### ISSUE TITLE
Loud audio is distorted/clipping/blown out

### ISSUE THREAD

**Issue by K4LCIFER** [mpv-player/mpv#10080]
### Important Information

Provide following Information:
- mpv version: 0.34.0-253-g2cafe5137f
- Linux Distribution and Version: Arch Linux, Gnome 42.0, Wayland
- Source of the mpv binary: AUR
- If known which version of mpv introduced the problem: Unknown
- Window Manager and version: Gnome 42.0
- GPU driver and version: AMD Radeon RX6600

### Reproduction steps

Open a video with loud audio. Turn OS volume to max. Observe that audio clips, and is heavily distorted when loud audio is playing. Observe that clipping goes away if you turn down the OS volume. 

### Expected behavior
I expect to have clear audio

### Actual behavior
Loud audio is clipping/blown out/distorted. If I turn down system sounds through the OS, then the clipping is gone. I do not have overamplification enabled.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/8461254/output.txt)

**Comment by Dudemanguy** [comment]
Does this happen if you use use a different AO?

**Comment by MagiX13** [comment]
I had a similar issue which came with the version after 0.33.1-3 in arch.

Following the suggestion, I switched from pipewire back to pulseaudio and the issue was fixed (at least for me).

Let me know if you need any more info, happy to test

**Comment by fir3-1ce** [comment]
I'm having this problem too after deciding to remove my old mpv version on Ubuntu 22.04 LTS then building it from source into a deb package myself. Pipewire doesn't come with Ubuntu 22.04, but I enabled it myself with pipewire-pulse.

So far, adding an `ao=pulse` line to mpv.conf seems to have remedied the issue. I'll report back if something else goes wrong, but that seems to be the fix for me

**Comment by mysteryx93** [comment]
In 2024, I'm still having this issue on an up-to-date Arch distro.

Adding `ao=pulse` does solve the problem.

I do not know what is the trigger that caused this problem to start happening; as I was using MPV just fine before.
