### ISSUE TITLE
Mpv crashes when Windows switches audio channels/config.

### ISSUE THREAD

**Issue by Gygun** [mpv-player/mpv#10303]
### Important Information

- mpv version:  0.34.0-265-g305332f8a0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects. Built on Sun Apr 17 11:25:20 UTC 2022
- Windows Version: Windows 10 Pro 20H2 v19042.985

### Reproduction steps

My PC is connected via HDMI (from GTX 1080) to and audio receiver (Yamaha RX-V385). It tunnels my video and audio to get 24bit 192khz and 5 channels support.
I don't turn off my PC at night, but I turn off monitors/audio. When I do that, the audio channel of Windows switches to 2.0 48khz. I expect mpv to switch audio channels too.

### Actual behavior
Mpv doesn't switch audio channels and crashes. No error msg on screen, just closes by itself. There is an error in the log file. It's annoying because If I pause a video, go to sleep, and want to continue watching it the next day, I have to re open it and manual seek where I left off.

### Log file
`[ 525.746][v][ao/wasapi] OnDeviceStateChanged triggered on device {0.0.0.00000000}.{87eaef72-536e-4e60-8dc3-9420a27617ce}: requesting ao reload
[ 525.746][d][ao/wasapi] Uninit wasapi
[ 525.746][d][ao/wasapi] Thread Reset
[ 525.746][d][ao/wasapi] Thread shutdown
[ 525.746][v][ao/wasapi] OnDefaultDeviceChanged triggered: requesting ao reload
[ 525.748][d][ao/wasapi] Thread uninit done
[ 525.748][d][ao/wasapi] Thread return
[ 525.979][v][ao/wasapi] OnPropertyValueChanged triggered on device {0.0.0.00000000}.{87eaef72-536e-4e60-8dc3-9420a27617ce}
[ 525.979][v][ao/wasapi] Changed property: {b3f8fa53-0004-438e-9003-51a46e139bfc},11
[ 525.979][v][ao/wasapi] OnPropertyValueChanged triggered on device {0.0.0.00000000}.{87eaef72-536e-4e60-8dc3-9420a27617ce}
[ 525.979][v][ao/wasapi] Changed property: {b3f8fa53-0004-438e-9003-51a46e139bfc},12
[ 525.988][d][ao/wasapi] Uninit wasapi done
[ 525.989][v][af] User filter list:
[ 525.989][v][af]   (empty)
[ 525.989][v][af] [in] 48000Hz stereo 2ch floatp
[ 525.989][v][af] [userspeed] 48000Hz stereo 2ch floatp
[ 525.989][v][af] [convert] 48000Hz stereo 2ch floatp
[ 525.989][v][ao] Trying audio driver 'wasapi'
[ 525.989][v][ao/wasapi] requested format: 48000 Hz, stereo channels, floatp
[ 525.989][d][ao/wasapi] Init wasapi
[ 525.989][d][ao/wasapi] Find device ''
[ 525.994][v][ao/wasapi] No device specified. Selecting default.
[ 525.998][v][ao/wasapi] Selecting device '{d3473d28-a696-4460-aed3-a0ef20895592}' (RX-V385 Center (NVIDIA High Definition Audio))
[ 525.998][v][ao/wasapi] Monitoring changes in device {0.0.0.00000000}.{d3473d28-a696-4460-aed3-a0ef20895592}
[ 526.012][d][ao/wasapi] Init wasapi thread
[ 526.012][d][ao/wasapi] Activating pAudioClient interface
[ 526.013][d][ao/wasapi] Probing formats
[ 526.017][v][ao/wasapi] Trying stereo float (32/32 bits) @ 192000hz (shared) -> unsupported
[ 526.017][v][ao/wasapi] Fallback to mix format 5.1 float (32/32 bits) @ 192000hz
[ 526.017][v][ao/wasapi] Accepted as 5.1 float @ 192000hz -> 5.1 float (32/32 bits) @ 192000hz (shared)
[ 526.017][d][ao/wasapi] Fixing format
[ 526.017][d][ao/wasapi] IAudioClient::GetDevicePeriod
[ 526.018][v][ao/wasapi] Device period: 10 ms
[ 526.018][d][ao/wasapi] IAudioClient::Initialize
[ 526.023][e][ao/wasapi] Error initializing device: AUDCLNT_E_UNSUPPORTED_FORMAT (0x88890008)
[ 526.023][d][ao/wasapi] Thread shutdown
[ 526.023][d][ao/wasapi] Uninit wasapi
[ 526.023][d][ao/wasapi] Thread uninit done
[ 526.023][d][ao/wasapi] Thread return
[ 526.023][d][ao/wasapi] Uninit wasapi done
[ 526.023][v][ao] Trying audio driver 'openal'
[ 526.023][v][ao/openal] requested format: 48000 Hz, stereo channels, floatp
[ 526.040][w][ao/openal] Direct channels aren't supported by this version of OpenAL`

Same thing happens with --no-config

**Comment by jeeb** [comment]
Seems like the older build just didn't have other AOs built in such as `openal` , which is why it cannot fall back onto them. openal sounds like the component which is actually causing the boom/sudden exit in this case.

Positive bit is that wasapi is actually attempted to reinitialize. Too bad it then ends up in errors.

**Comment by avih** [comment]
> I turn off monitors/audio. When I do that, the audio channel of Windows switches to 2.0 48khz

How do you know that it switches to stereo/48khz, and not simply get disabled?

**Comment by avih** [comment]
You can also try this script. Save it as `audio-device-reload.lua` in your scripts dir, and it should fix this issue. Therer's an explanation for what happens at comment inside the script:
```lua
-- see https://github.com/mpv-player/mpv/issues/10303

-- by default, when the audio device becomes unavailable (e.g. HDMI audio
-- and the display turns off), then unless --audio-fallback-to-null is enabled,
-- mpv drops the audio track - which is quite undesirable.
-- But even with --audio-fallback-to-null, when the device becomes available
-- again - e.g. HDMI audio and the display turns on, then mpv doesn't switch
-- to it if it previously fell-back to null.

-- this script addresses both issues:
--   1. it enables --audio-fallback-to-null
--   2. if the audio device list changes while ao is null - reload the ao
--      (e.g. find the HDMI audio after the display was turned on)

mp.set_property("audio-fallback-to-null", "yes")

mp.observe_property("audio-device-list", "native", function()
    -- let the AO settle (500 ms) after device change, then reload if null
    mp.add_timeout(0.5, function()
        if mp.get_property("current-ao") == "null" then
            print("reloading AO...")
            mp.command("ao-reload")
        end
    end)
end)
```

**Comment by Gygun** [comment]
> You can also try this script. Save it as `audio-device-reload.lua` in your scripts dir, and it should fix this issue. Therer's an explanation for what happens at comment inside the script:
> 
> ```lua
> -- see https://github.com/mpv-player/mpv/issues/10303
> 
> -- by default, when the audio device becomes unavailable (e.g. HDMI audio
> -- and the display turns off), then unless --audio-fallback-to-null is enabled,
> -- mpv drops the audio track - which is quite undesirable.
> -- But even with --audio-fallback-to-null, when the device becomes available
> -- again - e.g. HDMI audio and the display turns on, then mpv doesn't switch
> -- to it if it previously fell-back to null.
> 
> -- this script addresses both issues:
> --   1. it enables --audio-fallback-to-null
> --   2. if the audio device list changes while ao is null - reload the ao
> --      (e.g. find the HDMI audio after the display was turned on)
> 
> mp.set_property("audio-fallback-to-null", "yes")
> 
> mp.observe_property("audio-device-list", "native", function()
>     -- let the AO settle (500 ms) after device change, then reload if null
>     mp.add_timeout(0.5, function()
>         if mp.get_property("current-ao") == "null" then
>             print("reloading AO...")
>             mp.command("ao-reload")
>         end
>     end)
> end)
> ```

Wow, thank you for the script! It makes sense now of why it's happening.
Sadly, the fix didn't work. I see in the log that the property is active (line 73, line 130), but mpv is still crashing after I turn off the HDMI connection.
I removed all my other scripts, just in case, but with no luck.

I attached the full log here.
[log.txt](https://github.com/mpv-player/mpv/files/8961125/log.txt)
.

**Comment by avih** [comment]
Could you please add to your config `ao=wasapi` (or launch mpv with `--ao=wasapi`) and post another log ? This should help us rule out other AOs, such as OpenAL which mpv seem to attempt.

Aso, can you describe (exactly if possible) what you do (before and) after you launch mpv which results in this crash?   (example of such description: make HDMI audio output as default, launch mpv to play some mp3 file, switch audio output to speakers from the tray icon, result -> mpv crashes).

**Comment by Gygun** [comment]
> Could you please add to your config `ao=wasapi` 
**It worked!**

Steps to reproduce the crash without that config:

-Using HDMI audio (2.0/5.0 24bit 192khz)
open mpv
drag and drop a video (mp4). Tried to pausing it before, but same result.
turn off the receiver (Windows blinks like when you alt tab from a full screen game, with a few secs in black screen, and resets the audio and the video).
*mpv crashes in the background*
After a few secs, video from and audio from OS is up again (This time only 2.0 48hz audio)
Then I can try turn on the receiver, Windows blinks again, and automatically switches back to 2.0/5.0 192khz.

Log attached again
[log.txt](https://github.com/mpv-player/mpv/files/8961291/log.txt)

**Comment by avih** [comment]
> It worked! Thank you!

Right, so the previous log where it did crash shows that mpv was trying to use OpenAL after the audio configuration changed, and with `ao=wasapi` it doesn't try to any other AOs, and it doesn't crash.

This means there's probably some issue with OpenAL audio in mpv, either in mpv code, or in OpenAL code.

Unfortunately I don't think many mpv developers use OpenAL, but hopefully someone will find the time at some stage to look into it.

> ...
> turn off the receiver (Windows blinks like when you alt tab from a full screen game, with a few secs in black screen, and resets the audio and the video).
> _mpv crashes in the background_

Does it also happen if, instead of turning the receiver off, you left-click the speaker icon at the taskbar tray, then click the name of the output at the top (just above the slider) and then choose a different output, for instance speakers?

> Log attached again
> [log.txt](https://github.com/mpv-player/mpv/files/8961291/log.txt)

Just to be clear, this new log is with `ao=wasapi` - where it does NOT crash, right?

**Comment by Gygun** [comment]
> Does it also happen if, instead of turning the receiver off, you left-click the speaker icon at the taskbar tray, then click the name of the output at the top (just above the slider) and then choose a different output, for instance speakers?

It didn't crash when I change to "speakers" (analog 3.5 input)
But... I have 2 displays via HDMI. One is the main display with digital audio via the receiver. The second one is not connected to it, but windows recognizes audio because it's a TV, so It appears in the audio devices list. If I try to change it to that one display, It crashes.
Tried to reproduce the crash with that device turned off but it doesn't help. Same bug happening.

> Just to be clear, this new log is with `ao=wasapi` - where it does NOT crash, right?

Yup, with that opt on, It doesn't crash =)

**Comment by Gygun** [comment]
Logs of what I just described.

[log-hdmi to hdmi.txt](https://github.com/mpv-player/mpv/files/8962111/log-hdmi.to.hdmi.txt)
[log-hdmi to speakers.txt](https://github.com/mpv-player/mpv/files/8962113/log-hdmi.to.speakers.txt)

**Comment by avih** [comment]
Thanks. Hopefully some will be able to look into it.
