### ISSUE TITLE
mpv crashes when capturing a screenshot

### ISSUE THREAD

**Issue by xvim64** [mpv-player/mpv#10349]
### Important Information

Provide following Information:

- mpv version
mpv-x86_64-20220626-git-3a2838c.7z

- Windows Version
Windows 10 x64 21H2

- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220626-git-3a2838c.7z/download

- If known which version of mpv introduced the problem
mpv-x86_64-20220626-git-3a2838c.7z

- Possible screenshot or video of visual glitches
https://user-images.githubusercontent.com/83569599/176580809-25be96d4-5e1f-4958-af14-d04a14ff718f.mp4

### Reproduction steps

1. start mpv with any video file

2. screen-shot

### Expected behavior

no crash when capturing screenshot

### Actual behavior

crash of mpv

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/9016057/log.txt)

### Sample files

[ Spring ]
https://www.youtube.com/watch?v=WhWc3b3KhnY

**Comment by n-buna404** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/issues/228
20220629 build fixed this problem. please update

**Comment by thebombzen** [comment]
> [shinchiro/mpv-winbuild-cmake#228](https://github.com/shinchiro/mpv-winbuild-cmake/issues/228) 20220629 build fixed this problem. please update edit; seems like still not working for .jxl

What do you mean by "not working"? There was a bug preventing screenshots in specific cases in libjxl that has been fixed as of libjxl@341a7ebc699a06c557200fb43a14c8b1c09d4197 so once shinchiro updates that, it should work fine.

**Comment by n-buna404** [comment]
> > [shinchiro/mpv-winbuild-cmake#228](https://github.com/shinchiro/mpv-winbuild-cmake/issues/228) 20220629 build fixed this problem. please update edit; seems like still not working for .jxl
> 
> What do you mean by "not working"? There was a bug preventing screenshots in specific cases in libjxl that has been fixed as of [libjxl/libjxl@341a7eb](https://github.com/libjxl/libjxl/commit/341a7ebc699a06c557200fb43a14c8b1c09d4197) so once shinchiro updates that, it should work fine.

as of 20220630 build the screenshot to jxl still not working ( it will show error taking screenshot and create jxl files with 0 bytes). but build before like 20220623 had no problem until commit https://github.com/shinchiro/mpv-winbuild-cmake/commit/ac5c78fff3757e7cc7afc9ebea7b85d0136d61c0

**Comment by jimmy-1000** [comment]
> There was a change about 7 days ago in FFmpeg's libjxl wrapper that makes it trigger the bug fixed by [libjxl/libjxl@341a7eb](https://github.com/libjxl/libjxl/commit/341a7eb). You'll need to wait for the libjxl update to get it to work.

Last version of mpv (mpv 0.34.0-365-g369168b9be / mpv-x86_64-20220703-git-369168b.7z ) has this problem.
Do we need the last version of ffmpeg ?

**Comment by thebombzen** [comment]
You have to wait until shinchiro uses a recent-enough version of libjxl.

**Comment by garoto** [comment]
Shinchiro's next auto-build in a few of hours will have a commit-revert in `libjxl.cmake` that should address any new developments in libjxl repository. 

https://github.com/shinchiro/mpv-winbuild-cmake/commits/master/packages/libjxl.cmake

**Comment by n-buna404** [comment]
![Screenshot 2022-07-04 092022](https://user-images.githubusercontent.com/68980945/177065259-de6287a8-7449-4918-9250-cd5cec036ec8.png)
still not fixed as of 20220704 build released an hour ago. kinda back 20220630 which png works but jxl don't

**Comment by garoto** [comment]
Poor shinchiro. Together with zimg recent changes and this whole `libjxl` compilation issues for the past... what? 2 months already? Gee...

**Comment by shinchiro** [comment]
It's either libjxl or ffmpeg problem. You can try grab ffmpeg and run `ffmpeg -i input.mkv -vframes 1 -ss 10 out.jxl`. Current ffmpeg's git master threw error:
```
[libjxl @ 000002063ddeaa80] Unknown transfer function, assuming IEC61966-2-1/sRGB. Colors may be wrong.
Error submitting video frame to the encoder
Conversion failed!
```

**Comment by shinchiro** [comment]
Unfortunately, it still happen with latest git of libjxl and ffmpeg

**Comment by thebombzen** [comment]
@shinchiro https://patchwork.ffmpeg.org/project/ffmpeg/patch/20220707183248.129374-1-leo.izen@gmail.com/

**Comment by thebombzen** [comment]
Warning is expected if the video doesn't tag its colorspace
