### ISSUE TITLE
Drastic brightness changes with gpu-next

### ISSUE THREAD

**Issue by FCrane** [mpv-player/mpv#10824]
### Important Information

Provide following Information:
- libmpv (latest version from git)
- Windows 11 22H2
- shinchiro build 30-10-2022

gpu-next produces frequent drastic brightness changes with tone-mapping = auto and HDR video on an SDR Windows desktop!

Here's an example of the conf that causes the issue:
vo = gpu-next
hdr-compute-peak = yes
target-peak = 100
tone-mapping = auto

During playback, the brightness drastically changes (bright -> low and low -> bright) many times during playback (always at the same time codes).

Using:
vo = gpu-next
hdr-compute-peak = yes
target-peak = 100
tone-mapping = bt.2390
tone-mapping-param = 1.0

(or actually anything except "auto") does not show this issue.

What does "auto" select for BT.2020 files? Why is it reselected during playback? Using "bt.2446a" results in an extremely dark picture.

### Expected behavior
Constant picture brightness.

### Actual behavior
Changing brightness.

**Comment by haasn** [comment]
Can you show me a sample file that exhibits this issue? I guess it has to do with dynamically changing metadata, but I have no files like this to test with.

**Comment by FCrane** [comment]
I have a test clip, that is 30 seconds (56 MB). How can I attach it here? The "https://0x0.st/" thing is too complicated - I have no idea how to use it or how to reference the upload...

If it's dynamically changing metadata, tone mapping bt.2390 with hrd-compute-peak should also get it wrong?

**Comment by haasn** [comment]
> tone mapping bt.2390 with hrd-compute-peak should also get it wrong?

No, `hdr-compute-peak` is entirely separate and happens entirely on the GPU. It cannot affect the `auto` algorithm selection.

> I have a test clip, that is 30 seconds (56 MB). How can I attach it here?

You may be able to just attach it directly to the GitHub issue. Or if that doesn't work, upload it anywhere else and send a link.

**Comment by FCrane** [comment]
[TestClip.zip](https://github.com/mpv-player/mpv/files/9920863/TestClip.zip)

I was able to cut it down to meet the max attachment size (25 MB). This clip shows the issue well: near the end, the brightness flickers extremely. Generally it's much too dark (compared to bt.2390).

Strangely, the brightness change seems to be dependent on the length of the clip, meaning that a longer clip (starting a few seconds before this one) will show a different behaviour, like changing to bright once and then to dark a few seconds later instead of the heavy flickering...

bt.2390 plays the clips perfectly fine, bright (much brighter than auto) and with constant brightness...

**Comment by haasn** [comment]
Oh, I've identified the source of the issue. It's actually an unexpected and undesired *interaction* between `hdr-compute-peak` and the way `auto` gets resolved.

**Comment by haasn** [comment]
Should be fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/322

**Comment by FCrane** [comment]
Thanks! When is the fix going to be included in the shinchiro builds so that I can test it?

Also: what exactly does "auto" do? I did not find any "real" 
explanation for it for "tone-mapping" and "target-peak"... How can I find out which values are actually chosen by mpv? Is "auto" evaluated once at start of playback (or when the file is loaded) or are the values evaluated continuously? It's very confusing and all parameters seem to interfere with each other so it's almost impossible for me to find a configuration that works for HDR as well as for SDR... Even worse, there seem to be media files that use bt.2020 but without any HDR meta data!

How can I determine that from within mpv? "video/primaries" only gives "bt.2020" or "bt.709", but no info about HDR metadata present or not...

Thanks!

**Comment by haasn** [comment]
> Also: what exactly does "auto" do?

From the patch:

```c
    if (par->function == &pl_tone_map_auto) {
        float src_max = pl_hdr_rescale(par->input_scaling, PL_HDR_NORM, par->input_max);
        float dst_max = pl_hdr_rescale(par->output_scaling, PL_HDR_NORM, par->output_max);
        float ratio = src_max / dst_max;
        if (ratio > 10) {
            // Extreme reduction: Pick spline for its quasi-linear behavior
            par->function = &pl_tone_map_spline;
        } else if (src_max < 1 + 1e-3 && dst_max < 1 + 1e-3) {
            // SDR<->SDR range conversion, use linear light stretching
            par->function = &pl_tone_map_linear;
        } else if (fmaxf(ratio, 1 / ratio) > 2) {
            // Reasonably ranged HDR<->SDR conversion, pick BT.2446a since it
            // was designed for this task
            par->function = &pl_tone_map_bt2446a;
        } else if (ratio < 1) {
            // Small range inverse tone mapping, pick spline since BT.2446a
            // distorts colors too much
            par->function = &pl_tone_map_spline;
        } else {
            // Small range conversion (nearly no-op), pick BT.2390 because it
            // has the best asymptotic behavior (approximately linear).
            par->function = &pl_tone_map_bt2390;
        }
        par->param = par->function->param_def;
    }
```

**Comment by FCrane** [comment]
If this constantly changes during playback, there's no way to prevent irregularities and therefore visually incorrect brightness and color changes...

Should be evaluated and set once when the file is loaded and then the selected tone mapping should be kept throughout the whole media file.

However, my observations are, that this indeed seems to change dynamically - is this intended? Or is it caused by the "auto" issue?

**Comment by aufkrawall** [comment]
:tada: 
Looks like this has finally fixed distinct brightness fluctuations with compute-peak? I'm sill seeing this issue in LG chess demo with mpv-x86_64-v3-20221030-git-f594482 build on Windows, whereas it's gone with own git-master builds of libplacebo and mpv I use on Linux.

**Comment by GH0STDATA** [comment]
This issue still seems to be persistent on the latest version of mpv for Windows when tone mapping any kind of Dolby Vision content specifically. I've posted the version of mpv I'm having issues with below. If any other information is needed, please let me know.

```
mpv 0.35.0-20-ge1a04cd8ac Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
built on Tue Nov 22 12:40:58 2022
libplacebo version: v5.229.1-33-g7ead30d
FFmpeg version: git-2022-11-21-c0c0a5f10
FFmpeg library versions:
   libavutil       57.43.100
   libavcodec      59.54.100
   libavformat     59.34.101
   libswscale      6.8.112
   libavfilter     8.50.101
   libswresample   4.9.100
```

**Comment by haasn** [comment]
Can you post a sample to reproduce the issue (preferably in a new issue)?

**Comment by GH0STDATA** [comment]
> Can you post a sample to reproduce the issue (preferably in a new issue)?

It looks like its fixed now on Shinchiro's latest v3 build, thanks for responding though!

**Comment by Sinkingsun** [comment]
HDR flickering is still happening with Dolby Vision sources for me. Haven't been able to fix it with any .config changes.

LG C2 @ 120Hz 4:4:4 @ 12bpc

**Comment by markg85** [comment]
This exact issue still persists to this very day with the exact same settings as the initially posted here.
Now my setup is on Linux with no HDR features enabled.

It is difficult to pinpoint exactly which HDR videos have it. Demo videos are annoyingly enough so full of action that it doesn't show at all. Movies, specifically the dialog scenes, show it. In my specific case the Dark Phoenix movie shows is **very** prominently. But for example Strange new worlds (HDR10+) shows nothing.

When the brightness changes constantly, even subtly, it's a highly unpleasant viewing experience.

How do i debug this, what info do you need to know to figure things out?

Can this issue be reopened? Making a new issue works fro me too even though it seems a bit redundant.

**Comment by kasper93** [comment]
> How do i debug this, what info do you need to know to figure things out?

It's known issue, you can try those settings to make it more stable https://github.com/mpv-player/mpv/issues/12756#issuecomment-1927544909
