### ISSUE TITLE
Subtitle border stretched horizontally (regression?)

### ISSUE THREAD

**Issue by clr134** [mpv-player/mpv#11825]
### Important Information

Provide following Information:
- mpv version
mpv 0.35.0-445-g650c53df

- Platform and Version
Windows 10 x64

- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/

### Reproduction steps

1. Download the [0.34.0-230-g7ac4b7dfe7](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220313-git-7ac4b7d.7z/download) build, download the latest build.
2. Play the video in the latest version until the subtitle line appears, pause.
3. Play the video in the older version until the subtitle line appears, pause.
4. Compare the output.

Reproducible with no-config. I did not check when exactly the regression happened, it's just the build I happened to check.

### Expected behavior

Border is rendered evenly in both directions.

### Actual behavior

mpv currently stretches the border horizontally, regardless of the settings (at least border/shadow related).

### Log file

Old version: https://0x0.st/HQ8T.txt
New version: https://0x0.st/HQ8c.txt

### Sample files

https://0x0.st/HQ8b.mkv

**Comment by llyyr** [comment]
libass "feature". See https://github.com/libass/libass/issues/690 and related discussion on https://github.com/libass/libass/issues/689

**Comment by TheOneric** [comment]
> Can mpv not change it on their end, passing the correct display resolution to libass?

mpv can, how is described in the first reply of [libass/libass#690](https://github.com/libass/libass/issues/690#issuecomment-1500971203): override the bad converter’s `PlayResX` to match the DAR of the actual video. Ideally this should be fixed in ffmpeg (and any other affected converter) directly, though I lack familiarity with ffmpeg API to make any call on how to best do that.

To save everyone some time, libass/libass#690’s first reply is also the only post in libass/libass#690 and libass/libass#689 relevant for working around buggy converters in mpv. The others all are related to additional cropping methods llyyr used and some speculation about a possible solution in ffmpeg, theoretical hacky workarounds in libass etc *(there are no plans to realise such hacks atm)*.

**Comment by Kosm8** [comment]
llyyr's fix solves this issue with libass master.

**Comment by infini667** [comment]
Is this fixed? Because I'm using the version 0.35.0-511-gab300285 and I still have this issue.

**Comment by Kosm8** [comment]
The fix is still worked on https://github.com/mpv-player/mpv/pull/11831
