### ISSUE TITLE
[ao/alsa] Bad handling of PCM after waking up from suspension

### ISSUE THREAD

**Issue by 2ion** [mpv-player/mpv#1252]
Using the ALSA output, after suspending the computer while mpv was playing audio and resuming again, mpv doesn't resume playing but floods the terminal with the message:
```
[ao/alsa] Audio output is reporting incorrect buffer status.
[ao/alsa] PCM in suspend mode, trying to resume.
```
and does not play back audio. Playback will be resumed after toggling the audio with the switch_audio function (or re-starting the player, obviously).
This should be handled more elegantly/automatically, since for example the music player daemon (mpd) manages to 'bridge' a suspend-resume cycle just fine without failing ALSA output, and without user intervention.

**Comment by 2ion** [comment]
I forgot about this. In the current mpv, this is fixed.

**Comment by mistnim** [comment]
This is still a problem for me. I know that says that hardware doesn't support resume in the log. But I could do it just fine with mpv on debian.

### mpv version and platform
0.24 on archlinux

### Reproduction steps
play something, put the laptop on suspend, resume it from suspend

### Expected behavior
Playing on mpv resume

### Actual behavior
mpv hangs, I have to pause and unpause to resume playing, then this line comes up:

> [ao/alsa] PCM in suspend mode, trying to resume.

### Log file

http://sprunge.us/RjDh

**Comment by wm4** [comment]
I don't really see a problem here. Apparently it gives you a chance to continue after manual intervention. The ALSA API is fickle and garbage enough to make this a bit too hard, so why not just let users suffer from it.
