### ISSUE TITLE
Gpu context waylandvk and gpu api cuda don't work on KDE Plasma (but on GNOME do)

### ISSUE THREAD

**Issue by imartemy1524** [mpv-player/mpv#13250]
## Important Information

- mpv version: 
```
mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 19 2023 21:54:02
libplacebo version: v6.338.1
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```
- Linux Distribution and Version:
```
                   -`                    im@IMArch 
                  .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: GF63 Thin 11UD REV:1.0 
               `+oooooo:                 Kernel: 6.6.10-arch1-1 
               -+oooooo+:                Uptime: 2 hours, 14 mins 
             `/:-:++oooo+:               Packages: 1672 (pacman), 18 (flatpak) 
            `/++++/+++++++:              Shell: fish 3.7.0 
           `/++++++++++++++:             Resolution: 1920x1080 
          `/+++ooooooooooooo/`           DE: Plasma 5.27.10 
         ./ooosssso++osssssso+`          WM: kwin 
        .oossssso-````/ossssss+`         Theme: [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], BeautyLine [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       CPU: 11th Gen Intel i5-11400H (12) @ 4.500GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce RTX 3050 Ti Mobile 
  `+sso+:-`                 `.-/+oso:    GPU: Intel TigerLake-H GT1 [UHD Graphics] 
 `++:.                           `-/+/   Memory: 10813MiB / 15698MiB 
 .`                                 `/
```
- Graphics:
```
  Device-1: Intel TigerLake-H GT1 [UHD Graphics] vendor: Micro-Star MSI
    driver: i915 v: kernel arch: Gen-12.1 ports: active: eDP-1 empty: HDMI-A-1
    bus-ID: 00:02.0 chip-ID: 8086:9a68
  Device-2: NVIDIA GA107M [GeForce RTX 3050 Ti Mobile]
    vendor: Micro-Star MSI driver: nvidia v: 545.29.06 arch: Ampere pcie:
    speed: 16 GT/s lanes: 8 bus-ID: 01:00.0 chip-ID: 10de:25a0
  Device-3: SunplusIT HD Webcam driver: uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 bus-ID: 3-10:3 chip-ID: 5986:211b
  Display: wayland server: X.org v: 1.21.1.10 with: Xwayland v: 23.2.3
    compositor: kwin_wayland driver: X: loaded: intel,nvidia
    unloaded: modesetting,vesa alternate: fbdev,nouveau,nv dri: i965 gpu: i915
    display-ID: 0
  Monitor-1: eDP-1 model: ChiMei InnoLux 0x15e7 res: 1920x1080 dpi: 142
    diag: 394mm (15.5")
  API: Vulkan v: 1.3.274 surfaces: xcb,xlib,wayland device: 0
    type: discrete-gpu driver: nvidia device-ID: 10de:25a0
  API: EGL Message: EGL data requires eglinfo. Check --recommends.
```
Drivers:
```
lib32-vulkan-icd-loader 1.3.274-1
vulkan-headers 1:1.3.274-1
vulkan-icd-loader 1.3.274-1
vulkan-tools 1.3.269-1
```
Nvidia-smi:
```
Mon Jan  8 20:43:05 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3050 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0               8W /  35W |      7MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       631      G   /usr/lib/Xorg                                 4MiB |
+---------------------------------------------------------------------------------------+
```

- Source of the mpv:
I've tried binary package from aur, building `mpv` from the sources using meson, aur [mpv](https://archlinux.org/packages/extra/x86_64/mpv), [mpv-git](https://aur.archlinux.org/packages/mpv-git/), [mpv-full](https://aur.archlinux.org/packages/mpv-full) — everything gives the same error. 

## Expected behavior
`--gpu-context=waylandvk --gpu-api=vulkan` don't crashes on wayland KDE.

## Actual behavior
All issues started after I updated the whole system and mpv with it (using aur).
I'm unable to use VULKAN api anymore.
When I'm using vulkan wayland gpu api, I'm getting next error: 
```
[vo/gpu/libplacebo] vk->CreateSwapchainKHR(...): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/swapchain.c:620)
[vo/gpu/libplacebo] Failed (re)creating swapchain!
```
My command is: `mpv --gpu-api=vulkan --gpu-context=waylandvk /tmp/text.mkv --log-file=output.txt`
[output.txt](https://github.com/mpv-player/mpv/files/13865138/output.txt)

But when I use `--gpu-context=x11vk`, everything at least works (by the way, I'm on wayland KDE right now), but frame synchronization doesn't.
[log2.txt](https://github.com/mpv-player/mpv/files/13865262/log2.txt)
Video [record](
https://github.com/mpv-player/mpv/assets/41122604/dafc2d57-c9c0-4d58-95b8-53afd4787e2b
)

I found a way to synchronize frames by adding `--video-sync=display-resample-vdropс` parameter.

#### GNOME
I have also gnome installed on my PC, and on gnome everything works without any problems (no vsync problem, no wayland problem with same drivers).

**Comment by CounterPillow** [comment]
It seems both logs you've provided (output.txt and log2.txt) are using X11. Did you make a mistake while uploading them?

**Comment by philipl** [comment]
I checked on GNOME (I can't run KDE conveniently) and I verified we work fine with waylandvk, vulkan and with both nvdec and vulkan hwdecs on both pure nvidia and intel+nvidia offloading.

So there's nothing wrong on the mpv side.

It's possible KDE has something broken with respect to handling nvidia render offload, but it would surprise me.

We won't know for sure without the proper logs but maybe it's related to vulkan using the intel device (which will not work with nvdec)

**Comment by Dudemanguy** [comment]
Most likely, this is a either a driver problem or a plasma issue given the factors at play here (wayland compositors and nvidia).

**Comment by guidocella** [comment]
Probably fixed by driver 550: https://www.nvidia.com/Download/driverResults.aspx/218120/en-us/
"Fixed an issue that sometimes caused Wayland applications to run at less than one frame per second on Maxwell, Volta, and Pascal series GPUs."

**Comment by guidocella** [comment]
Fixed by driver 550.

**Comment by imartemy1524** [comment]
Updated the drivers. 
Still happening on NVIDIA-SMI 550.54.14, CUDA Version: 12.4
