### ISSUE TITLE
Horizontal and vertical lines appear when window is scaled 

### ISSUE THREAD

**Issue by Tiramisu561** [mpv-player/mpv#13998]
### Important Information

Provide following Information:
- mpv version `mpv v0.38.0-63-gb364e4a6`
- Windows Version `Version 22H2 (OS Build 19045.4291)`
- Source of the mpv binary: https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240421
- Possible screenshot or video of visual glitches 
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/117456100/98b9f573-3fd8-4532-8f26-3812016c2778)

### Reproduction steps

 `mpv --no-config --vo=gpu-next --autofit=50% "video_[B4DB49AE].mkv"` 

### Expected behavior
No horizontal or vertical lines when the window is scaled down.
![mpv-shot0008](https://github.com/mpv-player/mpv/assets/117456100/6a668a51-4249-4b49-93c7-4339c63305e2)

### Actual behavior
Horizontal and vertical lines, sometimes both to form a grid-like pattern appear, not every time but I would say they appear once every 5 times I go from full screen to windowed. Often they appear at the start of the playback when it is already windowed and then go away when fullscreened. They never appear in fullscreen, only when windowed 

[More screenshots uploaded here](https://slow.pics/c/iALC7Cva)

### Log file
[scale.txt](https://github.com/mpv-player/mpv/files/15131141/scale.txt)

### Sample files
[video_[B4DB49AE].mkv](https://0x0.st/XH2Z.mkv) but it is reproducible with other videos as well

**Comment by kasper93** [comment]
Can you install latest Intel GPU driver? `10.18.10.5161` are quite old and Intel has a history with completely output on certain drivers.

**Comment by llyyr** [comment]
Can you use `--show-profile=fast` and apply each option independently and see which one fixes it?

**Comment by Pentaphon** [comment]
I also have this issue on similar hardware and I find that only 16:9 and wider videos seem to have this issue. 4:3 aspect videos are unaffected.

**Comment by guidocella** [comment]
In the absence of old Intel hardware, this can be reproduced in a Windows virtual machine.

**Comment by kasper93** [comment]
> In the absence of old Intel hardware, this can be reproduced in a Windows virtual machine.

This is already fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/680

**Comment by OverWorldD** [comment]
Can confirm this problem still exists on windows build mpv v0.40.0-349-g83fafbfbe on older Intel GPU (HD 3000 in my case)
Can be fixed with the line --correct-downscaling=no as mentioned. However after uninstalling the beta and going back to 4.4 the issue disappears, so it's only in the beta that apparently some settings are different for the mpv player
