### ISSUE TITLE
Cannot cycle fullscreen after modifying geometry properties at runtime

### ISSUE THREAD

**Issue by IC0hO** [mpv-player/mpv#14005]
### Important Information

Provide following Information:
- mpv version
`mpv v0.38.0-70-g2e03e030 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects`
- Windows Version
`Windows 11 23H2    OS build:22631.3447`
- Source of the mpv binary
[https://github.com/shinchiro/mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake)
- If known which version of mpv introduced the problem
- GPU model, driver and version
GPU model: NVIDIA GeForce RTX 3070    Driver version: 552.22
- Possible screenshot or video of visual glitches

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

If the issue is performance-related, try to reproduce it with --no-config
--profile=fast, which is designed to work on lower-end mobile devices.
Additionally, enable hardware decoding with --hwdec=yes or the Ctrl+h shortcut.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
Modify the geometry property while mpv is running. After the modification, the player should be able to switch between fullscreen and window normally.
### Actual behavior
When the geometry property is modified during mpv runtime, the player cannot cycle fullscreen after the modification. After using the command such as mp.set_property("geometry", "100%:100%") in the lua script. The same situation is the same when entering "set geometry 100%:100%" in the console. The temporary solution now is to modify any player status, such as increasing or decreasing the volume, pausing and playing.
### Log file

Make a log file made with -v -v or --log-file=output.txt, attach it to
the issue, and replace this text with a link to it.
Without the log file, this issue will be closed for ignoring the issue template.
In the case of a crash, please provide a backtrace.
[output.txt](https://github.com/mpv-player/mpv/files/15137981/output.txt)
This situation appeared after the commit on April 19, 2024. I think the relevant commit is: https://github.com/mpv-player/mpv/commit/dc9da5d46367ab4ffd430a0afd92f9533c69494f

**Comment by Dudemanguy** [comment]
Fixed by 76367dae35ef4253e99205ccccf1dbccfc70bdfc

**Comment by JorgeR81** [comment]
I'm using mpv `0.40.0` and I still have this issue.

I can't set `fullscreen` to "no", if the `geometry` is changed in the same function, in a Lua script. 

This partially breaks the "Picture in Picture" feature / button in the tethys OSC ( https://github.com/Zren/mpv-osc-tethys/issues/39#issuecomment-3539184753 )

When "PIP" is enabled, `fullscreen` should be toggled off ( as you can see in the code line bellow ), but it does not work. 
https://github.com/Zren/mpv-osc-tethys/blob/master/osc_tethys.lua#L2286

Only if I remove the line that changes the `geometry` ( see bellow ), `fullscreen` is toggled off. 
https://github.com/Zren/mpv-osc-tethys/blob/master/osc_tethys.lua#L2289

**Comment by Dudemanguy** [comment]
```
function do_stuff()
    mp.commandv("set", "fullscreen", "no")
    mp.commandv("set", "geometry", "500x500")
end

mp.add_key_binding("v", "do-stuff", do_stuff)
```

Works for me. Same if I swap the order. Open a new issue with full details.
