### ISSUE TITLE
Twitch VODs not playing from the beginning

### ISSUE THREAD

**Issue by TheLongLife** [mpv-player/mpv#14840]
### mpv Information

```bash
mpv v0.38.0-567-g68a1a387 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jun 29 2024 00:14:16
libplacebo version: v7.349.0 (v7.349.0-rc1-3-g1fd3c7b-dirty)
FFmpeg version: N-116052-gd5e603ddc
FFmpeg library versions:
   libavcodec      61.9.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.4.100
   libavutil       59.27.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

```text
- Windows version: Windows 10 LTSC 1809
- GPU model, driver and version: irrelevant
- Source of mpv: Windows builds by shinchiro
- Introduced in version: n/a
```

### Reproduction Steps

1. Play Twitch VOD (by dragging the link to mpv window, or however you want)
2. Look at the progress bar / current time

### Expected Behavior

For video to start playing at the beginning 00:00:00

### Actual Behavior

It starts playing roughly a minute after the beginning. 

Seeking to beginning manually doesn't work, it just goes back to that same spot.  
In VLC it plays from the beginning without issues.

### Log File

[output.txt](https://github.com/user-attachments/files/16997000/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Sneakpeakcss** [comment]
Had the same issue some time ago and found out that `script-opts-add=ytdl_hook-use_manifests=yes` fixed this, but at the same time it stopped selecting the very best quality track no matter the `ytdl-format` setting.

**Comment by TheLongLife** [comment]
> Had the same issue some time ago and found out that `script-opts-add=ytdl_hook-use_manifests=yes` fixed this, but at the same time it stopped selecting the very best quality track no matter the `ytdl-format` setting.

Oh that does fix it. Thank you.  
It sets the quality to 720p but I can change it to higher resolution within UOSC stream quality menu, no problem.

**Comment by Sneakpeakcss** [comment]
> > Had the same issue some time ago and found out that `script-opts-add=ytdl_hook-use_manifests=yes` fixed this, but at the same time it stopped selecting the very best quality track no matter the `ytdl-format` setting.
> 
> Oh that does fix it. Thank you. It sets the quality to 720p ~but I can change it to higher resolution within UOSC stream quality menu, no problem.~ Actually changing the quality makes the beginning unplayable again xD

Calling it a fix was a bit generous. If you're using `mpv-twitch-chat` script, then it no longer shifts the subtitle by a minute forward, but if you either reload or progress the video too far, and seek to 00:00 then the issue comes back. To correct the quality i use a lua script + conditional profile:

```lua

mp.add_hook("on_preloaded", 50, function ()
    local title = mp.get_property_native("title")
    if title and title:find("Twitch VoD") then
        if mp.get_property("vid") ~= "1" then mp.set_property("vid", "1") end
        if mp.get_property("aid") ~= "1" then mp.set_property("aid", "1") end
    end
end)
```

```
[twitchvod]
profile-cond=get("path", ""):find("^https://www.twitch.tv/(.*)videos?") ~= nil
profile-restore=copy
script-opts-add=ytdl_hook-use_manifests=yes
title=Twitch VoD — ${media-title}
```

From what i remember both `vlc` and `mpc-hc` do not have this problem.

**Comment by CrendKing** [comment]
Thanks. According to my test, both the `on_preloaded` hook or the auto profile would be too late to change `script-opts`, because ytdl_hook is already executed on the [`on_load` hook with priority 10](https://github.com/mpv-player/mpv/blob/5c59f8accc44f3f31f1ef003e23643a5f5eaa0f3/player/lua/ytdl_hook.lua#L1214). I think an effective script would be something like
```
mp.add_hook('on_load', 0, function()
    if string.find(mp.get_property_native('stream-open-filename', ''), "^https://www.twitch.tv/videos/") then
        local script_opts = mp.get_property_native('script-opts')
        script_opts['ytdl_hook-use_manifests'] = 'yes'
        mp.set_property_native('script-opts', script_opts)

        -- select the best qualities
        mp.set_property('vid', 1)
        mp.set_property('aid', 1)
    end
end)
```

**Comment by Rochkiller** [comment]
I saw the solution in another issue, you need to add `--demuxer-lavf-o=live_start_index=0` to your command
Mine look like that : `& $Mpv $Url --demuxer-lavf-o=live_start_index=0`
I didn't try to add it in my mpv.conf but try this :

```
[twitchvod]
profile-cond=get("path", ""):find("^https://www.twitch.tv/(.*)videos?") ~= nil
profile-restore=copy
script-opts-add=ytdl_hook-use_manifests=yes
title=Twitch VoD — ${media-title}
demuxer-lavf-o=live_start_index=0
```

**Comment by CrendKing** [comment]
> --demuxer-lavf-o=live_start_index=0

I believe this is only needed for the VOD that is currently live (which yt-dlp has lengthy discussion at https://github.com/yt-dlp/yt-dlp/issues/13181). The original issue was already solved by `script-opts-add=ytdl_hook-use_manifests=yes`.

**Comment by kasper93** [comment]
If you are able to build ffmpeg/mpv you can try https://github.com/mpv-player/mpv/pull/17646 and https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/22610 

This fixes VODs of live streams, to allow seeking, this is the "subscribe only" feature on twitch page. Maybe it fixes also those issues described in this issue.

**Comment by talchas2** [comment]
That replaces `demuxer-lavf-o=live_start_index=0` and does the job for that better, in that it has the whole stream available for seeking immediately (it does still have the default starting point be the end, but if you didn't want that you can specify start=0 for a twitch profile). You still need `script-opts-add=ytdl_hook-use_manifests=yes; vid=1; aid=1`.

**Comment by Mikachu** [comment]
re the original report and not whatever the other comments are talking about:
from what I can tell, even though the timestamp in mpv starts around 1 minute in for twitch vods (ones that have finished, no live vod shenanigans), the actual video being played starts from the beginning. I confirmed this by playing a vod that starts with a countdown timer and it shows the exact same thing both in mpv and on the twitch website. also when you get towards the end of the vod, the video length gradually increases as it fills in the cache, until it is a minute longer than it was originally claimed to be.
Not sure if this was known already but I couldn't see this being stated in any of the other comments here, so just noting it in case it gives someone an "aha".

**Comment by kasper93** [comment]
Fixed by: https://github.com/mpv-player/mpv/commit/662d41093c27e52a6c0ae0bee00f59310d16aa83

**Comment by Sneakpeakcss** [comment]
> Fixed by: [662d410](https://github.com/mpv-player/mpv/commit/662d41093c27e52a6c0ae0bee00f59310d16aa83)

It does work on the initial load without manifests now, but the previously mentioned:

> if you either reload or progress the video too far, and seek to 00:00 then the issue comes back

Is still happening in a weird way.

However, i'm not sure if this is related to the original issue or a separate one related to seeking, but it looks to be exclusive to Twitch VODs, since Youtube works fine.

1. Open a Twitch VOD (preferably a very long one ~10h)
2. Seek few hours forward
3. Seek back to ~`00:00`
4. Seek back using keybinds or `seek -100` command

It seems to wrap around, and instead of stopping at `00:00` it seeks forward to somewhat random timestamps. 

You can also reproduce this more easily if you pause and reload with `Ctrl+r` at the beginning and then use `seek -3600` a few times. Instead of stopping at `00:00` it keeps seeking further and further forward.

**Comment by kasper93** [comment]
@Sneakpeakcss: Should be fixed by https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/23519 if you want to try.

**Comment by Sneakpeakcss** [comment]
> [@Sneakpeakcss](https://github.com/Sneakpeakcss): Should be fixed by https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/23519 if you want to try.

That does work. The only _'issue'_ i can find now is that after reloading (`Ctrl+r`), VODs from certain channels start at `00:00:02` instead of `00:00:00`. Other than that, everything seems to be working fine now.

___

> (…) this is unndeded work

[unndeded](https://code.ffmpeg.org/FFmpeg/FFmpeg/commit/8da63f6e4490f5ad7c92969c435e68db37cce29e)

SMH, what would xdev say…

**Comment by kasper93** [comment]
> > [@Sneakpeakcss](https://github.com/Sneakpeakcss): Should be fixed by https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/23519 if you want to try.
> 
> That does work. The only _'issue'_ i can find now is that after reloading (`Ctrl+r`), VODs from certain channels start at `00:00:02` instead of `00:00:00`. Other than that, everything seems to be working fine now.

I was fixing live playlists, and noticed this too. Should be fixed as part of https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/23735. It should clamp to the first segment now, instead of skipping 2s. It was due slightly off seek time and since the start of playback waits for keyframe it was discarding whole 2s until 2nd segment. Should snap now exactly to the start.
