### ISSUE TITLE
mpv window always moves to centre of screen when changing video

### ISSUE THREAD

**Issue by randomcoder67** [mpv-player/mpv#14911]
### mpv Information

```bash
mpv v0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 23 2024 17:46:22
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- Linux version: Arch (fully updated)
- Kernel Version: 6.10.10-arch1-1
- GPU Model: Intel Iris Xe
- Mesa/GPU Driver Version: OpenGL 4.6
- Window Manager and Version: i3 Window Manager 4.23 (also occurs on Xfce)
- Source mpv: Pacman
- Introduced in version: Latest, v0.39.0
```

### Reproduction Steps

(Note, I just tested this on Xfce4 and the issue also occurs there)

Run mpv and set the window to floating. Move the window somewhere on the screen, then skip to next track/video. The window will move to the centre

Seems to be related to geometry options, specifically geometry options inside a profile.

I narrowed my config down to this:

```
[AudioFiles]
profile-cond = (filename:match"%.mp3$" or filename:match"%.m4a$") ~= nil
geometry=25%
```

This causes the issue. Interestingly, moving the geometry argument outside of the profile, the issue no longer occurs:

```
geometry=25%
[AudioFiles]
profile-cond = (filename:match"%.mp3$" or filename:match"%.m4a$") ~= nil
```

### Expected Behavior

Window stays where it is

### Actual Behavior

Window moves back to centre on track skip

### Log File

[output.txt](https://github.com/user-attachments/files/17112727/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#user-content-How_do_I_apply_a_profile_only_once_with_Auto_Profiles

**Comment by randomcoder67** [comment]
> https://github.com/mpv-player/mpv/wiki/FAQ#user-content-How_do_I_apply_a_profile_only_once_with_Auto_Profiles

Thanks, this fixed it. The profile is now:

```
[AudioFiles]
profile-cond = (filename:match"%.mp3$" or filename:match"%.m4a$") ~= nil
profile-cond = not p["user-data/AudioFiles-applied"
geometry=25%
```

Did something change in the latest update, as my config worked okay before?

**Comment by guidocella** [comment]
4d80e7b72c

**Comment by randomcoder67** [comment]
> https://github.com/mpv-player/mpv/wiki/FAQ#user-content-How_do_I_apply_a_profile_only_once_with_Auto_Profiles

**Comment by randomcoder67** [comment]
I have found this issue also happens when playing YouTube videos. 

Using the following command:

`mpv --ytdl-format="best" --x11-name="mainfloating" --force-window=immediate "$url"`

The window will appear in the centre of the screen, despite and entry in i3conf telling it to be in the corner.

As before, moving the geometry argument outside of the profile fixes it, but:

`profile-cond = not p["user-data/AudioFiles-applied"]`

doesn't fix this instance of the issue.

**Comment by guidocella** [comment]
Isn'it it already fixed by be603f0539654289de742e5730f6737183fad622?

**Comment by randomcoder67** [comment]
> Isn'it it already fixed by [be603f0](https://github.com/mpv-player/mpv/commit/be603f0539654289de742e5730f6737183fad622)?

The original issue using local files is, the profile-cond line is no longer necessary for that.

Using the youtube links though the issue still seems to be occuring, regardless of whether the profile-cond line is present.

In my i3 config, I have this line:
`for_window [instance="mainfloating"] floating enable, move to workspace $ws5, move position 70 100`

If I run the mpv command when ws5 *is* focused, it will work fine, and i3 will position the window correctly. But if I run the mpv command when ws5 *is not* focused, it doesn't work, and ends up somewhere near the center of the screen

**Comment by guidocella** [comment]
Is it fixed by removing `--force-window=immediate`?

**Comment by guidocella** [comment]
Then the i3 rule is only applied at startup, but with `--force-window=immediate` the VO is reconfigured when playback starts and geometry is reapplied.

**Comment by Dudemanguy** [comment]
It's actually a deeper problem here. The fundamental reason is that mpv is not aware of the coordinates of the window until it is visible at least on i3. I did some tests fetching the coordinates of the windows and it always returns coordinates as if it was centered (since that's the default). It is also possible that i3 just doesn't move the window until you switch workspaces.

One way to simulate this is to use the `for_window [instance="mainfloating"] floating enable, move to workspace $ws5, move position 70 100` rule from above (or just `instance=mpv` if you want to shortcut it) and then open a playlist where the videos have different aspect ratios so a reconfigure has to be done. `vo_calc_window_geometry` will calculate it as if it was centered so the next video will get moved to the middle. `--force-window=immediate` happens to simulate the same thing.

I don't how this could be fixed from our end. It seems like a window manager thing out of our control. Also you can easily workaround this by just passing coordinates to `--geometry` which will work fine. So I'll go ahead and close this again since this particular thing is very different than what the original issue was reporting and that is indeed fixed.
