### ISSUE TITLE
Playback dim when display color space set to Rec. ITU-R BT.2020-1

### ISSUE THREAD

**Issue by low-batt** [mpv-player/mpv#15138]
### mpv Information

```bash
mpv v0.39.0-170-g37159a8ee0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Oct 20 2024 00:54:23
libplacebo version: v7.349.0 (v7.349.0-18-g9e16c86f)
FFmpeg version: n7.1
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Other Information

```text
- macOS version: macOS 15.0 (24A335)
- Source of mpv: My own build of master using mpv-build
- Introduced in version: Unknown
```

### Reproduction Steps

On a Mac that supports [Extended Dynamic Range](https://developer.apple.com/documentation/metal/hdr_content/displaying_hdr_content_in_a_metal_layer#3335505) and is running macOS Sequoia:
- Download a copy of the Apple Advanced stream
H.264/HEVC/UHD/Dolby Vision/Dolby Digital/Dolby Atmos example from [here](https://developer.apple.com/streaming/examples/advanced-stream-dv-atmos.html).
- Under the  menu click on `System Settings…`
- In the `System Settings` panel click on `Displays`
- Change the `Color profile` setting to be `Rec. ITU-R BT.2020-1`
- Run mpv like so:
mpv --no-config --autofit=50% --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint --tone-mapping=auto --target-peak=500 --vo=gpu-next ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4 
- Notice the picture is extremely dark

### Expected Behavior

With the `Color profile` of the display to `Rec. ITU-R BT.2020-1` the video looks somewhat similar how it looks when played with the Quicktime Player.

### Actual Behavior

With the `Color profile` of the display to `Rec. ITU-R BT.2020-1` the video is so dark that it is hard make out what is being shown. This screenshot shows mpv on top and the Quicktime Player below:
![Profile-changed](https://github.com/user-attachments/assets/af99f631-736d-4552-b4a9-232846662f71)

With the `Color profile` changed back to the default:
![Profile-default](https://github.com/user-attachments/assets/dbb261bf-3a6e-4b8a-a61a-876d7ba499a2)

This also happens with the `Color profile` set to `Rec. ITU-R BT.709-5`. With other `Color profile` settings this does not occur.

For the screenshots mpv was run like so:
```text
mpv/build/mpv --no-config --gpu-debug --log-file=output.txt --autofit=50% --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint --tone-mapping=auto --target-peak=500 --vo=gpu-next ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4 
```

This was reported against IINA in issue https://github.com/iina/iina/issues/5218

### Log File

[output.txt](https://github.com/user-attachments/files/17451863/output.txt)

### Sample Files

I downloaded a copy of the Apple Advanced stream example "H.264/HEVC/UHD/Dolby Vision/Dolby Digital/Dolby Atmos streaming" from [here](https://developer.apple.com/streaming/examples/advanced-stream-dv-atmos.html).

<details>
<summary><b>Media info:</b></summary>

```text
low-batt@urp Movies$ mediainfo Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4 
General
Complete name                            : Advanced stream H.264:HEVC:UHD:Dolby Vision:Dolby Digital:Dolby Atmos.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/dby1/iso2/mp41)
File size                                : 291 MiB
Duration                                 : 1 min 38 s
Overall bit rate                         : 24.7 Mb/s
Frame rate                               : 23.976 FPS
Writing application                      : Lavf61.1.100

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 1 min 38 s
Source duration                          : 1 min 38 s
Bit rate                                 : 23.0 Mb/s
Maximum bit rate                         : 24.0 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.116
Stream size                              : 270 MiB (93%)
Source stream size                       : 281 MiB (97%)
Title                                    : Core Media Video
Language                                 : English
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1375 cd/m2
Maximum Frame-Average Light Level        : 188 cd/m2
Codec configuration box                  : hvcC

Audio
ID                                       : 2
Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos
Codec ID                                 : ec-3
Duration                                 : 1 min 38 s
Bit rate mode                            : Constant
Bit rate                                 : 768 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 9.01 MiB (3%)
Title                                    : Core Media Audio
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1
Complexity index                         : Not present / 16
Number of dynamic objects                : 15
Bed channel count                        : 1 channel
Bed channel configuration                : LFE
Dialog Normalization                     : -27 dB
compr                                    : -0.28 dB
dialnorm_Average                         : -27 dB
dialnorm_Minimum                         : -27 dB
dialnorm_Maximum                         : -27 dB


low-batt@urp Movies$ 
```
</details>

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by low-batt** [comment]
An IINA user is encountering this without changing the display settings from the default, but so far I've not been able to trigger the problem that way.

**Comment by low-batt** [comment]
Here is the requested screenshot after pressing `I`:
![stats](https://github.com/user-attachments/assets/71da46d7-8526-49d2-b665-1a8ee618bfc8)


The screenshot was taken on a MacBookPro16,1 (6-Core Intel Core i7) running macOS 15.1.1.

To reproduce the problem you need to set the display's color profile to `Rec. ITU-R BT.2020-1` in macOS settings. I don't see `Rec. ITU-R BT.2020-1` as a choice on my M1 Mac running macOS Ventura. I would expect macOS Monterey is also missing `Rec. ITU-R BT.2020-1` as a choice. I think that value was added in macOS Sequoia.
![profile](https://github.com/user-attachments/assets/bd0c1d68-d5ca-4e5e-b3de-4faba74d61bf)


And yes, when I quit mpv it crashes. I believe that is the problem discussed in issue #12666.

**Comment by kasper93** [comment]
Where does the `target-peak=500` comes from? What value looks better `203`, `100`, `80`?

**Comment by low-batt** [comment]
This is also reproducible using the video [HDR10 - Sony Bravia OLED](https://www.demolandia.net/downloads.html?id=654828652) from [Demolandia](https://www.demolandia.net/) and the video [Sony: Whale in Tonga HDR](https://4kmedia.org/sony-whale-in-tonga-hdr-uhd-4k-demo/) from [4K Media](https://4kmedia.org/).

With IINA there is a history of reports from users of this dimming behavior when EDR is activated. But the problem has been hard to reproduce. It appears to be very sensitive to the type of chip, macOS version and the display. At one point the users with Macs that had M2 and M3 chips were reporting this problem, but we were not getting any reports from users with M1 based Macs. It seemed like the problem mostly cleared up for M2 and M3 Macs with macOS Sonoma although some users with external displays were still reporting problems. That this problem does not reproduce on your M1 MacBook Air lines up with the history of this problem being hard to reproduce.

This history was making me suspect a macOS defect. But now we have this example where the QuickTime Player does not exhibit the problem and mpv/IINA does playing the same video on the same Mac.

On the questions about `--target-peak`…

IINA obtains the `500` from macOS via the code found [here](https://github.com/iina/iina/blob/3578fedf8ff0422c9281762b17945ae4c1d3b840/iina/VideoView.swift#L483-L492). This is my older Intel MacBook Pro which has a peak brightness of 500.

Changing the value only makes a slight difference in the picture. With `--target-peak=80`:
![peak-80](https://github.com/user-attachments/assets/7a82aee5-3fce-430c-8c76-c8eab4cb7cf2)


With `--target-peak=200`:
![peak-200](https://github.com/user-attachments/assets/1fcf59f5-8e05-4580-a486-0b9d3a367277)


Without `--tone-mapping` and `--target-peak`:
![without-tone-mapping](https://github.com/user-attachments/assets/7b5664bf-0631-456d-a013-84375eb61d70)

**Comment by kasper93** [comment]
> Interestingly, I found similar results on some SDR videos.

Yes, rendering SDR videos with target-peak != 203 will make them dim. This is how libplacebo operates. This is exactly this issue https://github.com/mpv-player/mpv/issues/15411

What's unique in this (#15138) issue is that it happens with HDR videos in macOS environment. So let's limit this issue to HDR videos and discuss SDR in #15411 or even #8249 which is directly related.

> IINA obtains the 500 from macOS via the code found [here](https://github.com/iina/iina/blob/3578fedf8ff0422c9281762b17945ae4c1d3b840/iina/VideoView.swift#L483-L492). This is my older Intel MacBook Pro which has a peak brightness of 500.

Nice, wasn't aware you handle it. Recently we added similar display params extraction for Windows too.

> This history was making me suspect a macOS defect. But now we have this example where the QuickTime Player does not exhibit the problem and mpv/IINA does playing the same video on the same Mac.

Frankly this is surprising, it looks like PQ signal outputted from mpv is not interpreted correctly. Now, either there is something buggy on macOS side. Or... I have sneaking suspicion that HDR metadata is garbage, because memory allocations are not refcounted correctly. See #12666. Might be unrelated, but it looks suspicious to me. But I'm not macos user, I'm just trying to connect dots.

**Comment by low-batt** [comment]
Random memory corruption could certainly explain why the problem is so elusive. I see a fix to MoltenVK is in the works for #12666. Once the fix is available we can see if that also fixes this issue.

**Comment by low-batt** [comment]
Yes, if the problem requires use of MoltenVK then this problem is not related to #12666 as the problem can also be shown by invoking mpv similar to how IINA uses libmpv:
```text
mpv --no-config --gpu-debug --autofit=50% --cocoa-cb-output-csp=bt.2100-pq --pause --script-opts-append=osc-visibility=always --start=1:16 --target-prim=bt.2020 --target-trc=pq --tone-mapping=auto --target-peak=500 --vo=libmpv ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4
```

**Comment by low-batt** [comment]
ColorSync Utility displays a different MD5 signature on my Mac. Here is the file:
[ITU-2020.icc.zip](https://github.com/user-attachments/files/17972829/ITU-2020.icc.zip)

This is what I see in ColorSync:
![md5](https://github.com/user-attachments/assets/9cc24db2-2f93-43bc-b5ba-caad427f13f8)

**Comment by low-batt** [comment]
To test with that .icc file you can copy it to the user specific profiles directory:
```text
low-batt@urp Profiles$ pwd
/Users/low-batt/Library/ColorSync/Profiles
low-batt@urp Profiles$ ls
ITU-2020.icc
```

You will then see a second entry for `Rec. ITU-R BT.2020-1` appear in the macOS display settings.

Yes, if I change the color profile from one of the other profiles to `Rec. ITU-R BT.2020-1` or `Rec. ITU-R BT.709-5` while mpv is running the picture will change to being nearly black. Tailing the log file I only see a couple of messages when that happens:
```text
[  73.546][v][vo/gpu-next] Window size: 1792x1008 (Borders: l=0 t=0 r=0 b=0)
[  73.546][v][vo/gpu-next] Video source: 3840x2160 (1:1)
[  73.546][v][vo/gpu-next] Video display: (0, 0) 3840x2160 -> (0, 0) 1792x1008
[  73.546][v][vo/gpu-next] Video scale: 0.466667/0.466667
[  73.546][v][vo/gpu-next] OSD borders: l=0 t=0 r=0 b=0
[  73.546][v][vo/gpu-next] Video borders: l=0 t=0 r=0 b=0
```

With IINA there is a lot of history with this _symptom_ of the picture going black like this with EDR active. I don't know if this past IINA history is applicable or not to the problem at hand.

A lot of this history has made me strongly suspicious this is a macOS problem. My worry with blaming macOS has been that we could be doing something that macOS considers wrong where if you do that the behavior is "undefined" and might or might not work. 

The example at hand has invalidated my theory that it had something to do with OpenGL due to it reproducing using `--vo=gpu-next`. And now we have an example that shows QuickTime Player can play the same video without exhibiting the problem.

In the distant past IINA was not using `RGBA16Float`  for the `contentsFormat` of the view layer as shown in the Apple EDR examples. When IINA was changed to use `RGBA16Float` it seemed to reduce the occurrences of this problem.

From what I recall this problem was first encountered on M1 Macs after upgrading from Monterey to Ventura. Playing a HDR video was fine until you went into full screen mode. Then the video still was fine until the on screen controller was hidden. At that point the video turned black. If you moved the mouse to show the OSC, then the video was normal until the OSC disappeared again. As a workaround a horrible hack was added to IINA to add a nearly invisible view that was always shown. Sometimes this M1 problem would also exhibit as rapid flashing of the picture from light to dark.

Then the M2 came out and that workaround did not work on M2 Macs and the problem also was seen in windowed mode. Users reported they were able to workaround the problem by bringing up IINA's UI for cropping the picture and then _canceling_ that operation. I have no idea how that workaround could possibly work. As I did not have a M2 and the M1 was working fine, I could not investigate. When the M3 came out it behaved like the M2.

I believe when macOS Sonoma was released the problem no longer reproduced on the built in displays, but some users still reported it with external displays. It seemed like this was a macOS problem that was nearly fixed.

And now with macOS Sequoia it seemed like this problem might be coming back. There is a recent IINA issue reporting this problem under Sequoia without changing the display profiles. I was not able to reproduce that one.

I am always happy to help mpv with problems. Do not hesitate to ask me for information or to run experiments.

**Comment by low-batt** [comment]
Pretty much that is how IINA has been having to handle this elusive and hard to reproduce issue. If any interesting evidence comes in from new IINA issues I will update this issue with that information.

Currently I'm keeping my M1 running Ventura as I need to investigate an unrelated problem involving a change in macOS behavior in Sequoia that is causing an IINA glitch. I'll be sure to test this issue once I upgrade my M1 to Sequoia.

**Comment by kasper93** [comment]
I know nothing about macOS, but after #16512 it should be possible to implement `preferred_csp` for macOS Vulkan context which would tell exactly what image parameters are expected to be rendered so that is looks correctly.

I asked @Akemi about this, but at this point it is not sure how to extract this information in a best way. Suggestions welcome.

**Comment by kasper93** [comment]
Could someone affected do a test with different values `--target-peak` and `--inverse-tone-mapping`, so we can understand what kind of signal macOS is expecting?

In general if it happens with colorspace hint and gpu-next, it means that metadata are wrong, because it should interpret PQ correctly.

**Comment by low-batt** [comment]
I'm around and I'm happy to run any tests you need me to run.

Since this issue was entered the Mac has been upgraded to macOS 15.5 and my brew installed mpv was upgraded to 0.40.0:
```
low-batt@urp 15138$ mpv --version
mpv v0.40.0 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.351.0
FFmpeg version: 7.1.1
FFmpeg library versions:
   libavcodec      61.19.101
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
low-batt@urp 15138$ 
```

I set the display color space set to Rec. ITU-R BT.2020-1 first invoked mpv like before to confirm the problem still reproduces:
```
mpv --no-config --gpu-debug --log-file=output.txt --autofit=50% --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint --tone-mapping=auto --target-peak=500 --vo=gpu-next ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4
```

That resulted in an **all black** window. I set the display back to the default `Color LCD` color space and still got an **all black** window. This brew installed mpv is failing to draw the window if `--pause` is used. Is that a known problem? Late here. I will investigate this some more tomorrow.

Due to that issue I have to let the video play a bit to see the picture. The problem still reproduces. Adding `--inverse-tone-mapping` did not make a difference. I tried different values for `--target-peak` and the picture is still dark like in the screenshots above.

I will build master if I get a chance tomorrow and report back.

**Comment by kasper93** [comment]
Thanks. Please try with latest master, but to me it looks like the MoltenVK is configuring output incorrectly. mpv is not really messing with anything macos related, unless there is something hidden in swift code, we should be using just a Vulkan output and configuration.

**Comment by Akemi** [comment]
> That resulted in an **all black** window. I set the display back to the default `Color LCD` color space and still got an **all black** window. This brew installed mpv is failing to draw the window if `--pause` is used. Is that a known problem? Late here. I will investigate this some more tomorrow.

i recently noticed that too. the initial frame isn't rendered resulting in a black frame. i didn't have time investigating yet what causes it or what has changed.

**Comment by Akemi** [comment]
> Thanks. Please try with latest master, but to me it looks like the MoltenVK is configuring output incorrectly. mpv is not really messing with anything macos related, unless there is something hidden in swift code, we should be using just a Vulkan output and configuration.

just purely as info where MoltenVK does the colour stuff:
https://github.com/KhronosGroup/MoltenVK/blob/main/MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm#L340-L389
https://github.com/KhronosGroup/MoltenVK/blob/main/MoltenVK/MoltenVK/GPUObjects/MVKSwapchain.mm#L519-L573

no idea how correct this mapping is. we shouldn't interfere with that from our side, since we mostly leave the metal layer like it is. so it's just MoltenVK > setting meta data of rendered content on layer > macOS tonemaps layer to the screens 'colour space' if necessary.

**Comment by kasper93** [comment]
Could you check in the log what colorspace is selected for the output surface? EDIT: in fact the log from the latest version would be great.

**Comment by low-batt** [comment]
I updated the Mac today to macOS 15.6 and upgraded all the brew installed software. I then built mpv from master @ commit 3132ad62a38b1177e97182fce83271ebe96cff96:

```text
low-batt@urp mpv-build (master %=)$ mpv/build/mpv --version
mpv v0.40.0-273-g3132ad62a Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
 built on Aug 14 2025 15:24:50
libplacebo version: v7.352.0 (v7.351.0-39-g430d4921)
FFmpeg version: n7.1.1
FFmpeg library versions:
   libavcodec      61.19.101
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
low-batt@urp mpv-build (master %=)$ 
```

With this build I am still seeing the black screen at startup I reported last night when using `--pause` and `--start`, but oddly not all the time. Do you want me to enter an issue for that?

Running the master build with the following options and with the Mac's display's color space set to Rec. ITU-R BT.2020-1 I still see the very dim picture shown in the screenshots above:
```text
mpv/build/mpv --no-config --gpu-debug --log-file=output.txt --autofit=50% --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint --tone-mapping=auto --target-peak=500 --vo=gpu-next ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4
```

This is the log file from that test run with the master build:

[output.txt](https://github.com/user-attachments/files/21780561/output.txt)

This is on a `MacBookPro16,1`, an Intel based 16" 2019 MacBook Pro using its internal screen which has a brightness of 500 nits. Full display specs [here](https://support.apple.com/en-us/111932).

**Comment by Akemi** [comment]
> Do you want me to enter an issue for that?

feel free to, then i/we at least don't lose track of it.

**Comment by kasper93** [comment]
black frame might be caused because `VK_COLOR_SPACE_PASS_THROUGH_EXT` on macOS is real pass-through, but libplacebo considers this currently as sRGB output.

Either way, I merged small fix for initial metadata, might also help.

**Comment by low-batt** [comment]
I will enter an issue for the `--pause` black screen problem. Friday busy for me so likely not until this weekend.

I pulled the latest comments and built master @ commit 7653cc8f096e41d39697280986f4e75534a12988. Same behavior. This is the log from that test:

[output.txt](https://github.com/user-attachments/files/21781445/output.txt)

**Comment by low-batt** [comment]
I also confirmed that master still shows the problem when mpv is invoked with `cocoa-cb-output-csp`, `target-prim`, `target-trc` and `--vo=libmpv`, which is how IINA configures `libmpv` when playing this file:

```text
mpv/build/mpv --no-config --gpu-debug --log-file=output.txt --autofit=50% --cocoa-cb-output-csp=bt.2100-pq --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint --tone-mapping=auto --target-peak=500 --target-prim=bt.2020 --target-trc=pq --vo=libmpv ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4
```

**Comment by kasper93** [comment]
Please also test with https://code.videolan.org/videolan/libplacebo/-/merge_requests/732 libplacebo curently select wrong initial colorspace.

**Comment by low-batt** [comment]
I applied the libplacebo patch and rebuilt. The problem still reproduces. This is the log from that test run:

[output.txt](https://github.com/user-attachments/files/21782522/output.txt)

**Comment by kasper93** [comment]
> I applied the libplacebo patch and rebuilt. The problem still reproduces. This is the log from that test run:
> 
> [output.txt](https://github.com/user-attachments/files/21782522/output.txt)

Could you please report those issue to MoltenVK?

**Comment by low-batt** [comment]
I'm confused as to how MoltenVK is involved as the problem is also reproducable  with `--vo=libmpv` which doesn't use Vulkan / MoltenVK.

**Comment by kasper93** [comment]
> I'm confused as to how MoltenVK is involved as the problem is also reproducable with `--vo=libmpv` which doesn't use Vulkan / MoltenVK.

MoltenVK should set all the colorspace output stuff by itself, as it exposes support for colorspaces and HDR metadata.

For libmpv, it will need custom implementation on mpv side probably.

Btw. what happens when you use `--icc-profile-auto --icc-use-luma`?

**Comment by low-batt** [comment]
Was tied up, away from computer…

I've reported the initial black screen problem in issue #16693.

With the display set to Rec. ITU-R BT.2020 and running mpv built form master with patched libplacebo and adding  `--icc-profile-auto --icc-use-luma`:
```text
mpv/build/mpv --no-config --gpu-debug --log-file=output.txt --autofit=50% --icc-profile-auto --icc-use-luma --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint --tone-mapping=auto --target-peak=500 --vo=gpu-next ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4
```

The picture changes significantly. Bottom is QuickTime:

![Image](https://github.com/user-attachments/assets/31e26b1d-9a8a-4e93-81e6-06739f9a0c1a)

Log file from that run:

[output.txt](https://github.com/user-attachments/files/21824884/output.txt)

**Comment by kasper93** [comment]
Could you show it with stats, page 1 and 2 to see what target brightness we target. Also add `--inverse-tone-mapping` to try not limit upper range of output.

```
[   2.375][v][vo/gpu-next/libplacebo] Opened ICC profile:
[   2.375][d][vo/gpu-next/libplacebo]     Raw black point: X=0.000000% Y=0.000000% Z=0.000000%
[   2.375][v][vo/gpu-next/libplacebo]     Contrast = 203 cd/m^2 : 0.001 mcd/m^2 ≈ 203000000 : 1
[   2.375][v][vo/gpu-next/libplacebo]     Detected primaries: ITU-R Rec. BT.2020 (Ultra HD)
[   2.375][v][vo/gpu-next/libplacebo]     Approximation gamma: 1.884 (stddev 0.2)
```

The ICC profile itself looks quite normal. But we can see this "Apple gamma" bs, which may be good indicator of the issue. (this also reminds me to send a patch for ffmpeg for this... (unrelated))

**Comment by kasper93** [comment]
Could you also check with libplacebo 430d4921a and `--icc-profile-auto --icc-use-luma --target-colorspace-hint=no` to test icc profile in pass through mode? Maybe this is what macos expects?

**Comment by low-batt** [comment]
I may be confused about what combination of options you wanted me to test with…

I rebuilt mpv with the latest master. I see the change to libplacebo was merged so I did not have to patch the sources.

Adding `--inverse-tone-mapping`:
```text
mpv/build/mpv --no-config --gpu-debug --log-file=output.txt --autofit=50% --icc-profile-auto --icc-use-luma --inverse-tone-mapping --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint --tone-mapping=auto --target-peak=500 --vo=gpu-next ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4
```

Changes the picture. Here with stats:

![Image](https://github.com/user-attachments/assets/5f836951-0274-482e-808b-25ddb9f735fe)

![Image](https://github.com/user-attachments/assets/1ec5e2b8-ba92-4821-9f5a-46c9d10c7644)

The log file for that run:

[output.txt](https://github.com/user-attachments/files/21846476/output.txt)

With `target-colorspace-hint=no`:
```text
mpv/build/mpv --no-config --gpu-debug --log-file=output.txt --autofit=50% --icc-profile-auto --icc-use-luma --pause --script-opts-append=osc-visibility=always --start=1:16 --target-colorspace-hint=no --tone-mapping=auto --target-peak=500 --vo=gpu-next ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4
```

Changes the picture as well:

![Image](https://github.com/user-attachments/assets/da19b36d-d22e-48ea-86a7-f73ab196aec1)

The log from that run:

[output.txt](https://github.com/user-attachments/files/21846497/output.txt)

None of these look like the picture shown by QuickTime.

**Comment by kasper93** [comment]
@low-batt: After reading a bit, it looks like macOS considers SDR peak luminance of display as diffuse while level. Could you experiment with changing the scaling value https://github.com/haasn/libplacebo/blob/2454df3382368b2806a053334ce6be27ab644c49/src/include/libplacebo/colorspace.h#L278

Although it shouldn't affect direct PQ playback, but when any processing happens that involves tonemaping it would matter. 

You probably should try with 500 nits for start, but I'm only guessing, there are some complexities how HDR works in your walled garden. XDR displays apparently can upscale HDR brightness in scaler, which is not something I've seen anywhere else.

**Comment by low-batt** [comment]
I'm unclear on which options I should be testing with.

Increasing that value darkens the picture.

The MacBook Pro I can reproduce this on is an old one from 2019 that does not have a XDR display. The peak brightness of it's display is 500 nits. For Macs with XDR displays the macOS display configuration is completely different and does not have the same setting. I was not able to reproduce this problem on my M1 MacBook Pro that has an XDR display.

IINA has had reports of some external displays exhibiting "dimming" when playing HDR videos. I do not know if that is related to the problem at hand or not.
