### ISSUE TITLE
Video stuttering on Windows 11

### ISSUE THREAD

**Issue by steo86** [mpv-player/mpv#15196]
### mpv Information

```bash
Hello,

I have the issue that video on Windows 11 is stuttering. Display refreshrate is set to match the video (23,976hz) and also when checking with "I" there are no framedrops. It´s just stuttering. 

This happens:

- When switchen between windows. Means swtichen between mpv and other windows with "alt+tab".
- Video is running fine for about 20-60 minutes fine without stutter in fullscreen and then begin to sutter suddenly.

To fix it I need to:
- Pause the video
- Jump to another Windows with "alt+tab"
- Jump back to mpv with atl+tab
- Unpause video

Then video is running fine again for a few minutes and starts stuttering again.
I have this with my customized config-file but also with a plank downloaded MPV without any config.
So it seems to be independent form the config ander shaders etc. In logfile no error is visible.
Someone haveing similar issues?
```

### Other Information

```text
- Windows 11 24H2
- Latest mvp build form git
- Nvidia RTX 4070 + I5-14400F
```

### Reproduction Steps

see description

### Expected Behavior

Video should not stutter.

### Actual Behavior

begins stuttering after a few minutes or when switching window.

### Log File

[outlog.log](https://github.com/user-attachments/files/17540972/outlog.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by steo86** [comment]
[outlog.zip](https://github.com/user-attachments/files/17586984/outlog.zip)
Attached a logfile with logging options set to maximum (--msg-level=all=trace)
Video was running fine first minute and then began stuttering. 
Then I pressed pause 
--> see line **[ 105.444][v][cplayer] Set property: pause -> 1**
So stuttering began a few seconds before that line. Maybe someone is seeing whats going wrong?

**Comment by the-database** [comment]
I have the same issue, stuttering on Windows 11 running the latest NVIDIA driver, no frame drops reported by mpv but the video is clearly dropping frames sometimes. 

The only way I was able to work around the issue is to downgrade NVIDIA driver to 551.86. Not sure if there's any way to avoid the issue while running the latest driver.

**Comment by steo86** [comment]
it has something to mpv is synchronizing Video and Audio.

If I set "video-sync=desync" suttering goes away but then A/V is getting out of sync.

With "video-sync=display-resample" it often runs fine for about half an hour and then begins stuttering (no framedrops). 
By pressing pause in some cases it´s then working again.

All other settings like "video-sync=audio" are even worse and stuttering begins earlier.

So with A/V-Sync activated the "display-resample" is the best one but begins also stuttering. Sometimes after 10 mintues, sometimes after 30 minutes. 

I am using wasapi output and passing though DTS/ATMOS via HDMI. So no decoding in MPV.
Anyone has an idea how to get it working with "display-resample"?

**Comment by nissel** [comment]
I'm seeing the same thing with a similar configuration. 24H2, nvidia, video-sync=display-resample and pass through audio.

I force vsync on in the nvidia control panel and things mostly play smoothly, but after some time I do sometimes to some output frame drops.

**Comment by kasper93** [comment]
Could you try using `video-sync=display-vdrop`? `display-resample` relies on being able to resample audio to compensate for A/V drift. Apparently, things go wrong when it cannot do that, as is the case with audio passthrough.

**Comment by steo86** [comment]
there is definitely an difference when choosing for example display-vdrop/audio and display-resample. Stuttering begins directly when using display-vdrop/audio instead of display-resample where stuttering starts after a few minutes.
Als there are different additional settings (vsync-ratio/vsync-jitter) when pressin "I" compared to display-resample. So I think the different settings are working also with paththrough audio. As said best setting is display-resample where stuttering starts after 20/30 minutes. or using desync where no stuttering appears but then A/V getting out of sync which you can see by pressing "I".

Here are my audio settings:
**volume-max=100 
volume=100
ao=wasapi
audio-exclusive=yes
audio-spdif=ac3,eac3,dts-hd,truehd,dts
audio-channels=7.1,5.1,stereo**

**Comment by llyyr** [comment]
Can you provide a log with video-sync=display-resample and display-vdrop?

**Comment by steo86** [comment]
for "display-resample" there is already a logfile 6 posts above:
[https://github.com/mpv-player/mpv/issues/15196#issuecomment-2449617406](url)
For display-vdrop I will generate one...

**Comment by llyyr** [comment]
> for "display-resample" there is already a logfile 6 posts above:

Well that one is completely useless because 99% of the log lines are about mkv decoding, which we don't care about here. --log-file sets a lower verbosity than trace for a reason

**Comment by steo86** [comment]
[outlog_display_resample.log](https://github.com/user-attachments/files/17716372/outlog_display_resample.log)
[outlog_display_vdrop.log](https://github.com/user-attachments/files/17716373/outlog_display_vdrop.log)
attached the logfiles for display-resample and display-vdrop with loglevel debug.
with display-vdrop it directly stuttered from the beginning and I can see "[vo/gpu-next] Render queue underrun." messages in logfile. With Display-Resample it went fine for about 20 minutes and then began stuttering. But there was nothing special coming up in the logfile when begin stuttering.

**Comment by kasper93** [comment]
Please test with minimal set of options to reproduce the problem.

```
'd3d11-sync-interval' = '0'
```
things like that are breaking display sync.

**Comment by steo86** [comment]
[outlog_syncInterval0.log](https://github.com/user-attachments/files/17728629/outlog_syncInterval0.log)
[outlog_normal.log](https://github.com/user-attachments/files/17728631/outlog_normal.log)
I have now reduced my config to the following. Attached the logfiles one with "d3d11-sync-inverval=0" and one wihtout.
In both cases it started suttering after a while then I paused the video and closed it.

**# audio
volume-max=100 
volume=100
ao=wasapi
audio-exclusive=yes
audio-spdif=ac3,eac3,dts-hd,truehd,dts
audio-channels=7.1,5.1,stereo

# a/v sync
video-sync=display-resample
# on first logfile enabled. On second logfile commented out.
#d3d11-sync-interval=0**

**Comment by steo86** [comment]
no one an idea?

**Comment by bigboo3000** [comment]
I have the same issue with Windows 11 24h2 and latest Nvidia GPU drivers, I downgraded driver to 561.09 and the issue is fixed.

I have the same issue with a laptop with AMD GPU, 24H2 and latest AMD drivers.

I think latest drivers have added support to new WDDM 3.2 features of 24H2 and one of them is causing trouble to mpv frame sync:
https://learn.microsoft.com/en-us/windows-hardware/drivers/what-s-new-in-driver-development

**Comment by TheRealBix** [comment]
> I have the same issue with Windows 11 24h2 and latest Nvidia GPU drivers, I downgraded driver to 561.09 and the issue is fixed.

I have my estimated Display Rate that shift down a bit after some playback (from 23.976 to 23.8 or something) I will try that

**Comment by bigboo3000** [comment]
![Capture d'écran 2025-01-08 184814](https://github.com/user-attachments/assets/a232920b-a87b-41cd-84a9-3c862f885ddc)
It's a screen capture on my laptop, you can see display refresh rate is badly estimated (it's 60Hz)

here is a log:
[output.zip](https://github.com/user-attachments/files/18351060/output.zip)

**Comment by TheRealBix** [comment]
You get that kind of desync after 1min ? For me it's harder to spot, I'd say it works well for 20min to 1 hour then starts to drop.

**Comment by bigboo3000** [comment]
yep with video-sync=display-resample it's really obvious with this setting, no need to wait 20min

**Comment by hooke007** [comment]
> no frame drops reported by mpv but the video is clearly dropping frames sometimes.

> It's a screen capture on my laptop, you can see display refresh rate is badly estimated (it's 60Hz)

I don't think you were talking about the same issue.

**Comment by the-database** [comment]
I may have fixed my stuttering issue by using this tool https://github.com/RedDot-3ND7355/MPO-GPU-FIX to disable MPO, TDR, and HAGS. I'm leaving a video running to see if it starts happening later, but so far everything is smooth. 

@steo86 If you still have the issue, could you see if this tool fixes it for you?

**Comment by steo86** [comment]
I will try it this week if this will fix it.

As workaround I was now going with active interpolation and fixed 60hz in nvidia for a while which is now working pretty well without stuttering and without soap-effect so I did not further investigate in this topic.

```
interpolation=yes
tscale=oversample
```

**Comment by MidnightWatcher** [comment]
So to confirm, which version of the nVidia drivers for Windows 11 is recommended for MPV -- 551.86 per @the-database or 561.09 per @bigboo3000 ?

**Comment by cinema-ONE** [comment]
> So to confirm, which version of the nVidia drivers for Windows 11 is recommended for MPV -- 551.86 per [@the-database](https://github.com/the-database) or 561.09 per [@bigboo3000](https://github.com/bigboo3000) ?

@MidnightWatcher: I have just downloaded und installed Nvidia Studio Driver 561.09. I found it on the [German Nvidia website](https://www.nvidia.com/de-de/drivers/details/232610/). This fixed the stuttering in 23.976 / 24 fps videos.

It would still be interesting if somebody knows of a newer version that is still "good".

**Comment by darkred3** [comment]
> I may have fixed my stuttering issue by using this [MPO-GPU-FIX tool](https://github.com/RedDot-3ND7355/MPO-GPU-FIX) to disable MPO, TDR, and HAGS (or just use [this .reg file](https://nvidia.custhelp.com/app/answers/detail/a_id/5157/%7E/after-updating-to-nvidia-game-ready-driver-461.09-or-newer%2C-some-desktop-apps) from NVIDIA to disable MPO).

Thanks a bunch @the-database. I had a similar issue where panning shots were stuttering a lot. Fullscreen was smooth though and video-sync=display-resample also fixed the issue in windowed mode. Using the MPO-GPU-FIX tool and applying **only** the HAGS Fix did the trick. Didn't need MPO nor TDR.
Couldn't try with an older Nvidia Driver due to being on 5060Ti. For reference I'm currently running 577.00 on 24H2 26100.4652.
**Edit:** Oh nevermind, today I noticed stuttering again. Turned on MPO Fix too and it's gone now.
**Edit2:** Nevermind again, the issue persists. HAGSFix works against immediate stuttering problems, but long into a video (20min+?) panning shots start stuttering in windowed mode again. MPO and TDR Fix don't do anything. Guess I'll have to try various things the next few days...
**Edit3:** Stuttering actually happens in fullscreen too after a while. The fix to that is going windowed, then fullscreen again. Very weird.

**Comment by nathanlucas** [comment]
@darkred3 
Have you tried setting setting **Power management mode** to **Prefer maximum performance**?  This resolved a lot of my frame drop issues.

**Comment by darkred3** [comment]
@nathanlucas No that did not change anything. I did however find out just now that the stutter is resolved when I have a video open in mpc-hc in the background, but only with madvr selected as the video renderer. To be precise, it is these two madvr options that do the trick (each on their own, both at the same time is not required):

_1. use Direct3D 11 for presentation (Windows 7 and newer)_
_2. present several frames in advance_ (works even when the number of frames to be presented in advance is set to the lowest (1))

I have not found any way to replicate these settings in mpv. I thought `gpu-context=d3d11` would replicate setting 1, but it doesn't for some reason.
@kasper93 Do you perhaps have an idea of what these settings do so different from mpv and a way to replicate them? Alternatively would it be possible to implement them in mpv?

**Comment by MidnightWatcher** [comment]
Well after trying multiple suggestions found above with limited success I've decided to try something different. I've now installed the latest nVidia studio drivers (v577.0) and decided to stop using d3d11va and the 3d311 api. I'm now trying out nvdec and vulkan instead. I've had zero stuttering for the last hour (before it would begin after about 20 minutes or even sooner if jumping around in the movie). I've commented out the d3d11 lines and updated my mpv.conf as follows:

hwdec=nvdec
gpu-api=vulkan
gpu-context=winvk
vulkan-async-compute=no
vulkan-async-transfer=yes
vulkan-queue-count=2
vd-lavc-dr=yes

Fingers crossed this fixes it completely.

For anyone interested, here's my full mpv.conf for use with my JVC X790 projector (feel free to comment or offer any suggestions for improvements):

## Miscellaneous ##
msg-level=auto_profiles=warn,autocrop=warn,autoload=warn,cplayer=warn
profile=high-quality
osd-bar=no
border=no
osd-font-size=10
osd-border-size=1
snap-window
autofit-larger=100%x88%
autofit-smaller=33%x66%
no-input-default-bindings
input-doubleclick-time=200
image-display-duration=inf
screenshot-template="%{media-title}-%P-%n"
screenshot-format=png

## Subtitles ##
slang=en,eng,english,English
subs-with-matching-audio=forced
sub-font-size=30
sub-border-size=0
sub-back-color=0.0/0.0/0.0/0.75
sub-shadow-offset=4

## Video and GPU Renderer ##
ontop
fullscreen=yes
vo=gpu-next
fbo-format=rgba16hf
hwdec=nvdec
gpu-api=vulkan
gpu-context=winvk
vulkan-async-compute=no
vulkan-async-transfer=yes
vulkan-queue-count=2
vd-lavc-dr=yes

#gpu-api=d3d11
#hwdec=d3d11va
#d3d11-exclusive-fs=yes
#d3d11-output-format=rgb10_a2

## Scalers and Shaders ##
glsl-shaders-clr
glsl-shaders-append="C:\Users\tmitc\AppData\Roaming\mpv\shaders\FSRCNNX_x2_8-0-4-1.glsl"
scale-blur=0.981251
glsl-shaders-append="C:\Users\tmitc\AppData\Roaming\mpv\shaders\KrigBilateral.glsl"
cscale=mitchell
correct-downscaling=yes
sigmoid-upscaling=yes
scale=ewa_lanczos4sharpest

## Deringing ##
scale-antiring=0.7
dscale-antiring=0.7 
cscale-antiring=0.7

## Dithering ##
temporal-dither=yes 
dither-depth=10

## Debanding ##
deband
deband-iterations=2
deband-threshold=48
deband-range=16
deband-grain=48

## Audio Bitstreaming ##
#ao=wasapi
audio-exclusive=yes
audio-spdif=ac3,eac3,dts,dts-hd,truehd
audio-channels=7.1,5.1,stereo
alang=en,eng,english,English
volume-max=100 	# maximum volume in %, everything above 100 results in amplification
volume=100		# default volume, 100 = unchanged

## OSD ##
input-default-bindings = no
input-ar-delay = 500
input-ar-rate = 20
keep-open = yes
keep-open-pause = no
osd-duration = 2000
screenshot-directory = '~~desktop/'
[protocol.https]

############
# Profiles #
############

[arrival picture adjustments]
profile-desc = Arrival Fix
profile-cond=string.match(p.filename, "%.Bland.")~=nil
contrast=45
brightness=-5
saturation=10
gamma=1
target-peak=50
target-trc=gamma2.0

[elevated blacks fix]
profile-desc = Elevated Blacks
profile-cond=string.match(p.filename, "%.ElevatedBlacksHD.")~=nil
contrast=0
brightness=-5
saturation=0
gamma=7
target-peak=90
target-trc=gamma2.0

[bt.2100-pq]
profile-cond=get("video-params/primaries") == "bt.2020" and get("video-params/gamma") == "pq"
profile-restore=copy
target-trc=gamma2.2
target-colorspace-hint=no
target-prim=dci-p3
tone-mapping=auto
tone-mapping-param=0.2
target-peak=70
hdr-compute-peak=yes
hdr-peak-percentile=99.99
hdr-contrast-recovery=0.6
hdr-contrast-smoothness=20.0
gamut-mapping-mode=auto
target-contrast=30000

[bt.2020]
profile-cond=get("video-params/primaries") == "bt.2020" and get("video-params/gamma") == "bt.1886"
profile-restore=copy
target-trc=bt.1886
target-prim=dci-p3
#target-prim=bt.709

[bt.709]
profile-cond=get("video-params/primaries") == "bt.709"
profile-restore=copy
target-colorspace-hint=auto
target-colorspace-hint-mode=source
#x target-prim = bt.709
target-trc = bt.1886
target-peak=90

[interlaced]
profile-cond=deinterlace or (get("video-frame-info/interlaced") and not deinterlace)
profile-restore=copy
deinterlace

[end]
profile-cond=eof_reached
profile-restore=copy-equal

**Comment by MidnightWatcher** [comment]
Update: Didn't fix it as I had hoped, can still get it to stutter. Sigh.

**Comment by TheRealBix** [comment]
> Update: Didn't fix it as I had hoped, can still get it to stutter. Sigh.

Thanks for feedback. I tried your settings too with no luck. Best results for me is d3d11va/d3d11 and maximum performance on nvidia driver. Not perfect tho.

**Comment by nathanlucas** [comment]
I think these vulkan settings are actually working a little better for me vs d3d11.  I would usually see a few frame rate glitches during a movie but so far after maybe 5 movies I haven't noticed any problems.  

Relevant bits from my setup:
3060 ti
9600X
577.00
HAGS and MPO disabled.
Nvidia settings: Vsync=On, Power management mode=Prefer maximum performance
Display mode set to 23.976 to match the movies
OS is very bare bones.  Have only installed enough to run madvr, basically.

While on vulkan I tried reverting my nvidia driver settings and also using something other than video-sync=audio/desync (display-vdrop), but all of that is still needed or I get drops again.

My whole mpv.conf:
```
vo=gpu-next

#gpu-api=d3d11
#hwdec=yes

hwdec=nvdec
gpu-api=vulkan
gpu-context=winvk
vulkan-async-compute=no
vulkan-async-transfer=yes
vulkan-queue-count=2
vd-lavc-dr=yes

panscan=1.0

target-peak=140
target-prim=bt.2020
target-contrast=inf
target-trc=gamma2.2

tone-mapping=mobius
tone-mapping-param=0.001

vf=format:dolbyvision=yes:hdr10plus=no
hdr-compute-peak=auto

video-sync=audio
audio-exclusive=yes
audio-spdif=dts-hd,truehd,eac3,dts,ac3

alang=en
slang=en
sid=auto
subs-fallback-forced=always
subs-with-matching-audio=forced

```

**Comment by nissel** [comment]
Just an fyi. I brought a cheap AMD RX 7600 for my htpc and this problem seems fine on AMD. Can't claim everything on AMD is fine but this strange stutter isn't present.

**Comment by netExtra** [comment]
> Just an fyi. I brought a cheap AMD RX 7600 for my htpc and this problem seems fine on AMD. Can't claim everything on AMD is fine but this strange stutter isn't present.

Nvidia drivers are known to have stutter issues and have been for years.  There's a few things you can do that help and there's maybe two drivers from last year that are known to be stutter free and even one of those still has issues with certain games. 566.36 is the most well known "stutter free" driver.  5000 series drivers have the reputation of just being plain bad. This doesn't surprise me because Nvidia no longer cares about RTX.

**Comment by MidnightWatcher** [comment]
Nvidia just released new Studio Drivers version 580.97 today. I'll give those a spin also.

**Comment by kasper93** [comment]
Is this stuttering, as a presentation issue? Or is this performance issue, which causes frames to be dropped? I think nvidia locks clocks when hwdec is enabled, does it also happen without hwdec?

Generally I would report this to nvidia and let them fix the issues.

**Comment by mitzsch** [comment]
I was able to fix the stuttering (that began after driver 512.96) by setting swapchain-depth=1 inside the mpv.conf... Maybe this is of interest to someone.

**Comment by MidnightWatcher** [comment]
> I was able to fix the stuttering (that began after driver 512.96) by setting swapchain-depth=1 inside the mpv.conf... Maybe this is of interest to someone.

I think this could be the key. Watched a whole film this evening, seeking back and forth, did some other testing, and I wasn't able to get it stuttering again. IMHO a value of 1 should be the new default.

**Comment by kasper93** [comment]
> IMHO a value of 1 should be the new default.

No, it shouldn't be. Report broken drivers to NVIDIA.

**Comment by TheRealBix** [comment]
I'm trying "swapchain-depth=1" too but AV seem to desync progressively, maybe it breaks "video-sync=display-resample".
I'll investigate further.

**Comment by MidnightWatcher** [comment]
> > IMHO a value of 1 should be the new default.
> 
> No, it shouldn't be. Report broken drivers to NVIDIA.

Or maybe then the reference manual can mention that nVidia users may need to set this to 1 if experiencing issues with problematic drivers.

**Comment by MidnightWatcher** [comment]
> I'm trying "swapchain-depth=1" too but AV seem to desync progressively, maybe it breaks "video-sync=display-resample". I'll investigate further.

Interesting. I'm sensitive to syncing issues and it was perfect on my end.  swapchain-depth=1 is the only change I made to my mpv.conf above.

**Comment by mitzsch** [comment]
> I'm trying "swapchain-depth=1" too but AV seem to desync progressively, maybe it breaks "video-sync=display-resample".


Is there a reason why you use display-resample over the default audio mode? 
Always use video-sync=audio (= default) and never had any problems, the problems started as soon as I changed to different modes. 
With default mode, I had a dropped frame every 40/45minutes on my Nvidia cards, due to bad EDID timings. (a problem only nvidia seems to have, especially at 23.976fps) => I then changed HDMI timings, and now I have not encountered any dropped frames again. 
A write-up on how to do it => https://forums.plex.tv/t/windows-tweak-24p-for-framedropless-playback-in-plex-htpc/883747

**Comment by TheRealBix** [comment]
> > I'm trying "swapchain-depth=1" too but AV seem to desync progressively, maybe it breaks "video-sync=display-resample".
> 
> Is there a reason why you use display-resample over the default audio mode? 

That's a good point. I think I started to use display-resample when I had those stutters and never though to get back to audio. However with the few episodes I watched since I read your message, "video-sync=audio" + "swapchain-depth=1" gave me perfect playback (up to 1hour episodes). Also, no need to set nvidia to max performance.
Thanks for your guide. I once used CRU + Pixel clock calc but I did not do the trick, don't remember why. I may try this again.

**Comment by bigboo3000** [comment]
> I was able to fix the stuttering (that began after driver 512.96) by setting swapchain-depth=1 inside the mpv.conf... Maybe this is of interest to someone.

I can confirm it fixed the issue for me too! thank you so much

**Comment by kasper93** [comment]
Might be fixed by https://github.com/mpv-player/mpv/pull/16817. Feel free to comment, if it's not.

**Comment by artun42** [comment]
Wanna share my experience. Had an issue where when main window is focused, it will skip almost all frames. But unfocusing and clicking to something else -- suddenly it works again. Also worked flawlessly in fullscreen. 

What was causing this is actually setting in Nvidia App - in System -> Displays -> G-Sync -> On (Full screen and **_windowed_**). Selecting full screen only fixed the issue for me.

**Comment by iiiGerardoiii** [comment]
It still happened on my mpv v0.41.0 running on Windows 11. Going on fullscreen made it stutter (I could easily notice by making circles with my cursor).

I fixed it by going to the NVIDIA Control Panel > Manage 3D Settings > Program Settings > add mpv.exe and then find "Monitor Technology" in the list settings and select "Fixed Refresh".

Hope this helps anyone having this same problem.
