### ISSUE TITLE
incorrect window scale factor after monitor hotplug on kde wayland 

### ISSUE THREAD

**Issue by microcai** [mpv-player/mpv#15361]
### mpv Information

```bash
mpv v0.39.0-335-g70aaba71d6 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 6.1.2
FFmpeg library versions:
   libavcodec      60.31.102
   libavdevice     60.3.100
   libavfilter     9.12.100
   libavformat     60.16.100
   libavutil       58.29.100
   libswresample   4.12.100
   libswscale      7.5.100
```

### Other Information

```text
- Linux version: Gentoo
- Kernel Version: 6.12
- GPU Model: [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] [1002:731f] (rev c1)
- Mesa/GPU Driver Version: 24.2.7
- Window Manager and Version: kwin 6.2.3
- Source of mpv: built from git master
- Latest known working version: never worked
- Issue started after the following happened:
```

### Reproduction Steps

1. make sure to use KDE wayland session
2. set screen scale to 200% on kde screen settings.
3. play video with "mpv --hidpi-window-scale=no"
4. turn-off monitor or plug out HDMI cable
5. turn-on monitor or plug in HDMI cable

### Expected Behavior

mpv still play video with no window scale

### Actual Behavior

mpv will scale window doubled size.

### Log File

[output.txt](https://github.com/user-attachments/files/17877981/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
This seems like a KDE bug, but can you provide the output of `WAYLAND_DEBUG=1 mpv [...]` just to be sure?

**Comment by microcai** [comment]
KDE will send  window scale = 100% and then window scale = 200% again after monitor hotplug.
so the code   
```
 if (wl->scaling == scale) 
    return; 
```
will ignore the windows scale update, thus kwin will assume mpv is not dpi-aware after monitor hotplug.

**Comment by Dudemanguy** [comment]
Does this work for you?

```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index fd1213693f..4aa57fa60c 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -1248,7 +1248,7 @@ static void preferred_scale(void *data,
                             uint32_t scale)
 {
     struct vo_wayland_state *wl = data;
-    if (wl->scaling == scale)
+    if (wl->scaling == scale && wl->rurrent_output)
         return;
 
     wl->pending_scaling = scale;
```

**Comment by microcai** [comment]
> Does this work for you?

no.  does not work.

**Comment by llyyr** [comment]
Please provide `WAYLAND_DEBUG=1` logs, the "fix" doesn't make any sense

**Comment by microcai** [comment]
[output_with_wayland_debug_equ_1.txt](https://github.com/user-attachments/files/17878728/output_with_wayland_debug_equ_1.txt)

**Comment by llyyr** [comment]
WAYLAND_DEBUG=1 output isn't captured by `--log-file`.

`WAYLAND_DEBUG=1 mpv [file] 2>| out.log`

**Comment by microcai** [comment]
[wayland_debug.txt](https://github.com/user-attachments/files/17878750/wayland_debug.txt)

**Comment by llyyr** [comment]
> [   0.117][v][vo/gpu-next/wayland] Surface entered output ASUSTek COMPUTER INC ROG XG27UQ/LCLMQS088426  (0x44), scale = 2.000000, refresh rate = 99.901000 Hz

> [   7.733][v][vo/gpu-next/wayland] Surface entered output ASUSTek COMPUTER INC ROG XG27UQ/LCLMQS088426  (0x46), scale = 1.000000, refresh rate = 99.901000 Hz


When the output is re-enabled, it comes back with a different id than before and this condition isn't satisfied.

https://github.com/mpv-player/mpv/blob/e2a23e08b879919f4d1ab8532de31d8acffe6d64/video/out/wayland_common.c#L909-L916

Should be fixed by https://github.com/mpv-player/mpv/pull/15365

**Comment by microcai** [comment]
no, it does not fix. I applied your patch, still got incorrect scale.

**Comment by llyyr** [comment]
This is actually just a Kwin bug, the output id shouldn't change. What I'm encountering is a different bug from what the issue reports.

**Comment by microcai** [comment]
the bug is not from kwin side, but really mpv's bug.

the root cause is remove_output() does not "forget" the scale_factor that "belongs" to the old output surface.
when the new output surface gets registered,  it's "scacle_factor" notify event gets ignored because it happens to be the same value as the old one.
and thus, mpv does not  "response" to scale change from kwin's point of view.
the kwin mark mpv output window as "not dpi-aware". then scales up in kwin side.

**Comment by Dudemanguy** [comment]
>no. does not work.

Did you apply it? I just tested it and it worked for me.
