### ISSUE TITLE
title bar on second monitor after exiting fullscreen

### ISSUE THREAD

**Issue by Kuro6804** [mpv-player/mpv#15592]
### mpv Information

```bash
mpv c566872 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Dec 28 2024 17:09:20
libplacebo version: v7.350.0
FFmpeg version: 2af7885
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Other Information

```text
- Windows version: 24H2
- GPU model, driver and version: RX 6800 XT, AMD Adrenaline, 24.12.1
- Source of mpv: https://nightly.link/mpv-player/mpv/workflows/build/master (windows-msvc)
- Latest known working version: not sure which exact version, but the previous build I used was from November I think
- Issue started after the following happened: after updating mpv
```

### Reproduction Steps

1. enter fullscreen
2. exit fullscreen

### Expected Behavior

mpv exits fullscreen and in regular maximised state

### Actual Behavior

video still covers the whole screen—as if fullscreen—and the title bar appears on second monitor above the primary monitor

![mpv_NUYb5KuBgB](https://github.com/user-attachments/assets/c2904448-a83a-4f34-93a1-876f3f08cec0)
(also tested it with taskbar in regular position, didn't change anything)

### Log File

[output.txt](https://github.com/user-attachments/files/18268929/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Barafu** [comment]
I have the same issue. It has nothing to do with 2 monitors. 
Basically, if the window is small, press F twice. The window goes to fullscreen, and back again. But if the window is maximised, it goes to fullscreen, but does not get back to maximised. Instead, it enters the state where the borders of the window are pushed outside the screen. 
It is a total showstopper. The simplest way to get out of the stuck state is to close the player.

**Comment by adisib** [comment]
> The simplest way to get out of the stuck state is to close the player.

You do not have to exit the player. Once you press "f" to leave fullscreen, you will be able to drag the window around with the mouse, so you can drag it down, grab the title bar, then move the title bar to the top of the screen to maximize it like how it is supposed to be. Still very annoying regardless though.

**Comment by kasper93** [comment]
I have a work in progress branch that refractors  the whole window resizing logic. This likely is fixed already.

**Comment by Barafu** [comment]
Just to ping that the problem is still here in the latest builds.

**Comment by dashelm** [comment]
I have the same issue. Unfortunately this is still not fixed.

**Comment by kasper93** [comment]
Please test with the current master version, if this is still an issue. Should be fixed by #16127

**Comment by dashelm** [comment]
Confirmed fixed!

**Comment by kasper93** [comment]
Fixed by: https://github.com/mpv-player/mpv/pull/16127
