### ISSUE TITLE
MPV hides mouse cursor on Mac Yosemite

### ISSUE THREAD

**Issue by xanview** [mpv-player/mpv#1651]
I'm trying to create this issue without a visible mouse cursor. CMD+Tab temporarily shows the mouse cursor but it vanishes a few seconds later. This shouldn't happen unless the active window is mpv.

I'm using mpv 0.8.2 on Mac Yosemite installed by Homebrew.

**Comment by Akemi** [comment]
i am guessing here, but if i understand your problem correctly try using [cursor-autohide-fs-only](http://mpv.io/manual/master/#options-cursor-autohide-fs-only). otherwise you might need to explain the problem a bit more detailed.

**Comment by hackeron** [comment]
yes, specifying cursor-autohide-fs-only gives the desired behaviour. But the bug is that the cursor should not be auto hidden unless mpv is the active window - what happens without cursor-autohide-fs-only is no matter what application I am using, my cursor disappears, even if mpv is not visible at all.

**Comment by KCAS** [comment]
i am on yosemite and i can't seem to reproduce what you are experiencing. i even set autohide to always and when i switch to another app, cursor stays visible until i switch back to mpv.

**Comment by wm4** [comment]
We're hiding the cursor with ``CGDisplayShowCursor()``. This looks pretty global, the Apple docs even say that it ignores its arguments.

Is there a more robust method we could use? On X11, we just set an empty icon when the cursor should be invisible, but I haven't found an API to change the cursor icon on OSX yet.

**Comment by pigoz** [comment]
It's global, afaik there's no better API on OSX. But what @hackeron describes doesn't seem to be reproducible.

**Comment by torque** [comment]
For what it's worth, I can reproduce this bug (sort of), but I assumed it was a bug with Yosemite, rather than mpv. I haven't done much checking to determine the source of the blame though.

In my case, I have a global hotkey set in iTerm2 to switch to it. When I use that hotkey instead of the system task switcher (cmd+tab) to switch from mpv to my terminal, the mouse disappears and will not reappear until I use cmd+tab, at which point it will goes back to working normally.

**Comment by Argon-** [comment]
Yes, I experienced this bug as well, but not only with mpv so I assume it's Yosemite specific.
You can get your cursor back with some alt+tab usage.

Essentially: what torque said.

**Comment by wm4** [comment]
Is it possible that Apple will fix it? I heard Apple usually doesn't fix bugs.

**Comment by pigoz** [comment]
They rarely do. Last time I reported a cocoa bug on radar (_with testcase_), they did not even reply.

**Comment by hackeron** [comment]
It seems to be intermittent - right now I cannot reproduce this bug, but last night, the mouse cursor kept disappearing constantly and consistently every time mpv was running, no matter what application I was using.

The cursor re-repeared only when I closed mpv or used cursor-autohide-fs-only. Maybe cursor-autohide-fs-only can be a default on OS X?

**Comment by Nyx0uf** [comment]
Yes it is a 10.10 bug.

But knowing Apple, I wouldn't expect a fix in a 10.10.x branch… You can still try to fill a radar, but as pigoz said they will likely not answer…

**Comment by hackeron** [comment]
Baring this in mind maybe the default behaviour on OS X should be to only hide the cursor in full screen to avoid frustrating users? - I myself temporarily switched back to mplayer until I was aware I can change this behaviour :)

**Comment by wzxu** [comment]
Just FYI, Movist from the App Store handles this flawlessly. It also seeks almost instantaneously wherever I click on the timeline (even on an older machine).

Too bad it's not open sourced. Just saying that there is definitely room for improvement.

If not fixable, I agree that cursor-autohide-fs-only should be default behavior on OS X.

**Comment by wzxu** [comment]
[Did a short screen recording to showcase the behavioral differences.](http://cl.ly/a5cT)

**Comment by pigoz** [comment]
@wzxu: Well that definitely looks like a bug in mpv and I will fix it. It also seems to be easily reproducible.

**Comment by torque** [comment]
Question for anyone who can reproduce this issue: do you have the option "Use scroll gesture with modifier keys to zoom" enabled in System Preferences > Accessibility > Zoom? If I disable that option, I can no longer reproduce it.

**Comment by asoksevil** [comment]
I can reproduce this issue as well on Mavericks 10.9.5. Funny because I was about to post this bug and I found it there.

I do not have that accessibility option enabled either.

**Comment by pigoz** [comment]
@wzxu: the issue in your screencast is fixed with ce239f157

Can someone who can reproduce the main issue in this thread test torque's patch? (d7201a0)

**Comment by asoksevil** [comment]
I have just tested it and it seems to be working no, no more hiding cursor when mpv is open.

**Comment by asoksevil** [comment]
Update. It is "partially fixed", cursor stays even on full screen.

**Comment by asoksevil** [comment]
Fixed.

**Comment by pigoz** [comment]
533e151febe798e might fix this issue. Can anyone test mpv master?

**Comment by Akemi** [comment]
it seems fixed. i can't reproduce this anymore. if anyone still has this issue just drop a comment and i will reopen it.
