### ISSUE TITLE
Commit ce076de by default causes MESA: warning: Not using HDR metadata to avoid protocol errors

### ISSUE THREAD

**Issue by pinkflames** [mpv-player/mpv#16543]
### mpv Information

```bash
mpv v0.40.0-185-gbd2118026 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.351.0
FFmpeg version: 7.1.1
FFmpeg library versions:
   libavcodec      61.19.101
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Other Information

```text
- Linux version:
  NAME=Gentoo
  PRETTY_NAME="Gentoo Linux"
- Kernel Version:
  Linux redacted 6.16.0-rc6 #755 SMP PREEMPT Mon Jul 14 redacted 2025 x86_64 12th Gen Intel(R) Core(TM) i5-12400 GenuineIntel GNU/Linux
- GPU Model:
  00:02.0 VGA compatible controller [0300]: Intel Corporation Alder Lake-S GT1 [UHD Graphics 730] [8086:4682] (rev 0c)
  01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev e7)
- Mesa/GPU Driver Version:
  OpenGL version string: 4.6 (Compatibility Profile) Mesa 25.2.0-devel (git-36172c41dc) [I'm actually using Vulkan 1.4.313.0 but don't have vulkaninfo installed]
- Window Manager and Version:
  kwin_wayland 6.4.2 with HDR enabled
- Source of mpv:
  Gentoo stock live ebuild (media-video/mpv-9999::gentoo)
- Latest known working version:
  Commit 5b1df3c5d900298e433539c99e8e5ea60acfa068 [triple checked for good measure]
- Issue started after the following happened:
  After latest rebuild of the mpv from git a new Mesa warning popped up. It had been days since I last used mpv and at first suspected a Mesa change but thankfully it wasn't too hard to find the suspect range of mpv commits and manually bisect them.
```

### Reproduction Steps

With current git master and my SW/HW combo even `mpv --config=no <Literally any video including SDR>` prints `MESA: warning: Not using HDR metadata to avoid protocol errors` between the VO and AV lines.

Upon further testing, it seems that that warning is only printed with the new default --target-colorspace-hint-mode=target but not when it's set to source or source-dynamic.

For what it's worth, the verbose output places that line here:
```
[vo/gpu-next/libplacebo] Picked surface configuration 71: VK_FORMAT_R16G16B16A16_UNORM + VK_COLOR_SPACE_HDR10_ST2084_EXT
[vo/gpu-next/libplacebo] Spent 145.414 ms translating SPIR-V (slow!)
[vo/gpu-next/libplacebo] Spent 14.415 ms translating SPIR-V
MESA: warning: Not using HDR metadata to avoid protocol errors
[cplayer] first video frame after restart shown
```
but I have no idea, how much one can trust the ordering here.

### Expected Behavior

Not having that warning. ;)

### Actual Behavior

Ugh... I'm a bit confused what exactly is going on but it would seem that git master by default has broken HDR on Linux now, since while it looks HDR-ish, the colors are just slightly washed out. The fix or work-around is to set --target-colorspace-hint-mode=source|source-dynamic that has correct looking colors. Except those two don't **feel** like HDR but rather like well mapped HDR to SDR... (but of course the display is still in HDR mode and mpv does for all 3 of possible values report use of BT.2020 and PQ).

In short, I have no idea what the actual behavior is, sorry.

### Log File

[output.txt](https://github.com/user-attachments/files/21212738/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [x] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [x] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [x] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
> mpv --config=no <Literally any video including SDR>

Are you sure it's literally any video? The error comes from Mesa's WSI layer when mpv submits HDR metadata that's illegal by the color-management-v1 protocol. However, mpv just submits the metadata present on the file, so it really should be specific to the file you're trying to play

Could you share a sample file?

**Comment by kasper93** [comment]
> MESA: warning: Not using HDR metadata to avoid protocol errors

This happens because mesa rejects our metadata. The check was added is [mesa@cb7726bb2c](https://gitlab.freedesktop.org/mesa/mesa/-/commit/cb7726bb2cf7e25661c1401dbef2a6a597748ecd) following the Wayland protocol wording [color-management-v1.xml#L1015-1022](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/efbc060534be948b63e1f395d69b583eebba3235/staging/color-management/color-management-v1.xml#L1015-1022) added by [wayland-protocols@e14bb785c](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/commit/e14bb785c0310911929d04df4e072e10d1f8ead3)

```
        The protocol error invalid_luminance is raised if any of the following
        requirements is not met:
        - When max_cll is set, it must be greater than min L and less or equal
          to max L of the mastering luminance range.
        - When max_fall is set, it must be greater than min L and less or equal
          to max L of the mastering luminance range.
        - When both max_cll and max_fall are set, max_fall must be less or equal
          to max_cll.
```

I checked H.265 and CTA-861-H, there is nothing that would require `max_cll` and `max_fall` to be within mastering luminance range.

Now what happens in your case is that we use target display mastering luminance and source max_cll/max_fall values if they were not provided for the target display. Arguably this could be changed, but this doesn't change the fact the `source` mode is just as affected, because there is nothing that requires real HDR movies metadata to follow this Wayland restriction. 

And sure enough, I've checked few movies, both new and more recent ones. I can every easily found.

```
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 9918 cd/m2
Maximum Frame-Average Light Level        : 3241 cd/m2
```

```
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1008 cd/m2
Maximum Frame-Average Light Level        : 186 cd/m2
```

Or some HDR demos, with even more insane values
```
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0099 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 10000
Maximum Frame-Average Light Level        : 300
```

Now, all this metadata is rejected by Wayland, so I'm not sure what to do here. Should mpv clamp content metadata?

**Comment by mahkoh** [comment]
>Now what happens in your case is that we use target display mastering luminance and source max_cll/max_fall values if they were not provided for the target display.

Isn't the point of `target` that libplacebo should do tone and gamut mapping to the target display? Is it ever correct to use any of the source values afterwards?

**Comment by kasper93** [comment]
> > Now what happens in your case is that we use target display mastering luminance and source max_cll/max_fall values if they were not provided for the target display.
> 
> Isn't the point of `target` that libplacebo should do tone and gamut mapping to the target display? Is it ever correct to use any of the source values afterwards?

Yes, our current logic is lacking a bit. The point here is when we don't have target metadata at all or they are incomplete it's better to default to content range, instead of going full 10000 nits, bt.2020 gamut, which no display support anyway, so we just fallback to source. I will think about it, likely luminance values should be treated as a package. Not sure about primaries. We send this metadata to display so sending too wide metedata could make it do something to the image that we don't want. (my display is adjusting based on sent primaries). I will think about it. Same for the clamp of CLL, which we will have to do now, hmm.

**Comment by pinkflames** [comment]
This is all beyond me, therefore please excuse my ignorance, but can you even send HDR metadata to the display, when Wayland is being used? I'd have though that doing so would be limited to **vo_drm** or perhaps `--gpu-context=displayvk` et al. If so, then shouldn't the Wayland default be `--target-colorspace-hint-mode=source` anyway?

**Comment by llyyr** [comment]
> can you even send HDR metadata to the display, when Wayland is being used?

Yes, but in this case mpv sets the metadata on the Vulkan swapchain and then Mesa uses the color management protocol to set it.

**Comment by Dudemanguy** [comment]
Well there's a couple of things here. As discussed already, the message from Mesa is normal and unfortunately is just a side of effect of how the wayland protocol is defined. I'm hopeful we can [change Mesa](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/36129) to be more generous with HDR metadata.

That said, this shouldn't happen for literally every file. SDR should not be sending metadata of course and not every HDR file should hit that Mesa behavior (although many will).

**Comment by pinkflames** [comment]
However, I think it's just due to my SW/HW combo that everything triggers it, since my kwin_wayland has HDR brightness calibrated to 394 peak and 204 SDR white (presumably both are in nits and correspond to the max_cll and perhaps max_fall?). Overall screens like that are quite common, just perhaps not set to 394 peak, since 395 is the point at which the KWin HDR peak brightness test suddenly goes all white as if the display firmware is pulling some shenanigans when peak is set to >394.

And sure enough setting peak brightness to 409 in KWin's HDR brightness calibration (which results in all white test image) makes that MESA warning go away. The colors with --target-colorspace-hint-mode=target still might be a bit undersaturated but not really that noticeable.

P.S. I forgot to mention that SDR vidoes end up with `Primaries: display-p3` reported in the OSD, which might be why SDR videos also get that HDR related warning.

**Comment by Dudemanguy** [comment]
> I forgot to mention that SDR vidoes end up with Primaries: display-p3 reported in the OSD, which might be why SDR videos also get that HDR related warning.

Hmm that must mean that KWin reports that the preferred colorspace is display p3 since 39c9d1acb498b9ea5db2bd862cb0411c96979e14. That wouldn't be my expectation. Perhaps we shouldn't just blindly use that?

**Comment by kasper93** [comment]
> > I forgot to mention that SDR vidoes end up with Primaries: display-p3 reported in the OSD, which might be why SDR videos also get that HDR related warning.
> 
> Hmm that must mean that KWin reports that the preferred colorspace is display p3 since [39c9d1a](https://github.com/mpv-player/mpv/commit/39c9d1acb498b9ea5db2bd862cb0411c96979e14). That wouldn't be my expectation. Perhaps we shouldn't just blindly use that?

If the compositor wants display-p3, I think it's fine to comply. In theory it means that composition and display output is in p3 colorspace and we do this conversion.

**Comment by pinkflames** [comment]
I don't know how to check, what the actual screen configuration is but the display manufacturer's technical specification says something like [up to] 99% DCI-P3 coverage, so Display P3 might be about right in terms of primaries. The display OSD merely states that it's in HDR mode but does not specify if that's BT.2020 or some P3 variant.

I guess you'd want to match what's being sent to the screen, to avoid going BT.709 -> Display-P3 -> BT.2020 even if BT.2020 was limited to DCI-P3 primaries? I'm not sure, if this is helpful, but here's what's being sent to the display according to dmesg (most likely when turning the display back on after having suspended it during idle):

[edited for brevity, since, I think, it's just repeating these two lines like 4 times..]
> HDR SB:01 1a 02 00 00 7d 74 40 98 3a 30 75 4c 1d b8 0b
> HDR SB:13 3d 42 40 99 01 53 0f 99 01 99 01 00 00 00 00

**Comment by pinkflames** [comment]
Hey, I noticed this bug is still open but is there anything left to do here? As a non-expert I feel like the current HDR experience with bleeding edge software is pretty decent, so maybe this is now resolved upstream?

**Comment by serhii-nakon** [comment]
I seems have the same warning - how even check whether HDR properly works or not?

**Comment by llyyr** [comment]
If the warning is visible then the metadata isn't being used. This is a Mesa bug, it needs to be updated to use the version 2 of the color-management-v1 protocol, which has the restriction more relaxed.

mpv and libplacebo master (in combination) also workaround this bug by not using the WSI layer at all.

**Comment by pinkflames** [comment]
tl;dr: that warning message as well as, I think, the underlying issue should have been fixed. If you're seeing it, you should consider using newer software without old bugs. 😉 

I don't think there's a good way of checking other than doing color calibration to see how much of the actual DCI-P3 or BT.2020 you're getting when playing back HDR content. That being said, like in most cases in life, if it looks right to your eyes, it's probably alright.

Also HDR is not really a thing outside of video games. Real world content is at best DCI-P3 and even that is not easy to find. For example, here's a [YouTube test video](https://www.youtube.com/watch?v=LxnMg0I0LZM) that, when set to one of the higher resolutions with HDR tag, looks right with Firefox 155 and `gfx.color_management.hdr=true` set in about:config. Whether it's truly HDR, I have no way of proving beyond the fact that the entire stack from YouTube player to the display is reporting HDR and wide gamut in use.

I'm just a fool but my best guess for great HDR experience on Linux is that you need to be using the latest kwin_wayland such as 6.7.4 with a very recent Linux kernel such as 7.2.3 and absolutely latest Mesa such as 26.2.1. It's possible that Mac OS X with M series chips are also good but I have zero experience with those. Everything else is probably in various states of awful but might still be passable with enough config tweaking and adjustments. 

For example, wlroots 0.20 based compositors when using Vulkan such as Sway 1.12 can get the my display to switch to the HDR mode but they're reporting crazy high MaxCLL (and FALL) values to applications and, I bet, are lacking tone mapping on their part, so there's no automatic way to get HDR content to actually look right. It might be possible to tweak mpv.conf enough to work around all those issues but personally I know better than to polish t...

**Comment by llyyr** [comment]
> tl;dr: that warning message as well as, I think, the underlying issue should have been fixed. If you're seeing it, you should consider using newer software without old bugs. 😉

There's no new software without this "bug", unless as I suggested, you use an unreleased version of mpv and libplacebo.

> absolutely latest Mesa such as 26.2.1.

The "bug" isn't fixed on Mesa main, and there are no open MRs to do this. So I don't know what this suggestion has to do with anything. Same for kernel, it doesn't interact with anything here in any way.

Compositor version may be relevant, but only to ensure support for v2 of the protocol

**Comment by pinkflames** [comment]
Hang on, what part is not fixed yet? As far as I can tell/remember, patches relevant to this went into various places of the open source stack a good while back. Just because the merge requests linked here was closed, does not mean code hasn't changed in response.

I answered in the general sense, for example, my RX-580 will not have correct HDR output in kernels older than some weeks ago. My point being that HDR is still a fresh field in Linux and it benefits a lot to not be running software from months ago, let alone years.

And, yes, I skipped the part where I have custom patched builds of pre-release mesa, libdrm, libplacebo, kwin_wayland, etc, because that's rather irrelevant and will become standard bleeding edge software in just a month or two.

I also skipped many other custom tweaks, since hopefully people don't need to go nano on kwin config files to get great HDR experience. 😉

**Comment by llyyr** [comment]
> Hang on, what part is not fixed yet? As far as I can tell/remember, patches relevant to this went into various places of the open source stack a good while back. Just because the merge requests linked here was closed, does not mean code hasn't changed in response.

The code is indeed unchanged, because changing it would require supporting version 2 of the protocol in Mesa. Which would in turn require supporting power22 transfer function for the Vulkan WSI, for which there isn't a good way to do so.

The Mesa issue likely won't be fixed for a while, maybe months or years. mpv (master, not v0.41) is currently sidestepping this by not using WSI code at all.

I made an effort to do so a while back, but was told that Khronos are working on it internally so please trust that I know what I'm talking about. https://github.com/KhronosGroup/Vulkan-Docs/pull/2649
