### ISSUE TITLE
vavpp bob deinterlace always uses top field

### ISSUE THREAD

**Issue by zekica** [mpv-player/mpv#1668]
I have tested the vavpp filter for deinterlacing video, and after debugging I have concluded that the deinterlacer is using the top field twice. The result of this is that there are two identical deinterlaced frames in the output queue for each source frame (top and bottom fields).

I have also tested KODI and there bob deinterlacing works as expected. After comparing the code, I have found that there is one difference: They are also setting VAProcFilterParameterBufferDeinterlacing to VA_DEINTERLACING_BOTTOM_FIELD if the bottom field is requested.

So I have added the code in video/filter/vf_vavpp.c in render() below the lines:
        status = vaMapBuffer(p->display, buffer, (void**)&param);
        if (!check_error(vf, status, "vaMapBuffer()"))
            break;

that does:
        VAProcFilterParameterBufferDeinterlacing *filter_params;
        status = vaMapBuffer(p->display, *(p->pipe.filters), (void**)&filter_params);
        if (!check_error(vf, status, "vaMapBuffer()"))
            break;
        filter_params->flags = flags & VA_TOP_FIELD ? 0 : VA_DEINTERLACING_BOTTOM_FIELD;
        vaUnmapBuffer(p->display, *(p->pipe.filters));

After compiling the code I have confirmed that on (at least top_first) interlaced video everything works as expected with bob deinterlacing.

I have tested with libva 1.4.0 for now on Haswell HD 4600 but I can also test on Haswell HD 4400, Ivy Bridge HD 2500, Ivy Bridge HD 4000 and on Sandy Bridge HD 2000 if needed.

Can you review the code and include it if you don't see any potential problems.

**Comment by wm4** [comment]
Thanks. Can you submit a PR?

**Comment by wm4** [comment]
PS: ``git format-patch`` is also ok.

**Comment by zekica** [comment]
Ok, here is git format-patch: https://www.dropbox.com/s/qwk84bxph1wamfu/0001-Add-filter-parameters-to-VAAPI-deinterlacing-filter-.patch?dl=1

**Comment by wm4** [comment]
Adjusted the commit message and pushed. Thanks a lot.

**Comment by wm4** [comment]
Now I actually have the hardware to test. And bob deinterlacing seems to be broken. Does it work for you? (I tested with the lavfi ``telecine`` filter.)

**Comment by zekica** [comment]
It works for me in haswell hd4600 and hd4400 desktop, ivy bridge gt1
(celeron 1037u) and sandy bridge gt1 (celeron 847) although in the last
case it doesn't handle 1080i60 (it lags).

I'll test the latest git version tomorrow.

**Comment by Gusar321** [comment]
Bob deinterlacing works here with top field first video. It doesn't with bottom field first. A very nice sample to test deinterlacing is in mplayer's collection, it's bottom field first: http://samples.mplayerhq.hu/MPEG2/interlaced/burosch1.mpg

**Comment by zekica** [comment]
Ok, I'll try it tomorrow and probably make another parch.

**Comment by zekica** [comment]
I have fixed the problem with de-interlacing bottom-first videos. Here is the git-format patch:
https://www.dropbox.com/s/musvp05mk2pzcm4/0001-Fix-vavpp-bob-deinterlacing-for-bottom-field-first-v.patch?dl=1

**Comment by wm4** [comment]
Thanks, applied.

**Comment by wm4** [comment]
I've tried making the "extended" deinterlacing modes work. I've added support for provide reference frames (the deinterlacers want 1 future frame), but it still doesn't seem to work. The driver doesn't complain anymore, but the output doesn't make sense. Not sure what's wrong with it.

**Comment by Gusar321** [comment]
Which GPU do you have, also which version of libva-intel-driver? Advanced deinterlacers for Sandy Bridge and Ivy Bridge will only work with the git version of libva-intel-driver. Haswell should work already, probably Broadwell too. I will test on Haswell later today.

**Comment by zekica** [comment]
I have Haswell HD4600 (GT2) on i3-4330, Haswell HD (HT1) on Celeron G1840, Ivy Bridge GT2 (HD 4000) on i5-3210M, Ivy Bridge HD (GT1) on Celeron 1037u, and Sandy Bridge HD (GT1) on Celeron 847.

I haven't installed latest git versions. I have VA-API version: 0.37 (libva 1.5.0). I can install the git versions for testing.

**Comment by wm4** [comment]
I have:
```
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.37 (libva 1.5.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Broadwell - 1.5.1
```
Anyway, the driver doesn't refuse to use these deinterlacers. Just the frame order or so we make it output makes no sense. Surely just a problem on mpv's side,
