### ISSUE TITLE
Video is garbled, audio plays fine in some files

### ISSUE THREAD

**Issue by ainstushar** [mpv-player/mpv#1670]
Hi there, mpv fails to play some files properly. Audio plays just fine, but the video is garbled (see screenshot). The same file plays fine in movist. The file has the same issue playing in other players like vlc, mplayerx... Obviously the file is somehow damaged/corrupted, but I was wondering why movist was able to play the file and would it be possible for mpv to play it correctly?

Verbose log of playback:

````
[cplayer] Command line options: '-v' '/Users/Borat/Downloads/totally legit file.mkv'
[cplayer] mpv git-90adf29 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on 2015-03-09T22:35:49
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.15.100
[cplayer]    libavcodec      56.13.100
[cplayer]    libavformat     56.15.102
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.2.103
[cplayer]    libswresample   1.1.100
[cplayer] 
[cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv/HEAD --enable-zsh-comp
[cplayer] config.h:
[cplayer] 
[cplayer] #define DEFAULT_DVD_DEVICE "/dev/rdiskN"
[cplayer] #define DEFAULT_CDROM_DEVICE "/dev/disk1"
[cplayer] #define HAVE_CPLAYER 1
[cplayer] #define HAVE_LIBMPV_SHARED 0
[cplayer] #define HAVE_LIBMPV_STATIC 0
[cplayer] #define HAVE_STATIC_BUILD 0
[cplayer] #define HAVE_BUILD_DATE 1
[cplayer] #define HAVE_OPTIMIZE 1
[cplayer] #define HAVE_DEBUG_BUILD 1
[cplayer] #define HAVE_PDF_BUILD 0
[cplayer] #define HAVE_LIBDL 1
[cplayer] #define HAVE_DLOPEN 1
[cplayer] #define HAVE_VF_DLOPEN_FILTERS 0
[cplayer] #define HAVE_ZSH_COMP 1
[cplayer] #define HAVE_ASM 1
[cplayer] #define HAVE_TEST 0
[cplayer] #define HAVE_CLANG_DATABASE 0
[cplayer] #define HAVE_NOEXECSTACK 0
[cplayer] #define HAVE_LIBM 1
[cplayer] #define HAVE_MINGW 0
[cplayer] #define HAVE_POSIX 1
[cplayer] #define HAVE_POSIX_OR_MINGW 1
[cplayer] #define HAVE_WIN32_INTERNAL_PTHREADS 0
[cplayer] #define HAVE_PTHREADS 1
[cplayer] #define HAVE_STDATOMIC 0
[cplayer] #define HAVE_ATOMIC_BUILTINS 1
[cplayer] #define HAVE_SYNC_BUILTINS 0
[cplayer] #define HAVE_ATOMICS 1
[cplayer] #define HAVE_LIBRT 0
[cplayer] #define HAVE_ICONV 1
[cplayer] #define HAVE_DOS_PATHS 0
[cplayer] #define HAVE_WAIO 0
[cplayer] #define HAVE_TERMIOS_H 1
[cplayer] #define HAVE_SYS_TERMIOS_H 0
[cplayer] #define HAVE_TERMIOS 1
[cplayer] #define HAVE_SHM 1
[cplayer] #define HAVE_NANOSLEEP 1
[cplayer] #define HAVE_POSIX_SPAWN 1
[cplayer] #define HAVE_GLOB 1
[cplayer] #define HAVE_GLOB_WIN32_REPLACEMENT 0
[cplayer] #define HAVE_FCHMOD 1
[cplayer] #define HAVE_GLIBC_THREAD_NAME 0
[cplayer] #define HAVE_OSX_THREAD_NAME 1
[cplayer] #define HAVE_BSD_THREAD_NAME 0
[cplayer] #define HAVE_NETBSD_THREAD_NAME 0
[cplayer] #define HAVE_BSD_FSTATFS 1
[cplayer] #define HAVE_LINUX_FSTATFS 0
[cplayer] #define HAVE_LIBGUESS 0
[cplayer] #define HAVE_LIBSMBCLIENT 0
[cplayer] #define HAVE_LUA 1
[cplayer] #define HAVE_LIBASS 1
[cplayer] #define HAVE_LIBASS_OSD 1
[cplayer] #define HAVE_DUMMY_OSD 0
[cplayer] #define HAVE_ZLIB 1
[cplayer] #define HAVE_ENCODING 1
[cplayer] #define HAVE_JOYSTICK 0
[cplayer] #define HAVE_LIRC 0
[cplayer] #define HAVE_LIBBLURAY 1
[cplayer] #define HAVE_DVDREAD 1
[cplayer] #define HAVE_DVDNAV 0
[cplayer] #define HAVE_CDDA 0
[cplayer] #define HAVE_ENCA 0
[cplayer] #define HAVE_MPG123 1
[cplayer] #define HAVE_LADSPA 0
[cplayer] #define HAVE_RUBBERBAND 0
[cplayer] #define HAVE_LIBBS2B 0
[cplayer] #define HAVE_LCMS2 1
[cplayer] #define HAVE_VAPOURSYNTH_CORE 0
[cplayer] #define HAVE_VAPOURSYNTH 0
[cplayer] #define HAVE_VAPOURSYNTH_LAZY 0
[cplayer] #define HAVE_SDL2 0
[cplayer] #define HAVE_SDL1 0
[cplayer] #define HAVE_OSS_AUDIO_4FRONT 0
[cplayer] #define HAVE_OSS_AUDIO_NATIVE 0
[cplayer] #define HAVE_OSS_AUDIO_SUNAUDIO 0
[cplayer] #define HAVE_OSS_AUDIO 0
[cplayer] #define HAVE_RSOUND 0
[cplayer] #define HAVE_SNDIO 0
[cplayer] #define HAVE_PULSE 0
[cplayer] #define HAVE_JACK 0
[cplayer] #define HAVE_OPENAL 0
[cplayer] #define HAVE_ALSA 0
[cplayer] #define HAVE_COREAUDIO 1
[cplayer] #define HAVE_DSOUND 0
[cplayer] #define HAVE_WASAPI 0
[cplayer] #define HAVE_COCOA 1
[cplayer] #define HAVE_GDI 0
[cplayer] #define HAVE_WINMM 0
[cplayer] #define HAVE_OLE 0
[cplayer] #define HAVE_UUID 0
[cplayer] #define HAVE_WAYLAND 0
[cplayer] #define HAVE_X11 1
[cplayer] #define HAVE_XSS 1
[cplayer] #define HAVE_XEXT 1
[cplayer] #define HAVE_XV 1
[cplayer] #define HAVE_XINERAMA 1
[cplayer] #define HAVE_XRANDR 1
[cplayer] #define HAVE_GL_COCOA 1
[cplayer] #define HAVE_GL_X11 1
[cplayer] #define HAVE_EGL_X11 0
[cplayer] #define HAVE_GL_WAYLAND 0
[cplayer] #define HAVE_GL_WIN32 0
[cplayer] #define HAVE_GL 1
[cplayer] #define HAVE_VDPAU 0
[cplayer] #define HAVE_VDPAU_GL_X11 0
[cplayer] #define HAVE_VAAPI 0
[cplayer] #define HAVE_VAAPI_VPP 0
[cplayer] #define HAVE_VAAPI_GLX 0
[cplayer] #define HAVE_CACA 0
[cplayer] #define HAVE_JPEG 1
[cplayer] #define HAVE_DIRECT3D 0
[cplayer] #define HAVE_LIBAV 1
[cplayer] #define HAVE_LIBSWRESAMPLE 1
[cplayer] #define HAVE_LIBAVRESAMPLE 0
[cplayer] #define HAVE_RESAMPLER 1
[cplayer] #define HAVE_LIBAVFILTER 1
[cplayer] #define HAVE_LIBAVDEVICE 1
[cplayer] #define HAVE_AVCODEC_CHROMA_POS_API 1
[cplayer] #define HAVE_AVFRAME_METADATA 1
[cplayer] #define HAVE_AVFRAME_SKIP_SAMPLES 1
[cplayer] #define HAVE_VAAPI_HWACCEL 0
[cplayer] #define HAVE_VIDEODECODEACCELERATION_VDADECODER_H 1
[cplayer] #define HAVE_VDA_HWACCEL 1
[cplayer] #define HAVE_VDA_GL 1
[cplayer] #define HAVE_VDPAU_HWACCEL 0
[cplayer] #define HAVE_DXVA2_HWACCEL 0
[cplayer] #define HAVE_TV 1
[cplayer] #define HAVE_SYS_VIDEOIO_H 0
[cplayer] #define HAVE_VIDEODEV 0
[cplayer] #define HAVE_TV_V4L2 0
[cplayer] #define HAVE_LIBV4L2 0
[cplayer] #define HAVE_PVR 0
[cplayer] #define HAVE_AUDIO_INPUT 0
[cplayer] #define HAVE_DVBIN 0
[cplayer] #define HAVE_WIN32_EXECUTABLE 0
[cplayer] #define HAVE_COCOA_APPLICATION 1
[cplayer] #define HAVE_APPLE_REMOTE 1
[cplayer] #define HAVE_SYS_SOUNDCARD_H (HAVE_OSS_AUDIO_NATIVE || HAVE_OSS_AUDIO_4FRONT)
[cplayer] #define HAVE_SOUNDCARD_H HAVE_OSS_AUDIO_SUNAUDIO
[cplayer] #define CONFIGURATION "waf configure --prefix=/usr/local/Cellar/mpv/HEAD --enable-zsh-comp"
[cplayer] #define MPV_CONFDIR "/usr/local/Cellar/mpv/HEAD/etc/mpv"
[cplayer] 
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'encoding-profiles.conf' -> '/usr/local/Cellar/mpv/HEAD/etc/mpv/encoding-profiles.conf'
[cplayer] Reading config file /usr/local/Cellar/mpv/HEAD/etc/mpv/encoding-profiles.conf
[cplayer] 
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'mpv.conf|config'
[global]     -> '/Users/Borat/.mpv/config'
[cplayer] Reading config file /Users/Borat/.mpv/config
[cplayer] 
[cplayer] Setting option 'autofit-larger' = '100%x100%' (flags = 4)
[cplayer] Setting option 'hwdec' = 'vda' (flags = 4)
[cplayer] Setting option 'sub-text-font' = 'WenQuanYi Micro Hei' (flags = 4)
[cplayer] Setting option 'osd-font' = 'WenQuanYi Micro Hei' (flags = 4)
[cplayer] Setting option 'sub-text-font-size' = '20' (flags = 4)
[cplayer] Setting option 'sub-use-margins' = '' (flags = 4)
[cplayer] Setting option 'sub-pos' = '98' (flags = 4)
[cplayer] Setting option 'volume' = '100' (flags = 4)
[cplayer] Setting option 'keep-open' = '' (flags = 4)
[cplayer] Setting option 'screenshot-template' = '~/Desktop/mpv_screenshot_%n' (flags = 4)
[cplayer] Setting option 'af' = 'scaletempo' (flags = 4)
[cplayer] Setting option 'sub-scale' = '0.7' (flags = 4)
[cplayer] Setting option 'no-border' = '' (flags = 4)
[cplayer] Setting option 'contrast' = '3' (flags = 4)
[cplayer] Setting option 'brightness' = '3' (flags = 4)
[cplayer] Setting option 'gamma' = '3' (flags = 4)
[cplayer] Setting option 'saturation' = '5' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'input.conf'
[global]     -> '/Users/Borat/.mpv/input.conf'
[global] user path: '/Users/Borat/.mpv/input.conf' -> '/Users/Borat/.mpv/input.conf'
[file] Opened: /Users/Borat/.mpv/input.conf
[input] Parsing input config file /Users/Borat/.mpv/input.conf
[input] Input config file /Users/Borat/.mpv/input.conf parsed: 9 binds
[osc] Loading script @osc.lua...
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'scripts'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'lua'
[global]     -> '/usr/local/bin/lua'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'lua-settings/osc.conf' -> '/Users/Borat/.mpv/lua-settings/osc.conf'
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'scripts'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'lua'
[global]     -> '/usr/local/bin/lua'
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook_add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'scripts'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config file: 'lua'
[global]     -> '/usr/local/bin/lua'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'watch_later/7D6A8CFC1D6535A5B303787E143CBD46' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'watch_later' -> '/Users/Borat/.mpv/watch_later'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'watch_later/7D6A8CFC1D6535A5B303787E143CBD46' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'watch_later' -> '/Users/Borat/.mpv/watch_later'
[cplayer] Playing: /Users/Borat/Downloads/totally legit file.mkv
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook_ack, flags=0, args=[on_load]
[file] Opened: /Users/Borat/Downloads/totally legit file.mkv
[demux] Trying demuxer: disc (force-level: normal)
[demux] Trying demuxer: edl (force-level: normal)
[demux] Trying demuxer: cue (force-level: normal)
[demux] Trying demuxer: rawaudio (force-level: normal)
[demux] Trying demuxer: rawvideo (force-level: normal)
[demux] Trying demuxer: tv (force-level: normal)
[demux] Trying demuxer: libass (force-level: normal)
[demux] Trying demuxer: mkv (force-level: normal)
[mkv] Found the head...
[mkv] + a segment...
[mkv] /---- [ parsing seek head ] ---------
[mkv] \---- [ parsing seek head ] ---------
[mkv] |+ segment information...
[mkv] | + timecode scale: 1000000
[mkv] | + duration: 1524.932s
[mkv] | + segment uid c8 ba 5e b1 a9 3b be 6e e3 14 4b 70 d2 68 39 69
[mkv] |+ segment tracks...
[mkv] | + a track...
[mkv] |  + Track number: 1
[mkv] |  + Track type: Video
[mkv] |  + Video track
[mkv] |   + Display width: 1280
[mkv] |   + Display height: 720
[mkv] |   + Pixel width: 1280
[mkv] |   + Pixel height: 720
[mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[mkv] |  + CodecPrivate, length 39
[mkv] |  + Language: und
[mkv] |  + Default flag: 0
[mkv] |  + Default duration: 41.708ms ( = 23.976 fps)
[mkv] | + a track...
[mkv] |  + Track number: 2
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 48000.000000
[mkv] |   + Channels: 2
[mkv] |  + Codec ID: A_AC3
[mkv] |  + Language: ???
[mkv] |  + Default flag: 1
[mkv] |+ found cluster
[mkv] Deferring reading cues.
[mkv] Seeking to 682594531 to read header element 0x114d9b74.
[mkv] /---- [ parsing seek head ] ---------
[mkv] \---- [ parsing seek head ] ---------
[mkv] All headers are parsed!
[mkv] Aspect: 1.777778
[demux] Detected file format: Matroska
[find_files] Loading external files in /Users/Borat/Downloads/
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'sub/' -> '(NULL)'
[cplayer]  (+) Video --vid=1 (h264)
[cplayer]  (+) Audio --aid=1 --alang=??? (*) (ac3)
[cplayer] [V] fourcc:0x31637661  size:1280x720  fps:23.976
[vo/opengl] GL_VERSION='4.1 NVIDIA-10.2.1 310.41.15f01'
[vo/opengl] Detected desktop OpenGL 4.1.
[vo/opengl] GL_VENDOR='NVIDIA Corporation'
[vo/opengl] GL_RENDERER='NVIDIA GeForce GT 750M OpenGL Engine'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='4.10'
[vo/opengl] Detected OpenGL features:
[vo/opengl]   - Framebuffers
[vo/opengl]   - VAOs
[vo/opengl]   - Float textures
[vo/opengl]   - RG textures
[vo/opengl]   - 1st class shader arrays
[vo/opengl]   - 1D textures
[vo/opengl]   - 3D textures
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Display depth: R=8, G=8, B=8
[vo/opengl] Reinit rendering.
[vo/opengl] Resize: 0x0
[vo/opengl] Assuming 59.990267 FPS for framedrop.
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     lavc:h264_vda (h264) - H.264 (VDA acceleration)
[vd] Opening video decoder lavc:h264
[vd] Trying to use hardware decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[ad] Codec list:
[ad]     lavc:ac3 - ATSC A/52A (AC-3)
[ad]     lavc:ac3_fixed (ac3) - ATSC A/52A (AC-3)
[ad] Opening audio decoder lavc:ac3
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: ATSC A/52A (AC-3) [lavc:ac3]
[cplayer] Starting playback...
[af] Adding filter scaletempo 
[scaletempo] 1.000 speed * 1.000 scale_nominal = 1.000
[af] Adding filter lavrresample 
[scaletempo] 1.000 speed * 1.000 scale_nominal = 1.000
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float
[af]   [scaletempo] 48000Hz stereo 2ch float
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
[ao/coreaudio] requested format: 48000 Hz, stereo channels, float
[ao/coreaudio] selected audio output device: Built-in Output (38)
[ao/coreaudio] converted input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] converted input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] audiounit latency [us]: 354
[ao/coreaudio] device latency [us]: 291
[ao/coreaudio] using soft-buffer of 9600 samples.
[cplayer] AO: [coreaudio] 48000Hz stereo 2ch float
[cplayer] AO: Description: CoreAudio AudioUnit
[scaletempo] 1.000 speed * 1.000 scale_nominal = 1.000
[af] Removing filter lavrresample 
[scaletempo] 1.000 speed * 1.000 scale_nominal = 1.000
[af] Adding filter lavrresample 
[scaletempo] 1.000 speed * 1.000 scale_nominal = 1.000
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float
[af]   [scaletempo] 48000Hz stereo 2ch float
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
[scaletempo] 1.000 speed * 1.000 scale_nominal = 1.000
[vd] Pixel formats supported by decoder: vda_vld vda yuv420p
[vd] Pixel formats supported by decoder: vda_vld vda yuv420p
[vd] VIDEO:  1280x720  23.976 fps    0.0 kbps ( 0.0 kB/s)
[vd] VDec: vo config request - 1280 x 720 (vda)
[vd] VO Config (1280x720->1280x720,0x429)
[vf] Video filter chain:
[vf]   [vd] 1280x720 vda Autoselect/Autoselect CL=mpeg2/4/h264
[vf]   [in] 1280x720 vda BT.709 (HD)/TV CL=mpeg2/4/h264
[vf]   [out] 1280x720 vda BT.709 (HD)/TV CL=mpeg2/4/h264
[cplayer] VO: [opengl] 1280x720 vda
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl] Resize: 1280x720
[vo/opengl] Window size: 1280x720
[vo/opengl] Video source: 1280x720 (1280x720)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[vo/opengl] Video scale: 1.000000/1.000000
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0
[vo/opengl] Texture for plane 0: 1280x720
[vo/opengl] Reinit rendering.
[vo/opengl] compiling shader program 'frag_osd_libass', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2DRect
[vo/opengl] [  2] #define USE_RECTANGLE 1
[vo/opengl] compiling shader program 'frag_osd_rgba', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2DRect
[vo/opengl] [  2] #define USE_RECTANGLE 1
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[vo/opengl] compiling shader program 'final', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2DRect
[vo/opengl] [  2] #define USE_RECTANGLE 1
[vo/opengl] [  3] #define SAMPLE(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_l)
[vo/opengl] [  4] #define USE_COLOR_SWIZZLE gbra
[vo/opengl] [  5] #define USE_COLORMATRIX 1
[vo/opengl] [  6] #define USE_CHROMA_FIX 1
[vo/opengl] [  7] #define SAMPLE_C(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_c)
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /Users/Borat/.mpv /usr/local/bin /usr/local/Cellar/mpv/HEAD/etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[vd] set video colors gamma=3 
[vo/opengl] Resize: 2560x1440
[vo/opengl] Window size: 2560x1440
[vo/opengl] Video source: 1280x720 (1280x720)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 0) 2560x1440
[vo/opengl] Video scale: 2.000000/2.000000
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0
[vo/opengl] Reinit rendering.
[vo/opengl] compiling shader program 'frag_osd_libass', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2DRect
[vo/opengl] [  2] #define USE_RECTANGLE 1
[vo/opengl] compiling shader program 'frag_osd_rgba', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2DRect
[vo/opengl] [  2] #define USE_RECTANGLE 1
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[vo/opengl] compiling shader program 'final', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2DRect
[vo/opengl] [  2] #define USE_RECTANGLE 1
[vo/opengl] [  3] #define USE_INV_GAMMA 1
[vo/opengl] [  4] #define SAMPLE(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_l)
[vo/opengl] [  5] #define USE_COLOR_SWIZZLE gbra
[vo/opengl] [  6] #define USE_COLORMATRIX 1
[vo/opengl] [  7] #define USE_CHROMA_FIX 1
[vo/opengl] [  8] #define SAMPLE_C(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_c)
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[vd] set video colors brightness=3 
[vd] set video colors contrast=3 
[vd] set video colors saturation=5 
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:00 / 00:25:24 (0%) A-V:  0.000
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[statusline] AV: 00:00:01 / 00:25:24 (0%) A-V:  0.000 Dropped: 0/1
[cplayer] Run command: seek, flags=9, args=[5.000000, relative, unused]
[mkv] Seeking to 682583803 to read header element 0x1c53bb6b.
[mkv] /---- [ parsing cues ] -----------
[ffmpeg] SWR: discarding 1000 audio samples
[mkv] \---- [ parsing cues ] -----------
[statusline] AV: 00:00:06 / 00:25:24 (0%) A-V:  0.000
[vd] Pixel formats supported by decoder: vda_vld vda yuv420p
[statusline] AV: 00:00:11 / 00:25:24 (0%) A-V:  0.000
[cplayer] Run command: seek, flags=9, args=[5.000000, relative, unused]
[ffmpeg] SWR: discarding 1000 audio samples
[statusline] AV: 00:00:16 / 00:25:24 (1%) A-V:  0.000
[vd] Pixel formats supported by decoder: vda_vld vda yuv420p
[statusline] AV: 00:00:19 / 00:25:24 (1%) A-V:  0.000
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[cplayer] 
[ad] Uninit audio filters...
[af] Removing filter lavrresample 
[af] Removing filter scaletempo 
[ad] Uninit audio decoder.
[vd] Uninit video.
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
````

If you would like the copy of the file, I can probably upload it somewhere. Obviously this is a super low priority issue. Feel free to ignore this if you all are too busy. :)

Thanks.
Screenshot: 
![mpv](https://cloud.githubusercontent.com/assets/7689996/6566691/4a0c451a-c693-11e4-819b-1d438cb40335.jpg)

**Comment by wm4** [comment]
Yes, a copy or a small sample of the file would be useful.

What's movist?

**Comment by lachs0r** [comment]
Did you try without hardware decoding?

**Comment by ainstushar** [comment]
@lachs0r disabling hwdec made it work. That's strange. Any reason why this would be happening?

@wm4 movist is a media player for mac. Not free. I will upload the file and put a link down when I get a chance.

**Comment by ainstushar** [comment]
Example 1: http://goo.gl/9edyJZ
Example 2: http://goo.gl/ZZICwY

Both files approx 700mb. Same issue on both files.

**Comment by selsta** [comment]
Could you check if movist has hardware decoding enabled and still plays the video fine? I'm quite sure that your video triggers a bug in the vda framework. 

Happens to me quite often with blu-ray AVC remuxes.

**Comment by ainstushar** [comment]
Yes, movist is using hardware acceleration and plays the video just fine.

**Comment by selsta** [comment]
Okay that confirms that VDA itself is not the problem.

**Comment by wm4** [comment]
Can somebody post a small cut sample from these files? I'm not downloading 700mb from one of the shittiest filehosters ever.

>(or maybe movist is using some hacks to make VDA work.)

Or it doesn't use VDA at all.

**Comment by pigoz** [comment]
> Yes, movist is using hardware acceleration and plays the video just fine.

Are you sure it's not falling back to software decoding?

I can reproduce this issue with VDA btw, I will try to fix it if it's a bug in FFmpeg.

**Comment by ainstushar** [comment]
@pigoz Yes I am sure. When the player is using VDA, it turns the file name to blue in video properties. Also, I can confirm by processor usage too (disabled the VDA in pref -> 28% CPU, enabled -> 7%).

@wm4 Sorry man. I trimmed it using avidemux to 30mb and uploading it to google drive. http://goo.gl/N89u2J

**Comment by wm4** [comment]
It works fine on Linux with hardware decoding, so this is likely VDA/OSX related. (But it also could be just the hardware messing up; hard to tell.)

**Comment by wm4** [comment]
This was fixed in ffmpeg just now.

**Comment by pigoz** [comment]
Yep the sample is fixed. Thanks XMBC devs!

**Comment by ainstushar** [comment]
I feel like this bug is back. Recently updated my ffmpeg (and reinstalled mpv with the new build) and mpv hangs when trying to play any video files with ``hwdec=auto``. Works fine if I disable hwdec... Can one of the devs report this to ffmpeg? I don't really know what to put in bugreport since I never use ffmpeg directly.

Verbose log: http://pastebin.com/v4MTBiQR
mpv gets stuck at ``[vd] Pixel formats supported by decoder: vda_vld vda yuv420p``
