### ISSUE TITLE
dpkg-buildpackage complaining on libass

### ISSUE THREAD

**Issue by raeisi** [mpv-player/mpv#2384]
Trying to compile mpv on Debian Jessie.

These go fine:

$ git clone https://github.com/mpv-player/mpv-build.git
$ cd mpv-build
$ ./update
$ rm -f mpv-build-deps_*_*.deb
$ mk-build-deps -s sudo -i

but below command is failing complaining about libass
$ dpkg-buildpackage -uc -us -b -j4 

.......
configure.ac:6: installing './compile'
configure.ac:6: installing './config.guess'
configure.ac:6: installing './config.sub'
configure.ac:2: installing './install-sh'
configure.ac:2: installing './missing'
libass/Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... armv7l-unknown-linux-gnueabihf
checking host system type... armv7l-unknown-linux-gnueabihf
checking how to print strings... printf
checking for style of include used by make... GNU
checking for gcc... /usr/bin/gcc-4.8
checking whether the C compiler works... no
configure: error: in `/root/mpv-build/libass':
configure: error: C compiler cannot create executables
See `config.log' for more details
debian/rules:40: recipe for target 'libass_config' failed
make[1]: *** [libass_config] Error 77
make[1]: Leaving directory '/root/mpv-build'
debian/rules:30: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

Have also built and installed libass-0.13.0 but it didn't help.

**Comment by kevmitch** [comment]
Sounds like a c compiler isn't installed. Did the build-dep actually install al the dependencies?
What does ```gcc -v``` say?

**Comment by raeisi** [comment]
yes it finished installing all the dependencies and it is hanging on making the package on the error I sent you
root@DeJeBnPr:~# gcc -vUsing built-in specs.COLLECT_GCC=gccCOLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapperTarget: arm-linux-gnueabihfConfigured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv7-a --with-fpu=vfpv3-d16 --with-float=hard --with-mode=thumb --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihfThread model: posixgcc version 4.9.2 (Debian 4.9.2-10) 
 


     On Tuesday, 6 October 2015, 19:46, kevmitch <notifications@github.com> wrote:
   

 Sounds like a c compiler isn't installed. Did the build-dep actually install al the dependencies?
What does gcc -v say?—

**Comment by kevmitch** [comment]
ok, so you do have a seemingly sane c compiler. what does the ```libass/config.log``` say is failing? Please try and preserve the line breaks. You might actually want to use http://sprunge.us/ since it might be large.

**Comment by raeisi** [comment]
worth to mention I am doing it on a Debian Jessie on Armhf (Banana Pro) and the goal is to have a FrameBuffer player on this device. 


     On Wednesday, 7 October 2015, 1:11, shahrouz raeisi <s.raeisi@yahoo.co.uk> wrote:
   

 here you go. the whole file.
http://sprunge.us/QPWP

If you can not see it I have attached it as well. 


     On Wednesday, 7 October 2015, 0:23, kevmitch <notifications@github.com> wrote:
   

 ok, so you do have a seemingly sane c compiler. what does the libass/config.log say is failing? Please try and preserve the line breaks. You might actually want to use http://sprunge.us/ since it might be large.—

**Comment by raeisi** [comment]
here you go. the whole file.
http://sprunge.us/QPWP

If you can not see it I have attached it as well. 


     On Wednesday, 7 October 2015, 0:23, kevmitch <notifications@github.com> wrote:
   

 ok, so you do have a seemingly sane c compiler. what does the libass/config.log say is failing? Please try and preserve the line breaks. You might actually want to use http://sprunge.us/ since it might be large.—

**Comment by kevmitch** [comment]
mmm, seems to be using gcc-4.8 even though you have gcc-4.9 as system default. are you using arm, sparc, powerpc or something weird.

**Comment by raeisi** [comment]
By the way I can start from rootfs if you tell me what packages are needed to built this


Regards, 
Shahrouz Raeisi
+4747747742

Sent by mobile

**Comment by raeisi** [comment]
It's Arm7 


Regards, 
Shahrouz Raeisi
+4747747742

Sent by mobile

**Comment by kevmitch** [comment]
Ah, I think it's time for an old hack to die.

I don't know what you mean by rootfs, but the packages listed in debian/control as build-deps (and therefore installed by mk-build-deps) should be sufficient.

**Comment by kevmitch** [comment]
should be fixed in mpv-player/mpv-build@7bc0b120f3cb4ab32a8d795dd5e1ce2ad8b5074d

**Comment by raeisi** [comment]
Thanks, a lot
I have built it and it is installed now. I have also SDL with Mali Driver support installed but still get an error like below when trying to play the video

root@DeJeBnPr:~/DebFiles# mpv -vo sdl /mnt/lg_four_seasons_under_the_sea-DWEU.mkv Playing: /mnt/lg_four_seasons_under_the_sea-DWEU.mkv (+) Video --vid=1 (*) (h264) (+) Audio --aid=1 --alang=eng (*) (ac3)[vo] Video output sdl not found!Error opening/initializing the selected video_out (-vo) device.Video: no videoAO: [alsa] 48000Hz stereo 2ch floatA: 00:00:05 / 00:12:00 (0%)[input] No key binding found for key '0x18'.A: 00:00:09 / 00:12:00 (1%)

Exiting... (Quit)root@DeJeBnPr:~/DebFiles# 



     On Wednesday, 7 October 2015, 2:05, kevmitch <notifications@github.com> wrote:
   

 should be fixed in mpv-player/mpv-build@7bc0b12—

**Comment by wm4** [comment]
mpv wasn't compiled against SDL for some reason.

Also, SDL on a device that runs MALI is most likely too slow, both for decoding and display.

**Comment by kevmitch** [comment]
Yes, I've disabled SDL in the debian package because I thought it was useless. Was I wrong? It was also not possible to satisfy the dependency in debian wheezy, but I guess that shouldn't be a problem anymore.

**Comment by wm4** [comment]
> I've disabled SDL in the debian package because I thought it was useless.

Not really. So far it always turned out useless, and I bet this will be the outcome in this case too.

**Comment by kevmitch** [comment]
ok, well closing this. 
Open an other bug at https://github.com/mpv-player/mpv-build/issues if you really want sdl2 included.
