### ISSUE TITLE
touchinput on touchscreen in linux wayland not working

### ISSUE THREAD

**Issue by FearlessSpiff** [mpv-player/mpv#3457]
### mpv version and platform

mpv git-724f60b (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Aug 22 16:58:21 CEST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.2

Linux 4.7.1-1-ARCH
Gnome 3.20
Lenovo Yoga 900
### Reproduction steps

I use mpv with 
`hwdec=vaapi
vo=opengl
fs=yes` 

When I touch the screen on X11 everything is ok -> OSD shows up and can be used.
On Wayland nothing happens. Touch input is ignored
### Expected behavior

Touchinput works on Wayland.
### Actual behavior

Touchinput is ignored on Wayland. Ok on X11.
### Log files

nothing relevant in logfile
### Sample files

any video file

**Comment by atomnuker** [comment]
Fixed in commit 68f9ee7e0b3fd

**Comment by RussianNeuroMancer** [comment]
https://github.com/mpv-player/mpv/issues/2396#issuecomment-370885195

Still not working right now (or regressed recently). Do I need to fill new bugreport?
