### ISSUE TITLE
Immediate A-V desync disables video-sync

### ISSUE THREAD

**Issue by andreaskem** [mpv-player/mpv#3610]
### mpv version and platform

mpv 0.20.0 and git master
x86-64 Linux (up-to-date Arch Linux)
ffmpeg 3.1.3

### Reproduction steps

Preface: I am not sure if the file really is broken.
Play the example file uploaded to the address given below with mpv:

mpv --no-config -v --video-sync=display-resample TWBB_test.mkv

(The attached example file is the beginning of a DVD rip created using makemkv. The extraction of the first 5 seconds was performed using mkvtoolnix. The original file shows the same behavior. I am not 100% sure if the file is corrupted or not and do not really know how to check. I do not know in what way the file could be corrputed. mkvinfo does not report a problem and other DVD rips created by makemkv do not exhibit this problem.)

### Expected behavior

mpv plays the file without a warning and enables video sync.

### Actual behavior

mpv immediately detects A-V desynchronization and seems to disable display sync:

    [   1.246][w][cplayer] 
    [   1.246][w][cplayer] Audio/Video desynchronisation detected! Possible reasons include too slow
    [   1.246][w][cplayer] hardware, temporary CPU spikes, broken drivers, and broken files. Audio
    [   1.246][w][cplayer] position will not match to the video (see A-V status field).
    [   1.246][w][cplayer] 
    [   1.246][v][cplayer] Change display sync audio drift: 1
    [   1.270][v][cplayer] Video sync mode disabled.

The A-V drift seems to normalize quickly but display sync does not seem to get reactivated automatically. If I seek forward, DS seems to get reactivated. If I seek to the beginning of the file, it gets deactivated again and stays off. This behavior seems very odd.

### Log files

http://sprunge.us/WUZf

### Sample files

https://0x0.st/1Pz.mkv

**Comment by wm4** [comment]
It desyncs because audio starts late. Normally it should wait until audio starts, and this is a regression that was probably caused by a bug fix.

**Comment by wm4** [comment]
Fixed the desync. The DS disable behavior will stay the way it is.

**Comment by andreaskem** [comment]
My file plays perfectly now with this fix. Thank you very much!

**Comment by Maxxee** [comment]
This bug was never fixed and is still present. Almost every MKV I play suffers from it.
After playing a lot with different settings and different mpv versions, I am now quite sure that this is due to bad code.

Skipping forward/backward re-enables video-sync=display-resample but at random times it happens again which makes mpv a really bad experience overall.
No matter which settings I remove, gpu-context, scale, cscale, dscale, tscale, dither-depth, deband, etc. - nothing helps, the bug *will* return as long as video-sync=display-resample and interpolation are set.

**Comment by garoto** [comment]
Why don't you at leat provide a sample?

**Comment by Maxxee** [comment]
This is not an option as all the files are too big to provide any example, > 6 GB.
Also I don't expect any fix soon as this is a long present bug and there are probably way too many things involved like filters.

**Comment by garoto** [comment]
> Gee, I wonder if there is a tool that can cut any arbitrary lenght of a video file

**Comment by Maxxee** [comment]
It seems that this only happens with large files. Snippets taken from such files haven't show this issue.

**Comment by Maxxee** [comment]
I finally found that f.lux is the problem here. Deactivating f.lux fixes it.

**Comment by Maxxee** [comment]
Btw, are there any plans to investigate this? f.lux is important state of the art software ...

**Comment by Maxxee** [comment]
Wow, it's a general problem, not only while using f.lux and your bad code spits in the user's face by telling him:
"Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field)."

And all you do is ignoring the problem. Wow, just wow.

**Comment by Hrxn** [comment]
This is still an unrelated issue....

**Comment by haasn** [comment]
@Maxxee Works for me. Feel free to send me a crystal ball so I can remote debug your problem.

**Comment by daed-alus** [comment]
i'm not very happy to accommodate such rude persons, but i see the same as Maxxee on almost every playback start
not using f.lux and no broken files

[mpv.log](https://github.com/mpv-player/mpv/files/2613013/mpv.log)

**Comment by Akemi** [comment]
it was said before so please read the comments carefully.

> No, there are no plans to follow up on some **random comment in an unrelated issue** with no log or information attached other than the name of a random proprietary program.

> This is still an unrelated issue here...

to make it clear, the original issue from 2016 is completely unrelated to the issue you are having with f.flux. if you really want it fixed then go along the normal procedure. look for an already open issue and if there is none open a new issue with all information provided that the template is asking for.

i did half of the works for you, even with what little information i've got. seems like these two issues are related, #4846 and #4921. the former is already closed.

**Comment by daed-alus** [comment]
i said, that **i'm not using f.lux** and Maxxee also stated this

> Wow, **it's a general problem, not only while using f.lux** and your bad code spits in the user's face by telling him:

> 
> **not using f.lux and no broken files**

thanks for reading the comments carefully

**Comment by daed-alus** [comment]
reading my comment would have been completely sufficient and should be, for decency's sake, the absolute minimum, if you accuse sb to not read anything carefully
just posted here cause i had the exact same issue as the original poster and the last poster that had this problem again
but hey i didn't want to offend sb (yet still i feel offended now and begin to understand users like Maxxee)
i know my place now, will stop posting here and hold myself back in the future

**Comment by Maxxee** [comment]
The bug even occurs when pressing i for playback info, on an i7 system.
It's quite ridiculous how you deny it all the time, just because you know it's due to bad code of yours.
How dare you calling it "a fork of mplayer2 and MPlayer".

> i am well in my right here and you don't have any right to be wise-ass.
This really shows your attitude.

**Comment by haasn** [comment]
This is an issue tracker. Please blog somewhere else.

Next time, if you have an issue, [open an issue](https://github.com/mpv-player/mpv/issues/new). It's really not that hard.
