### ISSUE TITLE
Subtitles drag&drop does not work under Wayland

### ISSUE THREAD

**Issue by victornoel** [mpv-player/mpv#3676]
### mpv version and platform

mpv 0.20.0 on Linux/Wayland/Gnome 3.22
### Reproduction steps /

Open a video, with or without x11 backend (`vo=opengl-hq:backend=x11`) and drag and drop (from nautilus) a subtitle on the video window.
### Expected behavior

Under Xorg, drag and dropping a subtitle on the video will make the subtitle be taken into account by mpv and shown on the video.
### Actual behavior

Nothing happens, the subtitle is not shown nor is cyclable with the `j` key. It works well by passing the subtitle as a command line option of course.
### Log files

https://gist.github.com/victornoel/8c5f6242248ae5611f0ed986372a3153

**Comment by wm4** [comment]
CC @atomnuker

**Comment by atomnuker** [comment]
Yep, working on getting the old dropped code to work. It kinda half works, still need to figure out why the drop event never gets received.

**Comment by Hapoofesgeli** [comment]
Some love for this would be really appreciated. To me this is a much bigger deal breaker than something like window borders, having to use command-line for adding a subtitle or playing a new video is a hard usability issue.

**Comment by atomnuker** [comment]
Fixed in commit 68f9ee7e0b3fd

**Comment by geomaster** [comment]
I am still facing the issue on 0.29.1, GNOME 3.30.2, weston 5.0.0.

The issue can be apparently solved by running mpv with `--gpu-context=wayland`. Unfortunately, it also disables window decorations (the title bar).

Ubuntu has a patch which forces the use of Wayland by default when available and [fixes the issue](https://bugs.launchpad.net/ubuntu/+source/mpv/+bug/1730625), albeit with the same window decoration problem:

```patch
Description: Prefer native Wayland over X11 if both are present
 In Gnome Shell with Xwayland running, both protocols are present but only
 one will work with libva (VA-API). This is because libva only supports DRI2
 and Xwayland only supports DRI3. So libva fails to initialize using the X11
 option and mpv gives up without trying Wayland. We must force mpv to use
 native Wayland instead, which libva supports properly (albeit without a
 titlebar).
Author: Daniel van Vugt <daniel.van.vugt@canonical.com>
Bug: https://github.com/intel/libva/issues/79
Bug-Ubuntu: https://bugs.launchpad.net/bugs/1698287
Bug-MPV: https://github.com/mpv-player/mpv/pull/4556
Forwarded: yes
Last-Update: 2018-08-09

--- a/video/out/gpu/context.c	2018-07-23 00:46:25.000000000 +0800
+++ b/video/out/gpu/context.c	2018-08-09 17:50:21.799132327 +0800
@@ -80,6 +80,9 @@
 #if HAVE_GL_DXINTEROP
     &ra_ctx_dxgl,
 #endif
+#if HAVE_GL_WAYLAND
+    &ra_ctx_wayland_egl,
+#endif
 #if HAVE_GL_X11
     &ra_ctx_glx_probe,
 #endif
@@ -89,9 +92,6 @@
 #if HAVE_GL_X11
     &ra_ctx_glx,
 #endif
-#if HAVE_GL_WAYLAND
-    &ra_ctx_wayland_egl,
-#endif
 #if HAVE_EGL_DRM
     &ra_ctx_drm_egl,
 #endif
```

**Comment by sheepdestroyer** [comment]
Still not working on fedora 35

**Comment by CounterPillow** [comment]
@sheepdestroyer open a new issue with a full log file showing you attempting to drag and drop a subtitle onto the window, and with all necessary version information the issue template asks you for.
