### ISSUE TITLE
Issues with macOS native FS

### ISSUE THREAD

**Issue by sosia** [mpv-player/mpv#3944]
Greetings,
I finally managed to try out the new cocoa native-fs merged a bunch of days ago, and first of all I want to thank you all: IMHO it's a sensible improvement over the old method, and mpv taking a new space in fs fits way better with my workflow.

However, I had some troubles with it that I didn't see mentioned in the PR or in any issues in the tracker:

- [x] 1. **Issues with playback restore in fullscreen**
Using the playback restore function (Shift+q) with the player in fullscreen results in two weird issues, both always reproducible. 
First of all, when the file is opened again and mpv proceeds to restore playback, for half a second of so it only shows a black window in fullscreen, with some white flashes on the left (leftovers of an animation of some sort?), then the video starts to play without issue. (**solved by system update 10.12.4**)
But then, if you go back to windowed, instead of showing a regular window as big as the video, the windows itself is always 960x480 no matter what. To show you, I took a screenshot of this happening: the source video file is 1280x720, and it's been fullscreened, closed with Shift+q, restored then windowed: https://0x0.st/97j.png. 
Note that taking a screenshot with `screenshot window` keeps the black bars: https://0x0.st/97p.jpg. (**solved by** 4fe45fb)

- [x] 2. **Black flash entering or exiting fullscreen**
This doesn't happen all the times, and it doesn't seems to follow a precise pattern: some random times, regardless if the video is playing or paused, the window goes black for a split second. I wasn't able to catch any significant log, nor the player shows any dropped frame.

- [x] 3. **Small delay with keyboard input after going fullscreen**
For a very short time, mpv is not responsive to keyboard's inputs right after going fullscreen. I actually suspect this happens because, even though the resize is instantaneous, behind the window the system-wide space transition animation is going, so the player isn't in control until the animation is ended. Correct me if I'm wrong, but if that's the case I fear there's nothing to do about that (it's not a big issue, either), but I thought it was worth of a report nonetheless. (**solved by** 063ca8f)

I'm using the latest master on macOS 10.12.2, but I'm sure all of this is easily reproducible in 0.23.

**Comment by Hamuko** [comment]
>For a very short time, mpv is not responsive to keyboard's inputs right after going fullscreen. I actually suspect this happens because, even though the resize is instantaneous, behind the window the system-wide space transition animation is going, so the player isn't in control until the animation is ended.

I've experienced this as well. Quite annoying since I've gotten used to hitting both F and Spacebar to toggle full screen and playback. And I imagine the cause is exactly due to the transition animation.

**Comment by pigoz** [comment]
I find 3 very annoying as well, but I don't think it's configurable

**Comment by Akemi** [comment]
1. didn't test it yet but i think i know the issue. should be (easily) fixable.
2. that might be related to the fs space transition. it's a bit hard to debug since it's rather random.
3. definitely the space transition's fault. it would be more obvious with an animation instead of the instant fs. it can't be deactivated so it's not avoidable.

since there is still a demand for the old fs behaviour i might add a 'fs window' fullscreen as an option. i have a [branch](https://github.com/Akemi/mpv/commits/cocoa_windowedfs) which is a bit buggy but is similar to the old fs with some of the bugfixes of the new one. i will look into it if it's really wanted.

don't expect any bugfixes soon, since christmas and new years are busy this year for me. though i will definitely look into it.

**Comment by joeynotjoe** [comment]
As someone who takes notes while watching videos in fullscreen, I would really love having the fs window option. Thanks, and happy holidays!

**Comment by human-bean** [comment]
Does 'Reduce motion' (System Preferences>Accessibility>Display) help with 3? Can't test it myself, since this option is only available on Sierra.

**Comment by Hamuko** [comment]
It does not solve the issue and I doubt that it helps. As far as I can tell, _Reduce motion_ just cuts back on the movement, not the transition time. It just does a fade instead of a slide.

**Comment by tewe** [comment]
I don't like full screen as a different space at all. Working with video I switch apps a lot, and this is just too slow. I also can't reference other windows without shrinking the video into a tiny window as well.

But actual playback seems to work better, and it's probably less code, so what can you do.

**Comment by Akemi** [comment]
i was trying to reproduce issue 1, but i can't. does it also happen with an empty config? any other conditions that needs to be met?

**Comment by sosia** [comment]
Yes, it also happens with an empty config. I actually temporarily moved my whole config folder and I'm still able to reproduce it every time. I have a last generation's rMBP with the iGPU alone, but I can ask a friend with the dual GPU model of the same generation to run a test, just to make sure it's not a GPU/driver issue.
The log file of course doesn't say anything about it, but let me know if I can provide you anything useful to debug the issue.

**Comment by sosia** [comment]
Oh, and I forgot to say, about issue 2: I'm not entirely sure anymore it's native-fs's fault, as I've start to notice it sometimes happens at random even on "general" resizes (e.g. bounding a 2x window resize to a key).

**Comment by Akemi** [comment]
yeah, i really wonder if anyone else can reproduce this. you could provide me with a log for now, maybe i an spot something suspicious.

**Comment by sosia** [comment]
Well, that's getting really strange...
I tried to start the video from the terminal to provide you a more verbose log that the one provided with the --log-file option, and i notice that the problem 1 shows up only when the video is opened from the app bundle!
Steps I used to reproduce (100% reliably, with blank config):
- Opened a file, no matter if from the command line or via double click
- FS, then Shift+Q
- Now: if the file is reopened via command line, it reopens fullscreen without artifact of sort, and deactivating fullscreen produces a "normal" window. If the same file is reopened via double click or by drag and drop on the dock icon, it always shows the issue described in point 1.

**Comment by Akemi** [comment]
yes i can reproduce it like this. hopefully i can also debug it properly

**Comment by Akemi** [comment]
PR #4034 should fix the first issue.

**Comment by sosia** [comment]
Tank you very much, it works! The window now it's restored to the correct size.
As the only leftover of that issue, I still see some "garbage" on the screen upon fullscreen restoring: half of an animation, a slow resize, ... 
All of it goes away if I put `force-window=no` in my config, could those things be related (like, the forced window is drawn too fast or something like that)?

**Comment by Akemi** [comment]
are the garbage pixels related to watch later? can it be reproduced from the terminal with `force-window=yes`? do they just occur when toggling to fullscreen? does setting `opengl-pbo=yes` or setting it to no if you set it to yes help?

**Comment by sosia** [comment]
>are the garbage pixels related to watch later?
They're not exactly garbage pixel: I tried to make a video of it, to show you the issue directly (forgive me for the shit quality, but I took the video with my phone).
This is what happens when I restore a video closed in fullscreen with Shift+q: https://a.pomf.cat/swcork.mp4

>can it be reproduced from the terminal with force-window=yes?
Nope, not with `--force-window=yes` nor `--profile=pseudo-gui`, it only happens with the bundle.

>do they just occur when toggling to fullscreen?
It occurs only when restoring a fullscreen window with watch-later, "normal" fulscreen toggling is fine.

>does setting opengl-pbo=yes or setting it to no if you set it to yes help?
It happens with both `--opengl-pbo=yes` and `--opengl-pbo=no`.

**Comment by Akemi** [comment]
the garbage we are talking about is that small after image of the video? i also see the desktop poking out on the top left. it kinda looks like the standard space transition animation is showing through the window.

**Comment by sosia** [comment]
Exactly, the small afterimage (which I believe it actually is the video at its "windowed resolution" getting resized), plus the desktop leaking.
If I open the same file via terminal (or set `force-window=no` in the config file), they don't show up, the video is restored directly at the right dimensions without any piece of the desktop showing up.

**Comment by Akemi** [comment]
that's very weird. atm i have no clue what do.

**Comment by sosia** [comment]
It seems that opening video files on my "NAS" doesn't make the issue to show up. The "NAS" is actually a USB powered external HD connected to a Pi3 and mounted via SMB, fast enough to watch videos on my laptop without framedrop, but way slower than my internal storage (which contains the files I'm using to test). It doesn't explain the discrepancies between bundle and CLI behaviour, but maybe it's useful to you.

**Comment by sosia** [comment]
I tried to do some test to help in debugging 2, since it's a bit annoying.

It can happen pretty much in any fs-in or fs-out transition. I especially notice it on playback start (open file > pause > fs), but it's not limited to that, nor it's always reproducible. Also, unlike previously stated, I can reproduce it pretty much only on fullscreen and not on normal resizes, and the issue doesn't happen at all in mpv 0.22.0, so I'm positive that it is after all indeed related to the native fs.

With `--no-config` it doesn't seems to happen, so I'd thought it would have been useful to scrap my config and try to add one by one the video settings to find a culprit, but as soon as I add even something "soft" as cscale=bicubic, the issue is triggered. `--opengl-dumb-mode` gives the same results as `--no-config`. It shouldn't be a performances-related problem, though: while my GPU (Iris Pro) is surely not a high-end one, the playback is smooth even with taxing scalers like ewa_lanczos, and my video config is basically just opengl-hq, icc-profile with cache and blend-subtitles. I also have direct confirmation that the issue shows up also on the AMD card of the double GPU model from the same generation (2015 15'' rMBP).

**Comment by Akemi** [comment]
just wondering does `--opengl-early-flush=no` help?

**Comment by sosia** [comment]
Oh, right, I tried it too: no, it doesn't seems to help.

**Comment by Akemi** [comment]
could you try my [cocoa_ghosting](https://github.com/Akemi/mpv/commit/315ddf45cb3d42df5b25c5407a3ec9e399768995) branch and see if it fixes your 'ghosting' problem? just wondering if this is also related to the double buffering change. also try it with `--opengl-early-flush=no --opengl-pbo=yes` and maybe the other combination and that branch.

**Comment by sosia** [comment]
Unfortunately, it doesn't seems to help this specific issue. I tried with the various combinations of the aforementioned options, but the ghosting is still there every time.

**Comment by Akemi** [comment]
i pushed a different fix to the same [cocoa_ghosting](https://github.com/Akemi/mpv/commit/ec05b068e84be002c2f48fb1556fc8cef7b9da0a) branch. does this change anything?

**Comment by sosia** [comment]
Nope, sorry. And actually this commit makes mpv to behave weird (the titlebar stays visible for a while in fs, and going back windowed two black bars appears above and under the picture).

**Comment by Akemi** [comment]
pushed another [fix](https://github.com/Akemi/mpv/commit/3a5debf67c88a4c2ce8cb0639a0414b5f48ef7df) to the same branch. still those ghosting issues?

don't worry about the other things that don't work. just testing if something were doing is at fault or if something is wrong with apple's api.

**Comment by sosia** [comment]
No ghosting now! Ignoring little side things, the issue we're talking about doesn't show up with that fix.

**Comment by Akemi** [comment]
just a heads up. i think i found the issue with **Small delay with keyboard input after going fullscreen** by chance and it is most likely fixable. though it might require a big refactor that won't happen any time soon. i think i can also fix **Black flash entering or exiting fullscreen** since i found a way to make the fullscreen animation flawless instead removing and hiding it. also don't expect a fix for that any time soon since it will require some more work.

**Comment by sosia** [comment]
Don't worry, thank you for investigating these issues!

**Comment by Akemi** [comment]
does [this branch](https://github.com/Akemi/mpv/commits/cocoa_event) fix **Small delay with keyboard input after going fullscreen** for you?

**Comment by sosia** [comment]
Yes, it definitely seems so!

**Comment by Hamuko** [comment]
@Akemi Seems to work fine.

**Comment by Akemi** [comment]
that's good news. thx for testing.

**Comment by Akemi** [comment]
i merged the key input changes. sry it took so long i had some busy 2 weeks.

**Comment by sosia** [comment]
Thank you, works like a charm.

**Comment by sosia** [comment]
It's too soon to be sure, but from a quick glance it seems that I'm not able to reproduce the dreaded "ghosting" when restoring a fullscreen video anymore on 10.12.4.

**Comment by sosia** [comment]
I confirm that I'm not able to reproduce the ghosting issue after three days and a reboot, so I think it's safe to consider it a system bug fixed in update 10.12.4.

**Comment by Akemi** [comment]
that's good to hear. the last issue i most likely fixable but will be a larger refactor. it will also fix several other issues. though it's still a long way to go.

**Comment by Akemi** [comment]
PR #4391 should fix the last of the issues mentioned here. though you might need to use it with `--no-border` for now. other issue you may encounter can be reported on the PR.

**Comment by sosia** [comment]
Tried that branch, it still does a little black flash when entering/exiting fullscreen, but this time it always happens in the exact moment the video "adjusts" to the display aspect ratio (which as you write in the PR is a know problem) so it could likely be an entirely different thing from the one reported here. I'll retry it once the aspect ratio issue is solved to see if it still happens or not and report in the PR.
Everything else seems to work just fine, great job as always!

**Comment by Akemi** [comment]
can you try with `--opengl-early-flush=no` does it fix or improve the situation? do you use `--video-sync=display-resample` or `--no-border`?

i can reproduce the black flash but only under certain circumstances and it doesn't always occur here.

**Comment by Akemi** [comment]
i wrote a new 'backend' (cocoa-cb) that utilise the client api and opengl-cb to fix a lot of the issues of the cocoa backend. there is also a PR (#5520) open that changes the window styling, which seems to have the side effect of fixing the black flicker. feel free to test. just need to set `--vo=opengl-cb`

**Comment by Akemi** [comment]
closed via https://github.com/mpv-player/mpv/commit/938ad6ebc037ebb32b41619a31b15f8ade712867.
