### ISSUE TITLE
worse CPU performance on Linux compared to Windows, leads to dropped frames

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4003]
### mpv version and platform
0.23 x64, Win 10x64 vs. Linux 4.9 (Tumbleweed)

### Reproduction steps
When I play a 4k 59.94fps H.264 video on Linux with software decoding, I'm repeatedly getting dropped frames. This does not occur with VDPAU (just few dropped frames in the beginning) and also does not occur with software decoding on Windows 10. Quality settings are the same, so it's not a GPU bottleneck either. GPU power profile is set to maximum performance, driver is latest 375.26.
It's a typical H.264 high profile video and my CPU (2500k@4.6GHz) is far from being pushed to its limits. Other processes like X don't require much CPU performance during the playback, only process which is having notable CPU usage is mpv (as it should be with software decoding, around ~50% and CPU running with full clock). Happens also without any desktop compositor.

### Expected behavior
The performance on Windows and Linux should be equal, shouldn't it?

### Actual behavior
Performance on Linux is much worse with CPU decoding than on Windows 10.

### Log file
Linux CPU decoding:
http://sprunge.us/VMfN

Linux VDPAU:
http://sprunge.us/TjMN

Windows software:
http://sprunge.us/hXPE

**Comment by wm4** [comment]
The driver versions aren't even the same.

On Linux, it might depend on the compositor (if you run one), or on the screensaver state.

In general it's hard to tell which component performs slower. stats-dump on both machines might provide insight.

**Comment by aufkrawall** [comment]
There usually aren't drivers with the same version number on both Linux and Windows at the same time.
I had this this however with different driver versions, xserver versions and Linux kernel versions and also ffmpeg components versions.
As I already stated, this issue also occurs without any compositing and vsync completely controlled by mpv. There is no screensaver etc. running.

Should I know anything else for --dump-stats or should the explanation of the manual be sufficient for me to provide further information?

**Comment by aufkrawall** [comment]
Ok, I found something out:
The problem is either caused by "video-sync=display-resample" or having triple buffering in the Nvidia driver disabled (or at least the option for it not set).
When I enable triple buffering in the Nvidia driver via xorg.conf, the CPU decoding performance playback for demanding 4k 60fps videos is fixed.
However, the default setting in the Nvidia driver is that triple buffering is not enabled. Enabling triple buffering also comes with the penalty of broken vsync in Firefox, so it can also have a bad influence on other applications. So it's probably not a good solution for most people.
Not using "video-sync=display-resample" is not a great solution for me either, since I want to run my display with constant 75Hz and thus I need interpolation for stutter-free playback.

So, what's going on that mpv requires triple buffering explicitly enabled in the Nvidia driver for making "video-sync=display-resample" work correctly?

**Comment by wm4** [comment]
Probably the ANGLE performance issue.

**Comment by aufkrawall** [comment]
Does that mean it's hard to fix?
I wasn't aware mpv was using Angle on Linux for X11 backend as well.

**Comment by wm4** [comment]
Sorry, confused the direction. ANGLE tends to reduce performance on Windows.

**Comment by aufkrawall** [comment]
According to the Nvidia driver doc, the TB option enforces TB for every application that demands double buffering.
So, it seems like mpv somehow needs TB (at least with Nvidia on X11) to achieve the best performance.
I read that the TB option for mpv has been removed. Maybe it would make sense to bring it back for testing purposes?

**Comment by wm4** [comment]
mpv never had such an option. It's fully up to the driver.

**Comment by aufkrawall** [comment]
Well, seems like the issue can't be really fixed at user side.
However, I just switched to cuda-copy decoding to work around it. It seems to be more stable than vdpau-copy, btw. vdpau-copy already is a bit "prone" to the issue this entry is about, in the beginning of the playback there is some chance for a few framedrops with vdpau-copy here, which doesn't seem to be the case with cuda-copy.

**Comment by aufkrawall** [comment]
This issue doesn't occur with a AMD Ryzen R7 1700 CPU, at least I couldn't spot a difference in performance between Windows and Linux mpv with it. However, I need to check this more safely, might do this in a few weeks or months.
Wild guess: Maybe something's broken with ffmpeg and Sandy Bridge on Linux?

**Comment by exaiyo** [comment]
I'm having the same issue on a 2600k i7.  I tried setting hwdec=cuda-copy but that didn't solve the issue.  Did you ever find a solution?

**Comment by aufkrawall** [comment]
I'm with a 6700k for a year now and like Ryzen, it doesn't show the issue either. I guess we won't be able to pin this down unless it got bisected by ffmpeg people. Maybe there is some build config issue regarding AVX2 and Sandy Bridge, but that's just an uneducated guess.

**Comment by laichiaheng** [comment]
I have a Intel Core2 Q8200 CPU, I have to enable the `cpupower.service` and set the `governor` in `/etc/default/cpupower` to `'performance'`, otherwise there are lots of frame delayed and mistimed, although there still are many noticeable frame drops when playing the 1080p movie.

**Comment by aufkrawall** [comment]
I can't recall if I messed with the governor settings. But I wrote that the CPU was running with full clock, so it probably wouldn't have mattered.
Core2 Quad are ancient CPUs and intel_pstate=powersave even still sucks with my 6700k. If you need OS clock governor, try out acpi-cpufreq=schedutil with recent kernels.

Ryzen and Skylake CPUs should still save power, regardless of using acpi-cpufreq=performance when your mainboard bios doesn't screw you up.

**Comment by laichiaheng** [comment]
Does the `schedutil` do better than `performance`? It is the default setting if I disable intel_pstate.

**Comment by aufkrawall** [comment]
There are Phoronix benchmarks where schedutil performs very well with newer CPUs in games and the last time I tried it I had no issues with mpv.
I don't know how well intel_pstate=performance works on ancient CPUs, it usually works without issues on newer ones.
The reported CPU clocks are btw. complete rubbish with anything but intel_pstate=powersave. One should use a wattmeter to measure real power consumption.

**Comment by Jj0YzL5nvJ** [comment]
AMD Phenom(tm) II X6 1090T Processor:
$ cat /sys/devices/system/cpu/cpufreq/policy[0,1,2,3,4,5]/scaling_governor
```
ondemand
ondemand
ondemand
ondemand
ondemand
ondemand
```

**Comment by msshaikh1717** [comment]
i am having high frame drops on linux compare to windows with --no-config

**Comment by laichiaheng** [comment]
> i am having high frame drops on linux compare to windows with --no-config

Try to enable hardware decoding?

**Comment by aufkrawall** [comment]
3.5 years after I reported this, let me just tell you: Chances are very low that such an issue is actually caused by mpv and not something else. Mind to provide any data (at all)?

**Comment by msshaikh1717** [comment]
> 3.5 years after I reported this, let me just tell you: Chances are very low that such an issue is actually caused by mpv and not something else. Mind to provide any data (at all)?

i made 2 log files of https://commons.wikimedia.org/wiki/File:(4k)_Wild_Animal_-_Ultra_HD_Video_TV_60fps_(2160p).webm
both with --no-config -fs on wind10 and xubuntu.
[lin4ktest.txt](https://github.com/mpv-player/mpv/files/4949108/lin4ktest.txt)
[win4ktest.txt](https://github.com/mpv-player/mpv/files/4949109/win4ktest.txt)

**Comment by Jj0YzL5nvJ** [comment]
> [lin4ktest.txt](https://github.com/mpv-player/mpv/files/4949108/lin4ktest.txt)
> [win4ktest.txt](https://github.com/mpv-player/mpv/files/4949109/win4ktest.txt)

Lossless vs. lossy? A very fair comparison...
Why not lossless (opengl/vulkan) vs. lossless (opengl/vulkan) or lossy (direct3d) vs. lossy (xv)?

lin4ktest.txt
```
[   0.042][v][vo/gpu] Probing for best GPU context.
[   0.042][v][vo/gpu/opengl] Initializing GPU context 'wayland'
[   0.042][v][vo/gpu/opengl] Initializing GPU context 'x11egl'
[   0.042][v][vo/gpu/x11] X11 opening display: :0.0
[   0.045][d][vo/gpu/x11] X11 running at 1920x1080 (":0.0" => local display)
[   0.045][d][vo/gpu/x11] Detected wm supports NetWM.
[   0.045][d][vo/gpu/x11] Detected wm supports ABOVE state.
[   0.045][d][vo/gpu/x11] Detected wm supports BELOW state.
[   0.045][d][vo/gpu/x11] Detected wm supports FULLSCREEN state.
[   0.045][v][vo/gpu/x11] Display 0 (DVI-I-0): [0, 0, 1920, 1080] @ 60.000000 FPS
[   0.045][v][vo/gpu/x11] Current display FPS: 60.000000
[   0.051][v][vo/gpu/opengl] EGL_VERSION=1.5
[   0.051][v][vo/gpu/opengl] EGL_VENDOR=NVIDIA
[   0.051][v][vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL_ES OpenGL
[   0.051][v][vo/gpu/opengl] Trying to create Desktop OpenGL context.
[   0.051][d][vo/gpu/opengl] Chosen EGLConfig:
[   0.051][d][vo/gpu/opengl]   EGL_CONFIG_ID=40
[   0.051][d][vo/gpu/opengl]   EGL_RED_SIZE=8
[   0.051][d][vo/gpu/opengl]   EGL_GREEN_SIZE=8
[   0.051][d][vo/gpu/opengl]   EGL_BLUE_SIZE=8
[   0.051][d][vo/gpu/opengl]   EGL_ALPHA_SIZE=0
[   0.051][d][vo/gpu/opengl]   EGL_COLOR_BUFFER_TYPE=12430
[   0.051][d][vo/gpu/opengl]   EGL_CONFIG_CAVEAT=12344
[   0.051][d][vo/gpu/opengl]   EGL_CONFORMANT=77
[   0.065][v][vo/gpu/opengl] Choosing visual EGL config 0x28, visual ID 0x2b
[   0.128][v][vo/gpu/opengl] GL_VERSION='4.4.0 NVIDIA 435.21'
[   0.128][v][vo/gpu/opengl] Detected desktop OpenGL 4.4.
[   0.128][v][vo/gpu/opengl] GL_VENDOR='NVIDIA Corporation'
[   0.128][v][vo/gpu/opengl] GL_RENDERER='GeForce GTX 750 Ti/PCIe/SSE2'
[   0.128][v][vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.40 NVIDIA via Cg compiler'
[   0.128][d][vo/gpu/opengl] Combined OpenGL extensions string:
[   0.128][d][vo/gpu/opengl] EGL_EXT_buffer_age EGL_EXT_client_sync EGL_EXT_create_context_robustness EGL_EXT_output_base EGL_EXT_stream_acquire_mode EGL_EXT_sync_reuse EGL_IMG_context_priority EGL_KHR_config_attribs EGL_KHR_create_context_no_error EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_display_reference EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_partial_update EGL_KHR_swap_buffers_with_damage EGL_KHR_no_config_context EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_reusable_sync EGL_KHR_stream EGL_KHR_stream_attrib EGL_KHR_stream_consumer_gltexture EGL_KHR_stream_cross_process_fd EGL_KHR_stream_fifo EGL_KHR_stream_producer_eglsurface EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_NV_nvrm_fence_sync EGL_NV_post_sub_buffer EGL_NV_quadruple_buffer EGL_NV_stream_cross_display EGL_NV_stream_cross_object EGL_NV_stream_cross_process EGL_NV_stream_cross_system EGL_NV_stream_dma EGL_NV_stream_flush EGL_NV_stream_metadata EGL_NV_stream_remote EGL_NV_stream_reset EGL_NV_stream_socket EGL_NV_stream_socket_inet EGL_NV_stream_socket_unix EGL_NV_stream_sync EGL_NV_stream_fifo_next EGL_NV_stream_fifo_synchronous EGL_NV_stream_consumer_gltexture_yuv EGL_NV_stream_attrib EGL_NV_stream_origin EGL_NV_system_time EGL_NV_output_drm_flip_event EGL_NV_triple_buffer GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_EGL_image_storage GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_multiview_texture_multisample GL_EXT_multiview_timer_query GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_NV_robustness_video_memory_purge GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_shader_subgroup GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_subgroup_partitioned GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NV_gpu_multicast GL_NVX_progress_fence GL_NVX_gpu_memory_info GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum
[   0.131][d][vo/gpu/opengl] Texture formats:
```

win4ktest.txt
```
[   0.026][v][vo/gpu] Probing for best GPU context.
[   0.026][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
[   0.081][v][vo/gpu/d3d11] Using Direct3D 11 feature level 11_0
[   0.081][v][vo/gpu/d3d11] Device Name: NVIDIA GeForce GTX 750 Ti
[   0.081][v][vo/gpu/d3d11] Device ID: 10de:1380 (rev a2)
[   0.081][v][vo/gpu/d3d11] Subsystem ID: 19da:288a
[   0.081][v][vo/gpu/d3d11] LUID: 000000000000a34e
[   0.081][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
[   0.081][v][vo/gpu/d3d11] Using Direct3D 11.1 runtime
[   0.081][v][vo/gpu/d3d11] Maximum Texture2D size: 16384x16384
[   0.082][v][vo/gpu/d3d11] D3DCompiler version: 10.0.18362.1
[   0.100][v][vo/gpu/d3d11] Using DXGI 1.2+
[   0.100][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 1920x1080 @ 8 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)
[   0.100][v][vo/gpu/d3d11] Selected swapchain format R8G8B8A8_UNORM (28), attempting to utilize it.
[   0.102][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G22_NONE_P709 (0), attempting to utilize it.
[   0.102][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G22_NONE_P709 (0): normal: yes, overlay: no
[   0.102][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G22_NONE_P709 (0)!
[   0.102][v][vo/gpu/d3d11] Using flip-model presentation
[   0.102][d][vo/gpu/d3d11] Texture formats:
```

**Comment by msshaikh1717** [comment]
> > [lin4ktest.txt](https://github.com/mpv-player/mpv/files/4949108/lin4ktest.txt)
> > [win4ktest.txt](https://github.com/mpv-player/mpv/files/4949109/win4ktest.txt)
> 
> Lossless vs. lossy? A very fair comparison...
> Why not lossless (opengl/vulkan) vs. lossless (opengl/vulkan) or lossy (direct3d) vs. lossy (xv)?
> 
> lin4ktest.txt
> ```
> [   0.042][v][vo/gpu] Probing for best GPU context.
> [   0.042][v][vo/gpu/opengl] Initializing GPU context 'wayland'
> [   0.042][v][vo/gpu/opengl] Initializing GPU context 'x11egl'
> [   0.042][v][vo/gpu/x11] X11 opening display: :0.0
> [   0.045][d][vo/gpu/x11] X11 running at 1920x1080 (":0.0" => local display)
> [   0.045][d][vo/gpu/x11] Detected wm supports NetWM.
> [   0.045][d][vo/gpu/x11] Detected wm supports ABOVE state.
> [   0.045][d][vo/gpu/x11] Detected wm supports BELOW state.
> [   0.045][d][vo/gpu/x11] Detected wm supports FULLSCREEN state.
> [   0.045][v][vo/gpu/x11] Display 0 (DVI-I-0): [0, 0, 1920, 1080] @ 60.000000 FPS
> [   0.045][v][vo/gpu/x11] Current display FPS: 60.000000
> [   0.051][v][vo/gpu/opengl] EGL_VERSION=1.5
> [   0.051][v][vo/gpu/opengl] EGL_VENDOR=NVIDIA
> [   0.051][v][vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL_ES OpenGL
> [   0.051][v][vo/gpu/opengl] Trying to create Desktop OpenGL context.
> [   0.051][d][vo/gpu/opengl] Chosen EGLConfig:
> [   0.051][d][vo/gpu/opengl]   EGL_CONFIG_ID=40
> [   0.051][d][vo/gpu/opengl]   EGL_RED_SIZE=8
> [   0.051][d][vo/gpu/opengl]   EGL_GREEN_SIZE=8
> [   0.051][d][vo/gpu/opengl]   EGL_BLUE_SIZE=8
> [   0.051][d][vo/gpu/opengl]   EGL_ALPHA_SIZE=0
> [   0.051][d][vo/gpu/opengl]   EGL_COLOR_BUFFER_TYPE=12430
> [   0.051][d][vo/gpu/opengl]   EGL_CONFIG_CAVEAT=12344
> [   0.051][d][vo/gpu/opengl]   EGL_CONFORMANT=77
> [   0.065][v][vo/gpu/opengl] Choosing visual EGL config 0x28, visual ID 0x2b
> [   0.128][v][vo/gpu/opengl] GL_VERSION='4.4.0 NVIDIA 435.21'
> [   0.128][v][vo/gpu/opengl] Detected desktop OpenGL 4.4.
> [   0.128][v][vo/gpu/opengl] GL_VENDOR='NVIDIA Corporation'
> [   0.128][v][vo/gpu/opengl] GL_RENDERER='GeForce GTX 750 Ti/PCIe/SSE2'
> [   0.128][v][vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.40 NVIDIA via Cg compiler'
> [   0.128][d][vo/gpu/opengl] Combined OpenGL extensions string:
> [   0.128][d][vo/gpu/opengl] EGL_EXT_buffer_age EGL_EXT_client_sync EGL_EXT_create_context_robustness EGL_EXT_output_base EGL_EXT_stream_acquire_mode EGL_EXT_sync_reuse EGL_IMG_context_priority EGL_KHR_config_attribs EGL_KHR_create_context_no_error EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_display_reference EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_partial_update EGL_KHR_swap_buffers_with_damage EGL_KHR_no_config_context EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_reusable_sync EGL_KHR_stream EGL_KHR_stream_attrib EGL_KHR_stream_consumer_gltexture EGL_KHR_stream_cross_process_fd EGL_KHR_stream_fifo EGL_KHR_stream_producer_eglsurface EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_NV_nvrm_fence_sync EGL_NV_post_sub_buffer EGL_NV_quadruple_buffer EGL_NV_stream_cross_display EGL_NV_stream_cross_object EGL_NV_stream_cross_process EGL_NV_stream_cross_system EGL_NV_stream_dma EGL_NV_stream_flush EGL_NV_stream_metadata EGL_NV_stream_remote EGL_NV_stream_reset EGL_NV_stream_socket EGL_NV_stream_socket_inet EGL_NV_stream_socket_unix EGL_NV_stream_sync EGL_NV_stream_fifo_next EGL_NV_stream_fifo_synchronous EGL_NV_stream_consumer_gltexture_yuv EGL_NV_stream_attrib EGL_NV_stream_origin EGL_NV_system_time EGL_NV_output_drm_flip_event EGL_NV_triple_buffer GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_EGL_image_storage GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_multiview_texture_multisample GL_EXT_multiview_timer_query GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_NV_robustness_video_memory_purge GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_shader_subgroup GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_subgroup_partitioned GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NV_gpu_multicast GL_NVX_progress_fence GL_NVX_gpu_memory_info GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum
> [   0.131][d][vo/gpu/opengl] Texture formats:
> ```
> 
> win4ktest.txt
> ```
> [   0.026][v][vo/gpu] Probing for best GPU context.
> [   0.026][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
> [   0.081][v][vo/gpu/d3d11] Using Direct3D 11 feature level 11_0
> [   0.081][v][vo/gpu/d3d11] Device Name: NVIDIA GeForce GTX 750 Ti
> [   0.081][v][vo/gpu/d3d11] Device ID: 10de:1380 (rev a2)
> [   0.081][v][vo/gpu/d3d11] Subsystem ID: 19da:288a
> [   0.081][v][vo/gpu/d3d11] LUID: 000000000000a34e
> [   0.081][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
> [   0.081][v][vo/gpu/d3d11] Using Direct3D 11.1 runtime
> [   0.081][v][vo/gpu/d3d11] Maximum Texture2D size: 16384x16384
> [   0.082][v][vo/gpu/d3d11] D3DCompiler version: 10.0.18362.1
> [   0.100][v][vo/gpu/d3d11] Using DXGI 1.2+
> [   0.100][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 1920x1080 @ 8 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)
> [   0.100][v][vo/gpu/d3d11] Selected swapchain format R8G8B8A8_UNORM (28), attempting to utilize it.
> [   0.102][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G22_NONE_P709 (0), attempting to utilize it.
> [   0.102][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G22_NONE_P709 (0): normal: yes, overlay: no
> [   0.102][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G22_NONE_P709 (0)!
> [   0.102][v][vo/gpu/d3d11] Using flip-model presentation
> [   0.102][d][vo/gpu/d3d11] Texture formats:
> ```
> 
> P.S: There is no reliable way to make comparisons between Windows and Linux drivers without the use of hardware acceleration.

thnx bro for pointing it out... i ll upload the logs of lossless vs lossless and lossy vs lossy...

**Comment by aufkrawall** [comment]
You can also just look into the OSD (shift + i) and very likely see the decoder dropping frames. If there are any differences between platforms, it should be due to how ffmpeg is compiled (and thus not be an mpv issue).

**Comment by msshaikh1717** [comment]
> > [lin4ktest.txt](https://github.com/mpv-player/mpv/files/4949108/lin4ktest.txt)
> > [win4ktest.txt](https://github.com/mpv-player/mpv/files/4949109/win4ktest.txt)
> 
> Lossless vs. lossy? A very fair comparison...
> Why not lossless (opengl/vulkan) vs. lossless (opengl/vulkan) or lossy (direct3d) vs. lossy (xv)?
> 
> lin4ktest.txt
> 
> ```
> [   0.042][v][vo/gpu] Probing for best GPU context.
> [   0.042][v][vo/gpu/opengl] Initializing GPU context 'wayland'
> [   0.042][v][vo/gpu/opengl] Initializing GPU context 'x11egl'
> [   0.042][v][vo/gpu/x11] X11 opening display: :0.0
> [   0.045][d][vo/gpu/x11] X11 running at 1920x1080 (":0.0" => local display)
> [   0.045][d][vo/gpu/x11] Detected wm supports NetWM.
> [   0.045][d][vo/gpu/x11] Detected wm supports ABOVE state.
> [   0.045][d][vo/gpu/x11] Detected wm supports BELOW state.
> [   0.045][d][vo/gpu/x11] Detected wm supports FULLSCREEN state.
> [   0.045][v][vo/gpu/x11] Display 0 (DVI-I-0): [0, 0, 1920, 1080] @ 60.000000 FPS
> [   0.045][v][vo/gpu/x11] Current display FPS: 60.000000
> [   0.051][v][vo/gpu/opengl] EGL_VERSION=1.5
> [   0.051][v][vo/gpu/opengl] EGL_VENDOR=NVIDIA
> [   0.051][v][vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL_ES OpenGL
> [   0.051][v][vo/gpu/opengl] Trying to create Desktop OpenGL context.
> [   0.051][d][vo/gpu/opengl] Chosen EGLConfig:
> [   0.051][d][vo/gpu/opengl]   EGL_CONFIG_ID=40
> [   0.051][d][vo/gpu/opengl]   EGL_RED_SIZE=8
> [   0.051][d][vo/gpu/opengl]   EGL_GREEN_SIZE=8
> [   0.051][d][vo/gpu/opengl]   EGL_BLUE_SIZE=8
> [   0.051][d][vo/gpu/opengl]   EGL_ALPHA_SIZE=0
> [   0.051][d][vo/gpu/opengl]   EGL_COLOR_BUFFER_TYPE=12430
> [   0.051][d][vo/gpu/opengl]   EGL_CONFIG_CAVEAT=12344
> [   0.051][d][vo/gpu/opengl]   EGL_CONFORMANT=77
> [   0.065][v][vo/gpu/opengl] Choosing visual EGL config 0x28, visual ID 0x2b
> [   0.128][v][vo/gpu/opengl] GL_VERSION='4.4.0 NVIDIA 435.21'
> [   0.128][v][vo/gpu/opengl] Detected desktop OpenGL 4.4.
> [   0.128][v][vo/gpu/opengl] GL_VENDOR='NVIDIA Corporation'
> [   0.128][v][vo/gpu/opengl] GL_RENDERER='GeForce GTX 750 Ti/PCIe/SSE2'
> [   0.128][v][vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.40 NVIDIA via Cg compiler'
> [   0.128][d][vo/gpu/opengl] Combined OpenGL extensions string:
> [   0.128][d][vo/gpu/opengl] EGL_EXT_buffer_age EGL_EXT_client_sync EGL_EXT_create_context_robustness EGL_EXT_output_base EGL_EXT_stream_acquire_mode EGL_EXT_sync_reuse EGL_IMG_context_priority EGL_KHR_config_attribs EGL_KHR_create_context_no_error EGL_KHR_context_flush_control EGL_KHR_create_context EGL_KHR_display_reference EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_partial_update EGL_KHR_swap_buffers_with_damage EGL_KHR_no_config_context EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_reusable_sync EGL_KHR_stream EGL_KHR_stream_attrib EGL_KHR_stream_consumer_gltexture EGL_KHR_stream_cross_process_fd EGL_KHR_stream_fifo EGL_KHR_stream_producer_eglsurface EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_NV_nvrm_fence_sync EGL_NV_post_sub_buffer EGL_NV_quadruple_buffer EGL_NV_stream_cross_display EGL_NV_stream_cross_object EGL_NV_stream_cross_process EGL_NV_stream_cross_system EGL_NV_stream_dma EGL_NV_stream_flush EGL_NV_stream_metadata EGL_NV_stream_remote EGL_NV_stream_reset EGL_NV_stream_socket EGL_NV_stream_socket_inet EGL_NV_stream_socket_unix EGL_NV_stream_sync EGL_NV_stream_fifo_next EGL_NV_stream_fifo_synchronous EGL_NV_stream_consumer_gltexture_yuv EGL_NV_stream_attrib EGL_NV_stream_origin EGL_NV_system_time EGL_NV_output_drm_flip_event EGL_NV_triple_buffer GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_EGL_image_storage GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_multiview_texture_multisample GL_EXT_multiview_timer_query GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_formatted GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_NV_robustness_video_memory_purge GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_EXT_semaphore GL_EXT_semaphore_fd GL_KHR_shader_subgroup GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_equation_advanced_coherent GL_NV_blend_minmax_factor GL_NV_blend_square GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_feature_query GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_point_sprite GL_NV_primitive_restart GL_NV_query_resource GL_NV_query_resource_tag GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_atomic_int64 GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_shader_subgroup_partitioned GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_rectangle_compressed GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NV_gpu_multicast GL_NVX_progress_fence GL_NVX_gpu_memory_info GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_OVR_multiview GL_OVR_multiview2 GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum
> [   0.131][d][vo/gpu/opengl] Texture formats:
> ```
> 
> win4ktest.txt
> 
> ```
> [   0.026][v][vo/gpu] Probing for best GPU context.
> [   0.026][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
> [   0.081][v][vo/gpu/d3d11] Using Direct3D 11 feature level 11_0
> [   0.081][v][vo/gpu/d3d11] Device Name: NVIDIA GeForce GTX 750 Ti
> [   0.081][v][vo/gpu/d3d11] Device ID: 10de:1380 (rev a2)
> [   0.081][v][vo/gpu/d3d11] Subsystem ID: 19da:288a
> [   0.081][v][vo/gpu/d3d11] LUID: 000000000000a34e
> [   0.081][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
> [   0.081][v][vo/gpu/d3d11] Using Direct3D 11.1 runtime
> [   0.081][v][vo/gpu/d3d11] Maximum Texture2D size: 16384x16384
> [   0.082][v][vo/gpu/d3d11] D3DCompiler version: 10.0.18362.1
> [   0.100][v][vo/gpu/d3d11] Using DXGI 1.2+
> [   0.100][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY1, 1920x1080 @ 8 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)
> [   0.100][v][vo/gpu/d3d11] Selected swapchain format R8G8B8A8_UNORM (28), attempting to utilize it.
> [   0.102][v][vo/gpu/d3d11] Selected swapchain color space RGB_FULL_G22_NONE_P709 (0), attempting to utilize it.
> [   0.102][v][vo/gpu/d3d11] Swapchain capabilities for color space RGB_FULL_G22_NONE_P709 (0): normal: yes, overlay: no
> [   0.102][v][vo/gpu/d3d11] Swapchain successfully configured to color space RGB_FULL_G22_NONE_P709 (0)!
> [   0.102][v][vo/gpu/d3d11] Using flip-model presentation
> [   0.102][d][vo/gpu/d3d11] Texture formats:
> ```
> 
> P.S: There is no reliable way to make comparisons between Windows and Linux drivers without the use of hardware acceleration.
Here are the logs
[win-opengl.txt](https://github.com/mpv-player/mpv/files/4953312/win-opengl.txt)
[linux-xv.txt](https://github.com/mpv-player/mpv/files/4953313/linux-xv.txt)
