### ISSUE TITLE
Microstutters with Vulkan on Nvidia with interpolation

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#6738]
### mpv version and platform

Platform: GNU/Linux 64bit
Nvidia Drivers: 430.14
GPU: 1070 Ti

```$ mpv --version
mpv 0.29.0-329-g64cdc3694e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.27.100
   libavcodec      58.52.101
   libavformat     58.27.103
   libswscale      5.4.101
   libavfilter     7.51.100
   libswresample   3.4.100
ffmpeg version: N-93846-gbd6942b4c0
```
Libplacebo version: v1.18.0.13.g02c0219-1

### Reproduction steps

```
mpv --no-config --gpu-api=vulkan --interpolation --video-sync=display-resample
```
### Expected behavior

Smooth playback

### Actual behavior

Tiny stutters in the form of mistimed/dropped frames in display sync and dropped frames in VO. 
This does not happen with `gpu-api=opengl`.  

### Log file
Vulkan logfile created with 
```
mpv --gpu-api=vulkan --log-file=vulkan.log --msg-level=vo=trace ~/Videos/iceland2160p.webm --end=30 --no-config --fullscreen --interpolation --video-sync=display-resample
```
https://0x0.st/zaKd.log

OpenGL log created with 
```
mpv --gpu-api=opengl --log-file=opengl.log --msg-level=vo=trace ~/Videos/iceland2160p.webm --end=30 --no-config --fullscreen --interpolation --video-sync=display-resample
```
https://0x0.st/zaKn.log

### Sample files

I do not think the video matters, I have been noticing this for a while now. However 60 fps content (and being in fullscreen) makes it a lot more noticeable. This is the source of the video I used in my testing  (at 4k60 fps vp9): https://www.youtube.com/watch?v=ppy_gjBp71E. It's too large to upload but `youtube-dl -f 308+141` is the format for the exact streams I have.

I'm guessing this is a driver bug but I have no idea.

**Comment by philipl** [comment]
I happened to discover, when trying out interpolation with nvidia/vulkan that the nvidia driver busy waits when doing `vk_poll_commands` which is needed to ensure buffers have finished being used before being discarded, which ends up being necessary during interpolation. I can't remember the exact sequence of steps that gets us here.

I would bet this is either directly the cause of the problem or a contributing factor. It creates a significant amount of CPU load, especially at 4k60.

**Comment by LaserEyess** [comment]
I can recreate that behavior, so almost certainly a driver bug.

**Comment by LaserEyess** [comment]
This may not be a driver bug after all, with [this patch](https://0x0.st/zaMG.txt) I can fix the CPU spiking but the stuttering still remains.

**Comment by aufkrawall** [comment]
Likely still #6172 , Nvidia apparently doesn't care.

**Comment by philipl** [comment]
Doh. That’s where all the info was. No wonder I couldn’t find it in irc logs.

**Comment by LaserEyess** [comment]
@aufkrawall that particular issue was solved with the patch I posted, it's unrelated to the stuttering I'm getting.

**Comment by LaserEyess** [comment]
I don't seem to get this anymore. Still drops one or two frames with a weird stutters sometimes, but I can't really tell a difference between vulkan and openGL.

**Comment by Lamieur** [comment]
This is definitely still a problem.

After you've closed this, for a brief time Vulkan didn't work at all so I couldn't test, but now that it's working again (git from 2019-10-11), Vulkan backend is still choppy as hell while OpenGL still works perfectly fine.

And contrary to issue title, this happens _without_ interpolation. I do use video-sync=display-resample though.

I watch with the TV's motion smoothing cranked up to 11, so even a single dropped frame on an otherwise smooth video is visible even to an untrained eye, but having them every second (!) is infuriating.

Yes, every second. The video you tested in the OP shows by the end:
AV: 00:03:01 / 00:03:01 (99%) A-V:  0.000 DS: 1.000/373 Dropped: 187 Cache: 0.0s
So actually over 1 drop per second! They're very frequent, make the video super juddery and super frustrating to watch. So here I'd say it's happening "constantly", not "sometimes" :)

(OpenGL dropps exactly 0 frames to play the whole thing)

BTW LaserEyess, my TV thanks you for saving its life - I totally wanted to send it back thinking the judders were its fault, but I found this bug report and turns out gpu-api=opengl fixes the issue. I'd never think of testing that without you, thanks a lot! :)

**Comment by LaserEyess** [comment]
@Lamieur to be honest I was long looking at the visual effects of stuttering, instead of the actual amount of dropped frames. I don't get a dropped frame once every second, more like once every 10 seconds, but you are right, there's still an enormous difference between openGL and vulkan, so I guess that warrants an issue. I don't really know if that should be the same issue or a new one, because I get much smoother playback with vulkan now, even if it isn't as good as openGL.
