### ISSUE TITLE
mpv starts playing videos then hangs two seconds and crashes when using SVP (works on some other videos)

### ISSUE THREAD

**Issue by Kabouik** [mpv-player/mpv#7016]
### mpv version and platform

Platform: Linux, Manjaro
mpv version: mpv-git installed using AUR and mpv standalone built using [mpv-build](https://github.com/mpv-player/mpv-build)

### Reproduction steps
I have not yet identified how to discriminate videos that play successfully in mpv + vapoursynth + SVP from those that crash mpv. But videos that fail will always fail, and those that work will always work. It is not related to resolution or file size.

### Expected behavior
No crash.

### Actual behavior
Crash on some files.

### Log file
See log files posted after [this post](https://github.com/mpv-player/mpv/issues/3432#issuecomment-536116258) in #3432 

### Sample files
The files are not free licence and are quite large, but maybe I can provide them using a private communication channel, like IRC?

**Comment by Kabouik** [comment]
An interesting thread on SVP forum mentioned by @bobby: https://www.svp-team.com/forum/viewtopic.php?id=5422. However, I am not having the `(!!!) Intermediate file may be broken:` error the person is having in the SVP forum thread.

**Comment by BobbyWibowo** [comment]
@Kabouik Does your mpv exit with the error right when a playback finish as well btw? (like @v-fox, but without the JACK freezes thingy). In my end, even if the entire video played just fine, at the end of the playback mpv would still exit with the error.
When using SMPlayer with mpv back-end, playlist became unable to continue to the next file properly cause SMPlayer didn't like it when mpv exited with an error.

Other than that, I noticed that toggling options (such as "Temporarily disable SVP", or the Film/Animation optimization mode) during playback would cause mpv to crash immediately.

I also noticed that on some files it'd crash much earlier when I turned on SVP's "Detect and cut off black bars", though only when playing on full screen.

---

Likely unrelated, but I'll be spammed with `[vo/gpu] Format bgra8 not supported.` when using mpv + SVP with mpv options: `--gpu-context=x11vk --gpu-api=vulkan`, but I believe I never got this issue a few months back.

**Comment by wm4** [comment]
I'll try tomorrow with the open source stuff (https://gist.github.com/v-fox/43c287426c366679afc4c65eece60cbc), if I get it to work.

In the meantime, people might try to revert the commit mentioned here: https://github.com/mpv-player/mpv/issues/3432#issuecomment-537633173

Report that vulkan thing as separate issue.

**Comment by olifre** [comment]
I can also reproduce using the open source mvtools stuff, and with SVP on my end. 
I'm not that much into that code, but `gdb` traced it to the destruction of the `file` property of `vf_vapoursynth`. Hence, changing:
https://github.com/mpv-player/mpv/blob/f203a881e56e34e6d403a2091bd3dfec9a6c38ce/video/filter/vf_vapoursynth.c#L767
to:
```
p->opts->file = mp_get_user_path(NULL, f->global, p->opts->file);
```
also seems to hide the issue for me, without reverting the mentioned commit. Maybe that helps in tracking it down?

**Comment by wm4** [comment]
Pushed a view commits. Not sure if this is better, I couldn't get a simple VS script to work.

The things @olifre and @v-fox pointed out were quite right.

**Comment by v-fox** [comment]
> Pushed a view commits. Not sure if this is better, I couldn't get a simple VS script to work.
> 
> The things @olifre and @v-fox pointed out were quite right.

@wm4 Thanks ! This issue seems to be fixed.
The other ta.c crash came up with this update that seem to happen because mpv started trying to use 'waylandvk' gpu-context under X instead of 'x11vk', so forcing it manually avoids it but you probably already know about that.

Regarding mvtools scripts: for some reason mvtools only works reliably if 'concurrent-frames' are at least 8, ideally, somewhere around 16, even though it supposed to use only 3 at a time. Strangely, amount of 'buffered-frames' does not seem to affect it.

**Comment by wm4** [comment]
Report all bugs separately.

I guess that fixes this one? It's not clear, because people reported problems that have nothing to do with what I fixed.

**Comment by Kabouik** [comment]
I have not tried the commit yet but I'll check as soon as possible too and report back here.

**Comment by v-fox** [comment]
> Report all bugs separately.
> 
> I guess that fixes this one? It's not clear, because people reported problems that have nothing to do with what I fixed.

@wm4 Indeed. At least for my case of crashes on shutdown.

I thought that the vulkan thing was just a slip-up that will be soon address by author of whatever changes that caused it, so it's either already in the works or https://github.com/mpv-player/mpv/commit/defc8f359c5e4bb666e8ad1d4a097a8ac66cc1e2 addressed it, but, it seems, not yet.

And concerning VS's concurrent-frames weirdness: I'm not sure if that's intended by design or not.

**Comment by wm4** [comment]
Well seems rather unlikely that it fixes the other issues, but make new issues for that.

**Comment by olifre** [comment]
@wm4 To clarify after all those comments dealing with different issues: Yes, the issue is fixed, also filter unload and reload works now again without a crash. 
Also, many thanks for the commit message explaining the double-free - I also prefer your take on fixing this :smile:.

**Comment by Kabouik** [comment]
I can confirm that it works perfectly on all videos now. It is flawless, and enabling/disabling SVP filters during playback works too whereas it did trigger a crash all the time before, as mentioned by @olifre.

Thank you very much for this quick fix, I would never have expected this issue to be resolved this soon. Now I can enjoy interpolated videos with my family without having to go through the usual "Wait 10 more minutes until I fox it, and no we don't want the 24 fps version, I swear it works usually". :]

**Comment by wm4** [comment]
It shouldn't have fixed the mid-playback crash that the issue description mentions. That one probably still exists.

**Comment by Kabouik** [comment]
Weird, because it was a 100% failure when enabling/disabling during playback before, and yesterday I tried again after the commit and could not reproduce it.

**Comment by wm4** [comment]
Yeah, if it's enabled/disabled during playback, this makes sense. Not sure what these "2 secoconds" of hang are supposed to be then, though.
