### ISSUE TITLE
mpv on kde fullscreen transition bug

### ISSUE THREAD

**Issue by Sojiro84** [mpv-player/mpv#8652]
### Important Information

Provide following Information:
- mpv version: mpv 1:0.33.0-4
- Linux Distribution and Version: Arch KDE
- Source of the mpv binary: Arch repo
- Window Manager and version: kwin - 5.21.2-1
- GPU driver and version: mesa - 20.3.4-3

### Reproduction steps

Use KDE, play a video, and go full-screen. It will be instant and without the full-screen animation.

Important info: this bug only happens when you launch mpv. So it seems that on initial creation of the window, something goes wrong. If I move the window on the screen first, before going full-screen, there will be a full-screen transition animation. But if I leave the window as is, going full-screen is instant, but after that, the transition animation will always play, until I start a new instance of mpv and then it is as described earlier.

I reported this first on KDE, but they checked and forwarded me to here since the bug is in mpv (and that is true, I checked with smplayer and mplayer and they do work correctly).

### Expected behavior

I expected a full-screen transition animation.

### Actual behavior

mpv went fullscreen instantly, skipping the animation.

### Log file

https://gist.githubusercontent.com/Sojiro84/517efe43c4821ea902cc73de692684e2/raw/685bf193c3df844d29cf6a7f3a259de389c22477/gistfile1.txt

**Comment by CounterPillow** [comment]
This is likely because you enable applications to bypass the compositor, and kwin recently fixed that to actually work in kwin 5.21.0. Try `--x11-bypass-compositor=no`, this should fix it for you.

**Comment by Sojiro84** [comment]
> This is likely because you enable applications to bypass the compositor, and kwin recently fixed that to actually work in kwin 5.21.0. Try `--x11-bypass-compositor=no`, this should fix it for you.

Do I use the command as follows?: mpv --x11-bypass-compositor=no video.mp4 or mpv video.mp4 --x11-bypass-compositor=no ?

I tried both but issue still remains. I have set a option in system settings > compositor 'allow apps to block compositing' to unchecked. So compositing is always enabled.

If you are right, it is kind of strange that it only happens the first time going full-screen, after that first time, the animation is always there.

**Comment by CounterPillow** [comment]
`mpv --x11-bypass-compositor=no video.mp4` should work. As should unchecking compositing bypass. Are you sure your compositor is even enabled? (Shift+Alt+F12)

Either way, if you tell mpv not to bypass the compositor but kwin somehow still skips the animation then it's not an mpv issue but a kwin one.

**Comment by Sojiro84** [comment]
> `mpv --x11-bypass-compositor=no video.mp4` should work. As should unchecking compositing bypass. Are you sure your compositor is even enabled? (Shift+Alt+F12)
> 
> Either way, if you tell mpv not to bypass the compositor but kwin somehow still skips the animation then it's not an mpv issue but a kwin one.
> 
> You should also try setting Latency to either "Balance of Latency and Smoothness" or "Prefer Smoother Animations" in the compositor settings.

I have done all that. Compositor is always on. And the animation does work, but not the very first time (on initial window creation). I have to go full-screen once, and after that it works correctly OR I move the window around first and then going full-screen also work.

But on initial window creation it does not work.

I reported it to KDE first as a bug and they checked it and they said it was a mpv bug and that I should report it here.

https://bugs.kde.org/show_bug.cgi?id=434281

**Comment by CounterPillow** [comment]
It would be helpful if Nate Graham specified which default is being overridden.

**Comment by Sojiro84** [comment]
> It would be helpful if Nate Graham specified which default is being overridden.

I asked him if he could clarify which.
