### ISSUE TITLE
Pipewire causing unstable vsync ratio and mistimed/dropped frames with video-sync=display-resample?

### ISSUE THREAD

**Issue by DonKatsu** [mpv-player/mpv#8839]
### Important Information

Provide following Information:
- mpv version: 0.33.1
- Linux Distribution and Version: Fedora 34 KDE (clean install, not upgraded from 33)
- Source of the mpv binary: rpmfusion free
- Window Manager and version: kwin 5.21.5 (using X11)
- GPU driver and version: Mesa 21.0.3 (R9 280 with amdgpu.si_support=1 boot flag)

### Reproduction steps

With --no-config, the only thing that stands out in stats is with 60 fps videos, where it drops a frame every 10 seconds or so.
With --no-config --ao-sdl, 60 fps videos stop dropping frames entirely.

video-sync=display-resample is where it gets more visible.
Regardless of the video's framerate, vsync ratio will constantly fluctuate by +/- 0.020 from the expected value. A mistimed shows up on DS every few seconds. 60 fps videos continue to drop an output frame roughly every 10 seconds as well.
ao=alsa causes vsync ratio to fluctuate much more rapidly, and dropped/mistimed to build up much quicker. 50+ dropped on 60 fps in 10 seconds for example. Even 24 fps videos will start dropping frames.
Disabling the audio track prevents any of the above from happening, but I think that's expected?

Using ao=sdl or jack with video-sync=display-resample has vsync ratio stay stable, with no mistimed or dropped frames. Besides whatever mistimed initial playback incurs. Even 4k60 is fine, besides the odd delayed frame.

The only modification I've done with Pipewire has been setting api.alsa.headroom to 1024. Reverting this didn't have any effect.

One other somewhat unrelated Pipewire Pulse oddity is that starting anything with the paused option, letting it sit for a few seconds, then starting playback causes audio to not play. Stats still shows the audio bitrate changing. Pausing/playing or seeking fixes it. I think I did this in at least one of the pulse logs.
This doesn't seem to happen with actual Pulseaudio.

I tried a liveusb of Fedora 33 KDE since I'd rather not try replacing Pipewire with actual Pulseaudio at the moment. But it's not quite a valid comparison since I can't really update it.
ao=pulse with video-sync=display-resample worked perfectly. Stable vsync ratio, no dropped frames or mistimed past the start of playback.
ao=alsa with video-sync=display-resample still piles on mistimed and dropped frames, and has the worse fluctuating vsync ratio. Is that just normal then?

Then I tried Fedora 34 KDE's liveusb to see if the version of Pipewire there was any different. The first try, it seemed to be fine on pulse. Pipewire 0.3.25 packages, instead of the 0.3.27 I'm on now.
Updating installed Pipewire packages to 0.3.27 and restarting the services, which it didn't want me to do without restarting the daemon service but couldn't, and the problem showed up.
After restarting multiple times trying it again, it just kept doing what I'm experiencing on my install. Not sure why the first time worked.

Apologies in advance for likely going overboard. I'm not entirely sure where I should be reporting this, should I report to Pipewire as well?
Or am I overlooking something? I can't seem to find anything matching what I'm experiencing.

### Expected behavior
Normal playback without undue mistimed or dropped frames on pulse.
### Actual behavior
Playback with mistimed and dropped frames on pulse.
### Log file

[24fps no-config.log](https://github.com/mpv-player/mpv/files/6497404/24fps.no-config.log)
[60fps no-config.log](https://github.com/mpv-player/mpv/files/6497405/60fps.no-config.log)

[24fps pulse.log](https://github.com/mpv-player/mpv/files/6497119/24fps.pulse.log)
[24fps alsa severe.log](https://github.com/mpv-player/mpv/files/6497122/24fps.alsa.severe.log)
[24fps jack.log](https://github.com/mpv-player/mpv/files/6497123/24fps.jack.log)
[24fps sdl.log](https://github.com/mpv-player/mpv/files/6497124/24fps.sdl.log)

[60fps pulse.log](https://github.com/mpv-player/mpv/files/6497126/60fps.pulse.log)
[60fps alsa severe.log](https://github.com/mpv-player/mpv/files/6497125/60fps.alsa.severe.log)
[60fps jack.log](https://github.com/mpv-player/mpv/files/6497127/60fps.jack.log)
[60fps sdl.log](https://github.com/mpv-player/mpv/files/6497128/60fps.sdl.log)

[24fps pulse liveusb.log](https://github.com/mpv-player/mpv/files/6498372/24fps.pulse.liveusb.log)
[60fps pulse liveusb.log](https://github.com/mpv-player/mpv/files/6498378/60fps.pulse.liveusb.log)

**Comment by CounterPillow** [comment]
>  Disabling the audio track prevents any of the above from happening, but I think that's expected?

Yes, it falls back to the monotonic system clock for timing in that case.

Ok, this is a lot of info, I'll try to dig through it a bit for other developers.

> ao=alsa causes vsync ratio to fluctuate much more rapidly, and dropped/mistimed to build up much quicker.

I've just checked and this uses `ALSA <-> PipeWire PCM I/O Plugin`, so we can't blame the hardware, we can only blame PipeWire so far.

> One other somewhat unrelated Pipewire Pulse oddity is that starting anything with the paused option, letting it sit for a few seconds, then starting playback causes audio to not play.

This sounds like it's worthy of a separate issue.

> Then I tried Fedora 34 KDE's liveusb to see if the version of Pipewire there was any different. The first try, it seemed to be fine on pulse. Pipewire 0.3.25 packages, instead of the 0.3.27 I'm on now.
Updating installed Pipewire packages to 0.3.27 and restarting the services, which it didn't want me to do without restarting the daemon service but couldn't, and the problem showed up.
After restarting multiple times trying it again, it just kept doing what I'm experiencing on my install. Not sure why the first time worked.

I'm not 100% sure whether this means that 0.3.25 was fine or whether 0.3.25 ended up being broken too ("After restarting multiple times"), but if it's the former then it's definitely a pipewire regression.

So far this all points towards a pipewire bug, and not an mpv bug. Even if it's a bug with how mpv uses pulse that makes pipewire behave erratically, reporting it to the pipewire devs seems like a good choice because they'd be more familiar with what pipewire expects mpv to do.

From our side, it seems like all AOs roughly pick the same thing. Especially in the liveusb vs noconfig case, you can see that when it initialises the AO there's virtually no difference in what it chose. So I don't think it's any misconfiguration, but if it is a problem on our side, then something relating to how we use the pulse API.

Thank you for your work putting together all this data, this is way above and beyond what most users do and I genuinely appreciate it.

**Comment by DonKatsu** [comment]
> I'm not 100% sure whether this means that 0.3.25 was fine or whether 0.3.25 ended up being broken too ("After restarting multiple times")

The latter, yeah. It was a pretty messy experience though since it boots straight into wayland, and logging out of kwin wayland is temperamental at best on the version it's at in that image. I was restarting to try again fresh instead of trying to downgrade anything. Really not sure why it only worked the first time with 0.3.25. I tried three more times after that. It's something to keep in mind I guess.

I'll be opening an issue on Pipewire's side as well then.

**Comment by OldAVman** [comment]
First time on here so apologies in advance if I get anything wrong! I've been using mpv for quite a while as the player engine  in my  htpc box. As I don't want any audio mixing/resampling going on I don't use either Pulseaudio or Pipewire and only use alsa directly.
After upgrading from Fedora 32 to 33 I started to notice pretty much what your describing. The vsync jitter on the status line increased from the usual 0 +/-1 to at least +/-20mS. I tracked this down to a change in alsa-lib from 1.2.3.2-5 to 1.2.4. Reverting this 'upgrade' cured the problem in my case. I doubt if the problem is in mpv as I tried reverting to an older version and the jitter still occurred when using the new alsa-lib. I'm still investigating to try and find the change in alsa which causes the problem. Apologies if this is not relevant to your case but the symptoms sound similar.

**Comment by DonKatsu** [comment]
> I tracked this down to a change in alsa-lib from 1.2.3.2-5 to 1.2.4.
Interesting. Unfortunately, Fedora's 34 repo only has 1.2.4 and 33's live version comes with 1.2.3.2. And I'm not sure how to get just alsa running on a live environment.
But then there's still how I experience it with alsa-lib 1.2.3.2 ran through ALSA <-> PulseAudio PCM I/O plugin on F33 KDE live.

**Comment by OldAVman** [comment]
Not sure with a live version. With a normal version I simply remove Pulseaudio completely and the usual alsa controls appear in Alsamixer. I then specify ao=alsa and my chosen audio-device. I've just re-checked on two different computers with recent versions of mpv and ffmpeg both compiled from source and I get the same result on both: Using alsa-lib 1.2.3 everything works perfectly. Using alsa-lib 1.2.4 results in large amounts of sync jitter. This occurs with both video-sync=audio and video-sync=display-resample. You've probably got something else going on as well but for me the jitter seems to be definitely linked to alsa-lib. When I have time I'll try to see what changed between the two versions. Although I can currently solve my problem by using the older version it's not really a solution going forward.

**Comment by DonKatsu** [comment]
I got alsa-lib 1.2.5-2, and all issues with ao=alsa seem to have been fixed on my end. Just as stable as with sdl.

Still no change with ao=pulse, after 0.3.28-1 and 0.3.29-2.

**Comment by OldAVman** [comment]
Glad to hear it works for you. I'm still using the early version which works fine, but I'll try 1.2.5 for interest. I would have to say that even with the alsa-lib version that caused increased jitter for me, I wasn't seeing the same dropped frames problem as you. Having said that I'm mostly viewing 1080i and 720p TV streams which don't really stress the system very much.

**Comment by DonKatsu** [comment]
The pause option resulting in no sound upon playing problem with ao=pulse is caused by the `session.suspend-timeout-seconds` setting in `/usr/share/pipewire/alsa-monitor.conf`. Setting that to 0 resolves it.
Doesn't do anything for my dropped and mistimed frames though, so that's still from something else.

**Comment by notgood** [comment]
Same issue on Arch, mpv 0.34.1, pipewire 0.3.42, alsa-lib 1.2.6.1.

video-sync=display-resample is unusable outputing to pulse->pipewire, vsync ratio is fluctuating resulting delayed frames.

Changing audio output to alsa device results 100% stable vsync ration with no mistimed/dropped frames.

Any way to debug it and move this issue forward?

**Comment by jsravn** [comment]
Most likely a pipewire issue, so https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1200 although no response yet.

**Comment by notgood** [comment]
So far this issue didn't get much traction from pipewire devs, even though problem ir clearly repeatable..

But good news are that pulse compatibility layer can be avoided altogether, since native pipewire audio backend PR #9587 was merged into mpv master. According to my limited tests there are no mistimed/dropper frames when outputing audio directly to pipewire.

**Comment by Dudemanguy** [comment]
I'd say this is fixed by #9587. Compatibility layers can cause issues like this (I've experienced this with pulseaudio and alsa), so the best solution is to just use the actual ao.

**Comment by AtticFinder65536** [comment]
I still get many dropped frames when using `ao-pipewire`, but only with opengl (on sway). On vulkan it's fine (not sure if A-V in the terminal changing extremely rapidly by values less than 0.009 is supposed to happen, but the video looks completely fine). And it happens regardless of the ao. With `ao=pulse` and vulkan, display-resample plays great.

**Comment by cronyakatsuki** [comment]
I also get a lot of dropped and mistimmed frames with pipewire, except when using vulkan.
