### ISSUE TITLE
Saturation and hue have no effect when displaying image files

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#8914]
### Important Information

```
mpv 0.33.0-183-gdbbf4a415d Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Jun 12 12:21:34 CEST 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: n4.4
```
On arch linux. Reproducible with both pacakged mpv and built from git.
Using intel GPU with x11.

### Reproduction steps

Run `mpv --no-config --saturation=x --hue=y some_image.png`.
The output looks the same no matter the value of x or y.
Note that the issue does not occur with videos, only images. This does not affect brightness, contrast and gamma.

### Expected behavior

The hue and saturation value are applied.

### Actual behavior

The image is displayed, as if hue and saturation were set to 0.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/6642002/log.txt)

**Comment by haasn** [comment]
Fixed by #8799

**Comment by occivink** [comment]
Is it only fixed on vo_placebo? I've tried `vo=gpu` on this branch and the issue is still there

**Comment by occivink** [comment]
I've just noticed that this only occurs with png files, jpg seem ok.

**Comment by haasn** [comment]
> Is it only fixed on vo_placebo? I've tried `vo=gpu` on this branch and the issue is still there

Yeah, sorry for the lack of clarification - this works as intended under `--vo=gpu-next`.

**Comment by occivink** [comment]
Thanks for the clarification. It's still a little puzzling that the image format would matter

**Comment by haasn** [comment]
> Thanks for the clarification. It's still a little puzzling that the image format would matter

mpv mixes the hue/saturation math into the ycbcr->rgb decoding matrix, which is why they don't work for rgb formats
