### ISSUE TITLE
fontselect: failed to find any fallback for font

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#8919]
Hi, any help to fix the error:
**[osd/libass] fontselect: failed to find any fallback for font: (sans-serif, 400, 0)**
I changed font and I get the same error.

mpv 0.33
Windows 7 64 bits SP1

**Comment by CounterPillow** [comment]
> mpv 0.30

Why report this? Current version is 0.33.1. Recent (maybe even git) libass is preferred even for any issues relating to font fallback.

Also please do not use the question template for things that are not questions

**Comment by Robot-DaneelOlivaw** [comment]
It should have been fixed by https://github.com/libass/libass/pull/513.

**Comment by NOBLES5E** [comment]
Any workaround on lastest release version? This makes mpv unusable for me ...

**Comment by Akemi** [comment]
apparently this was fixed upstream. closing this issue since the issue template was ignored anyway.

**Comment by glubsy** [comment]
I'm doubtful this was actually fixed. Using mpv 0.34.0 and libass 0.15.2 (latest release) on Arch Linux, and I still get flooded by this error when playing a video that has emoticons in the title (the title is rendered on the OSD with missing glyph). 

The problem is not just the error messages: the video playback becomes very sluggish, probably less than 20 frames per second are rendered. If I edit the video file and remove the title, the frame rate is all good, and I don't get the flood of errors as shown below: 
```
[osd/libass] fontselect: failed to find any fallback with glyph 0x1F423 for font: (sans-serif, 400, 0)
[osd/libass] fontselect: failed to find any fallback with glyph 0x1F33E for font: (sans-serif, 400, 0)
```
Should I open a new ticket?

**Comment by liuxunfei** [comment]
这个问题怎么解决的，兄弟

**Comment by jimmy-1000** [comment]
> 这个问题怎么解决的，兄弟

I couldn't.

**Comment by jimmy-1000** [comment]
> 这个问题怎么解决的，兄弟

But I see the last version of mpv doesn't have that problem, it's fixed.

**Comment by jimmy-1000** [comment]
> I'm doubtful this was actually fixed. Using mpv 0.34.0 and libass 0.15.2 (latest release) on Arch Linux, and I still get flooded by this error when playing a video that has emoticons in the title (the title is rendered on the OSD with missing glyph).
> 
> The problem is not just the error messages: the video playback becomes very sluggish, probably less than 20 frames per second are rendered. If I edit the video file and remove the title, the frame rate is all good, and I don't get the flood of errors as shown below:
> 
> ```
> [osd/libass] fontselect: failed to find any fallback with glyph 0x1F423 for font: (sans-serif, 400, 0)
> [osd/libass] fontselect: failed to find any fallback with glyph 0x1F33E for font: (sans-serif, 400, 0)
> ```

Did you find any solution?

**Comment by glubsy** [comment]
No, but this is related to https://github.com/mpv-player/mpv/issues/8957, and as you can read it is tied to libass (https://github.com/libass/libass/issues/137, https://github.com/libass/libass/issues/381).

**Comment by troyBORG** [comment]
Can you tell us where to get the "Glyph" font it says we need?

**Comment by jimmy-1000** [comment]
> Can you tell us where to get the "Glyph" font it says we need?

In my case I never found a solution. I tried some emoji-fonts in my system but not worked

**Comment by garoto** [comment]
See if this hexchat docs entry helps: https://hexchat.readthedocs.io/en/latest/tips.html#special-glyphs

**Comment by christoph-heinrich** [comment]
Installing [Twitter Color Emoji](https://github.com/eosrei/twemoji-color-font) and creating `/etc/fonts/local.conf` with
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <alias>
     <family>sans-serif</family>
     <prefer>
       <family>Twitter Color Emoji</family>
     </prefer> 
   </alias>
</fontconfig>
```
fixed it for me. This works because the font only contains glyphs for emojis, effectively making my regular font the fallback. If you prefer the color emojis from a different emoji font, you can simply put a `<family>Other Emoji Font</family>` above the twitter one.

Note that this is system wide, for user specific configuration use `~/.config/fontconfig/fonts.conf` instead.

**Comment by jimmy-1000** [comment]
> Installing [Twitter Color Emoji](https://github.com/eosrei/twemoji-color-font) and creating `/etc/fonts/local.conf` with
> 
> ```
> <?xml version="1.0"?>
> <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
> <fontconfig>
>   <alias>
>      <family>sans-serif</family>
>      <prefer>
>        <family>Twitter Color Emoji</family>
>      </prefer> 
>    </alias>
> </fontconfig>
> ```
> 
> fixed it for me. This works because the font only contains glyphs for emojis, effectively making my regular font the fallback. If you prefer the color emojis from a different emoji font, you can simply put a `<family>Other Emoji Font</family>` above the twitter one.
> 
> Note that this is system wide, for user specific configuration use `~/.config/fontconfig/fonts.conf` instead.
> 
> Also I'm new to this whole font configuration thing, so I don't know if there is a better solution. So far I've not noticed any problems. Maybe adding `binding="weak"` to the alias tag might be preferred (based on [this](https://github.com/stove-panini/fontconfig-emoji/blob/master/old/69-emoji.conf)).

👍👍👍

**Comment by LampPrinter** [comment]
> fontconfig/fonts.conf

Not working for me on MacOS.
Installed Twitter Color Emoji through brew.

**Comment by dabcd** [comment]
I wanted to share the solution that worked for me on Linux:
1. Download Noto Emoji font from [here](https://fonts.google.com/noto/specimen/Noto+Emoji) - click on "Download family".
2. Extract file NotoEmoji-VariableFont_wght.ttf to your /home/{user}/.local/share/fonts/ directory (if the directory doesn't exist, create it).
3. Update the fonts cache: `fc-cache -f -v`. The output should contain: `/home/{user}/.local/share/fonts: caching, new cache contents: 4 fonts, 0 dirs`
4. Now `fc-list | grep Emoji` should list your new font: `/home/{user}/.local/share/fonts/NotoEmoji-VariableFont_wght.ttf: Noto Emoji
`
5. That's it. Steps 2-4 are from [this tutorial](https://www.unixtutorial.org/how-to-install-ttf-fonts-in-linux/). I have now black and white emojis in OSD without messing with config files.

**Comment by simurgh9** [comment]
@LampPrinter the file contents mentioned by @christoph-heinrich go in `$HOMEBREW_PREFIX/etc/fonts/local.conf` which should be `/opt/homebrew/etc/fonts/local.conf` as of my comment.

You can also run something like, `fc-conflist | grep "/fonts\.conf"` to find out where the configuration file for the fontconfig is. The `fonts.conf` recommends that you make a `local.conf` for your local configurations.

Anyways, I did all that and put ,

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<fontconfig>
  <alias>
     <family>sans-serif</family>
     <prefer>
       <family>Noto Emoji</family>
     </prefer> 
   </alias>
</fontconfig>
```

For [Noto Emoji](https://fonts.google.com/noto/specimen/Noto+Emoji) and nothing changed. Sign... The config file we made does get applied though. You can check by running `fc-match -s "sans-serif"`.

The flag `--osd-font` worked for me though,

~~~
mpv --osd-font="Noto Emoji" "https://www.youtube.com/watch?v=jfKfPfyJRdk"
~~~

But their it turns out, the Noto Emoji font was not a great one to pick due to spacing of the glyphs. I tried the [Symbola](https://github.com/ChiefMikeK/ttf-symbola) font.

~~~
mpv --osd-font="symbola" "https://www.youtube.com/watch?v=jfKfPfyJRdk"
~~~

Also, note that in order to install fonts on macOS, you can move the file files to `~/Library/Fonts/` and run `fc-cache -rvf`.

**Comment by dabcd** [comment]
@simurgh9 I tried to set Noto Emoji as an OSD font when I was looking for the solution some time ago, but it looked ugly. Currently I use the default mpv  and default system settings when it comes to the fonts (I use OpenSuse Linux).

It seems that when libass cannot find a suitable glyph within the default font, it picks that glyph from Nofo Emoji (because its monochrome). The libass adds the following line to the log for `mpv https://www.youtube.com/watch?v=jfKfPfyJRdk`:

```
[osd/libass] Glyph 0x1F4DA not found, broken font? Trying all charmaps
```

0x1F4DA being the "books" character. In the end the OSD text looks perfect, as attached.
Once again, all I've done was installing the Noto Emoji font, not even a config modification, but I'm on Linux.

![Screenshot_20230614_164951](https://github.com/mpv-player/mpv/assets/85885028/2c0f8024-e22d-4a46-88dd-aad4fcca0b47)

P.S. I run a debug command:
```
mpv --msg-level=osd=debug https://www.youtube.com/watch?v=jfKfPfyJRdk | grep osd
```

and got:
```
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/arial.ttf, 0, ArialMT
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[osd/libass] Glyph 0x1F4DA not found, selecting one more font for (sans-serif, 400, 0)
[osd/libass] fontselect: (sans-serif, 400, 0) -> /home/user/.local/share/fonts/NotoEmoji-VariableFont_wght.ttf, 0, NotoEmoji-Regular
[osd/libass] Glyph 0x1F4DA not found, broken font? Trying all charmaps
```

**Comment by simurgh9** [comment]
@dabcd I am on Ventura 13.4 Macbook Air. I have Noto Emoji installed.

```shell
$ fc-list | grep --color "Noto Emoji"
/Users/tfn/Library/Fonts/NotoEmoji.ttf: Noto Emoji:style=Light
/Users/tfn/Library/Fonts/NotoEmoji.ttf: Noto Emoji:style=Regular
/Users/tfn/Library/Fonts/NotoEmoji.ttf: Noto Emoji
/Users/tfn/Library/Fonts/NotoEmoji.ttf: Noto Emoji:style=Bold
```

I still get the,
```
[osd/libass] ASS library version: 0x1700000 (runtime 0x1700000)
[osd/libass] libass API version: 0x1700000
[osd/libass] libass source: tarball: 0.17.0
[osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 6.0.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider coretext
[osd/libass] Done.
[osd/libass] ASS library version: 0x1700000 (runtime 0x1700000)
[osd/libass] libass API version: 0x1700000
[osd/libass] libass source: tarball: 0.17.0
[osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 6.0.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider coretext
[osd/libass] Done.
AV: 00:00:02 / 00:00:14 (18%) A-V:  0.000 Cache: 11s/1MB
[osd/libass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[osd/libass] Glyph 0x1F4DA not found, selecting one more font for (sans-serif, 400, 0)
2023-06-14 14:57:20.950 mpv[980:12546] CoreText note: Client requested name ".LastResort", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
```

What is your `libass` version btw?

**Comment by dabcd** [comment]
@simurgh9 Sorry I cut the log, the complete one is here:
```
mpv --msg-level=osd=debug https://www.youtube.com/watch?v=jfKfPfyJRdk | grep osd
[osd/libass] ASS library version: 0x1701000 (runtime 0x1701000)
[osd/libass] libass API version: 0x1701000
[osd/libass] libass source: tarball: 0.17.1
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 3.4.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] ASS library version: 0x1701000 (runtime 0x1701000)
[osd/libass] libass API version: 0x1701000
[osd/libass] libass source: tarball: 0.17.1
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 3.4.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
AV: 00:00:01 / 00:00:14 (8%) A-V:  0.001 Cache: 13s/1MB
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/arial.ttf, 0, ArialMT
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[osd/libass] Glyph 0x1F4DA not found, selecting one more font for (sans-serif, 400, 0)
[osd/libass] fontselect: (sans-serif, 400, 0) -> /home/user/.local/share/fonts/NotoEmoji-VariableFont_wght.ttf, 0, NotoEmoji-Regular
[osd/libass] Glyph 0x1F4DA not found, broken font? Trying all charmaps
AV: 00:00:04 / 00:00:14 (27%) A-V:  0.000 Cache: 10s/1MB
```

My libass version is 0.17.1, and the font provider is fontconfig (yours is coretext). The last line of your log is concerning.

**Comment by simurgh9** [comment]
I am lost then ... what should I do? I am not very savy about font providers.

**Comment by dabcd** [comment]
Me neither, I found a similar message for example [here](https://developer.apple.com/forums/thread/652213), seems to be Mac related.
Maybe try to open a new issue? Attach these logs.

**Comment by simurgh9** [comment]
@Akemi @CounterPillow Should I open a new bug report?  If you could look at the last few responses.

**Comment by simurgh9** [comment]
@dabcd do you know if there is a way to disable that little strip with the video name?

**Comment by simurgh9** [comment]
Okay here is another strange thing, I tried,

~~~
mpv --osd-font-provider="fontconfig" "https://www.youtube.com/watch?v=jfKfPfyJRdk"
~~~

And got,

```
[osd/libass] can't find selected font provider
[osd/libass] can't find selected font provider
```

Even though I can use things like `fc-list` where does mpv look for the fontconfig?

**Comment by gsbabil** [comment]
#### # THE PROBLEM

📌 For people who are still struggling with these issues, my core observation here is that:
- [`libass`](https://github.com/libass/libass), the library used by `mpv` to render and display sub-titles, apparently does not support colorful emojis.
- Only monochrome emojis are handled by the version of `libass` used in `mpv`, which is why we need one of the following:
    - Either use an emoji font that either supports only monochrome emojis, or 
    - Use an emoji font that has both colored and monochrome emojis in the same font file.

#### # CURRENT WORKAROUND

📌 For `Mac` users, here's what solved my issues for `osd` and `subtitles`:

```sh
## Install "Twitter Color Emoji" font
brew install font-twitter-color-emoji

## Specify font to use by mpv in `osd` and `subtitles`
echo 'osd-font="Twitter Color Emoji"' >> $HOME/.config/mpv/mpv.conf
echo 'sub-font="Twitter Color Emoji"' >> $HOME/.config/mpv/mpv.conf
```

📌 Alternatively, you can start `mpv` with `--sub-font` and `--osd-font` options as shown below:

```
mpv --osd-font="Twitter Color Emoji" --sub-font="Twitter Color Emoji"  video.mp4
```

#### # ADDITIONAL NOTES

📌 My current `mpv` version is as shown below:

```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Mon Jul 24 01:30:19 2023
FFmpeg version: 5.1.3
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
```

📌 I didn't need to reconfigure the `$HOMEBREW_PREFIX/etc/fonts/local.conf` as discussed [here](https://github.com/mpv-player/mpv/issues/8919#issuecomment-1590604306) or [here](https://github.com/mpv-player/mpv/issues/8919#issuecomment-1174493995), and after installing a compatible font, _e.g._, "Twitter Color Emoji", the steps above, I think, should work fine on Linux too.


Hope this helps someone. Thanks!

**Comment by simurgh9** [comment]
@gsbabil, your solutions works but funnily enough, `[osd/libass] Glyph 0x1F4DA not found, broken font? Trying all charmaps` still gets printed on the console once.
