### ISSUE TITLE
Video freezes when audio sent over network with Pulseaudio

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#959]
Hello,

I can use Pulseaudio (pacmd load-module module-tunnel-sink server=192.168.1.14) to add a Pulseaudio sink that transmit audio over the network to a configured server. I can then select this sink for mpv.

This works well, except it makes the video freeze, either instantly, or after a few seconds. The UI also freezes (both LUA and terminal). I can still use it (seek, pause, etc) but the video will not unfreeze, or freeze again shortly after seeking.

When I let the file play completely, it will first finish the audio stream, then either unfreeze the video and silently play it until the end, or hang with a message like "[lavf] Too many packets in the demuxer packet queue (video: 4097 packets in 32420546 bytes, audio: 0 packets in 0 bytes, sub: 0 packets in 0 bytes)."

**Comment by hi117** [comment]
Sorry to bump an old issue, but I had the exact same problem and fixed it unrelated to mpv or pulseaudio.  I was running it on a slower system that could just barely handle the video.  When video entropy shot up, it froze.  I fixed it by setting framedrop to decoder+vo, though this only hides the root problem and still doesn't change the not our bug tag.

**Comment by wm4** [comment]
Maybe pulse wants us to do something after an underflow or so.

**Comment by wm4** [comment]
Just yesterday or so I had a report that seeking occasionally didn't resume audio with pulse, so maybe there's something fishy here.

**Comment by lachs0r** [comment]
I can’t reproduce this with recent PulseAudio. It’s still extremely bad at network audio, but this problem seems to have been solved.

**Comment by intelfx** [comment]
Yes, it's gone, especially when using the not-yet-default `module-tunnel-sink-new` implementation.

**Comment by majewsky** [comment]
I can still reproduce this with mpv 0.27.2 and PulseAudio 11.1 when using `module-tunnel-sink`. `module-tunnel-sink-new` works fine, but sucks because it's not zeroconf. :(

**Comment by uservinu** [comment]
Make sure the system time is synchronized in all clients and server.
