### ISSUE TITLE
Iris Xe: unsupported VA image format nv12 and blue image while trying to use vaapi decoding and vulkan

### ISSUE THREAD

**Issue by m911t** [mpv-player/mpv#9674]
### Important Information

Provide following Information:
- mpv version: 0.34.0
- Linux Distribution and Version: Fedora 35
- Source of the mpv binary: RPMfusion
- If known which version of mpv introduced the problem
- Window Manager and version: Gnome
- GPU driver and version: Mesa Iris, 21.3.3
- Possible screenshot or video of visual glitches

![Screenshot from 2022-01-04 23-29-59](https://user-images.githubusercontent.com/78878262/148161275-55006896-f496-45c9-bf06-aa8c709c97a9.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

1. run "mpv --hwdec=auto --gpu-api=vulkan "https://www.youtube.com/watch?v=4IKUEpn1DjE"

### Expected behavior
a player window appears and it shows the video properly

### Actual behavior
a player window appears but it only shows a blue screen, audio plays

### Log file
[mpv-log.txt](https://github.com/mpv-player/mpv/files/7812019/mpv-log.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by haasn** [comment]
Probably fixed by haasn/libplacebo@8cc4da8f90904d28412c7f29c9818fb3fe142bcd

**Comment by m911t** [comment]
> Probably fixed by [haasn/libplacebo@8cc4da8](https://github.com/haasn/libplacebo/commit/8cc4da8f90904d28412c7f29c9818fb3fe142bcd)

Is this commit in a release? Fedora has 4.157.0.1.fc35

**Comment by focus64** [comment]
I am on the same hardware but running Arch (Gnome wayland).

I can attest that with hwdec enabled (vaapi), vulkan/waylandvk settings, the problem still persists with the latest libplacebo (built off from libplacebo-git in AUR.) with the following error messages:

`[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).`
`[vo/gpu/vaapi-egl] unsupported VA image format nv12`
`[vo/gpu] Initializing texture for hardware decoding failed.`

However, if hwdec is disabled and vulkan is still in use, the playback is normal.

Also there are two warnings as long as vulkan is used:

`[vo/gpu/vulkan/libplacebo] Storable format 'bgr565' has no matching GLSL format qualifier but read/write without format is not supported.. disabling`
`[vo/gpu/vulkan/libplacebo] Storable format 'bgr5a1' has no matching GLSL format qualifier but read/write without format is not supported.. disabling`

**Comment by m911t** [comment]
yeah, I get the same messages, should be in the log I uploaded. You can use hwdec = vaapi-copy but that uses much more gpu.

**Comment by philipl** [comment]
This is an anv driver bug. https://gitlab.freedesktop.org/mesa/mesa/-/issues/5940

**Comment by philipl** [comment]
Closing as an upstream bug. I have provided a proposed fix in the linked issue.

**Comment by infinitecurse** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/15181 doesn't seem to help for me.

**Comment by philipl** [comment]
@infinitecurse Please file a new issue with all your information and logs. The fix in that MR works for me.
